// <auto-generated>
// Code generated by csilgen; DO NOT EDIT.
// </auto-generated>
#nullable enable

namespace corndogs;

/// <summary>The caller-supplied dumb byte transport seam. The generated client owns
/// (de)serialization (canonical CBOR via the generated codec); the transport only
/// moves bytes — it performs the call named by (service, op) with the already-encoded
/// request and returns the response bytes. Synchronous and blocking — no Task/async.</summary>
public interface ICsilTransport
{
    byte[] Call(string service, string op, byte[] request);
}

/// <summary>Raised by a generated client when the transport reports a failure.</summary>
public sealed class CsilClientException : System.Exception
{
    public long Code { get; }

    public CsilClientException(long code, string message) : base(message)
    {
        Code = code;
    }
}

/// <summary>Typed RPC client for the CorndogsService service. The client owns
/// (de)serialization via the generated codec; the transport only moves bytes.</summary>
public sealed class CorndogsClient(ICsilTransport transport)
{
    public SubmitTaskResponse SubmitTask(SubmitTaskRequest submitTaskRequest) =>
        Codec.Decode<SubmitTaskResponse>(transport.Call("CorndogsService", "SubmitTask", Codec.Encode(submitTaskRequest)));
    public GetTaskStateByIDResponse GetTaskStateByID(GetTaskStateByIDRequest getTaskStateByIDRequest) =>
        Codec.Decode<GetTaskStateByIDResponse>(transport.Call("CorndogsService", "GetTaskStateByID", Codec.Encode(getTaskStateByIDRequest)));
    public GetNextTaskResponse GetNextTask(GetNextTaskRequest getNextTaskRequest) =>
        Codec.Decode<GetNextTaskResponse>(transport.Call("CorndogsService", "GetNextTask", Codec.Encode(getNextTaskRequest)));
    public GetNextTaskGroupResponse GetNextTaskGroup(GetNextTaskGroupRequest getNextTaskGroupRequest) =>
        Codec.Decode<GetNextTaskGroupResponse>(transport.Call("CorndogsService", "GetNextTaskGroup", Codec.Encode(getNextTaskGroupRequest)));
    public UpdateTaskResponse UpdateTask(UpdateTaskRequest updateTaskRequest) =>
        Codec.Decode<UpdateTaskResponse>(transport.Call("CorndogsService", "UpdateTask", Codec.Encode(updateTaskRequest)));
    public CompleteTaskResponse CompleteTask(CompleteTaskRequest completeTaskRequest) =>
        Codec.Decode<CompleteTaskResponse>(transport.Call("CorndogsService", "CompleteTask", Codec.Encode(completeTaskRequest)));
    public CancelTaskResponse CancelTask(CancelTaskRequest cancelTaskRequest) =>
        Codec.Decode<CancelTaskResponse>(transport.Call("CorndogsService", "CancelTask", Codec.Encode(cancelTaskRequest)));
    public CleanUpTimedOutResponse CleanUpTimedOut(CleanUpTimedOutRequest cleanUpTimedOutRequest) =>
        Codec.Decode<CleanUpTimedOutResponse>(transport.Call("CorndogsService", "CleanUpTimedOut", Codec.Encode(cleanUpTimedOutRequest)));
    public GetQueuesResponse GetQueues(GetQueuesRequest getQueuesRequest) =>
        Codec.Decode<GetQueuesResponse>(transport.Call("CorndogsService", "GetQueues", Codec.Encode(getQueuesRequest)));
    public GetQueueTaskCountsResponse GetQueueTaskCounts(GetQueueTaskCountsRequest getQueueTaskCountsRequest) =>
        Codec.Decode<GetQueueTaskCountsResponse>(transport.Call("CorndogsService", "GetQueueTaskCounts", Codec.Encode(getQueueTaskCountsRequest)));
    public GetTaskStateCountsResponse GetTaskStateCounts(GetTaskStateCountsRequest getTaskStateCountsRequest) =>
        Codec.Decode<GetTaskStateCountsResponse>(transport.Call("CorndogsService", "GetTaskStateCounts", Codec.Encode(getTaskStateCountsRequest)));
    public GetQueueAndStateCountsResponse GetQueueAndStateCounts(GetQueueAndStateCountsRequest getQueueAndStateCountsRequest) =>
        Codec.Decode<GetQueueAndStateCountsResponse>(transport.Call("CorndogsService", "GetQueueAndStateCounts", Codec.Encode(getQueueAndStateCountsRequest)));
}

