// <auto-generated>
// Code generated by csilgen; DO NOT EDIT.
// </auto-generated>
#nullable enable

namespace corndogs;

/// <summary>The caller-supplied dumb byte transport seam (async variant). The generated
/// client owns (de)serialization (canonical CBOR via the generated codec); the transport
/// only moves bytes — it performs the call named by (service, op) with the already-encoded
/// request and returns a Task of the response bytes. The generated codec stays synchronous.</summary>
public interface ICsilAsyncTransport
{
    System.Threading.Tasks.Task<byte[]> Call(string service, string op, byte[] request);
}

/// <summary>Typed RPC client for the CorndogsService service. The client owns
/// (de)serialization via the generated codec; the transport only moves bytes.</summary>
public sealed class CorndogsAsyncClient(ICsilAsyncTransport transport)
{
    public async System.Threading.Tasks.Task<SubmitTaskResponse> SubmitTaskAsync(SubmitTaskRequest submitTaskRequest) =>
        Codec.Decode<SubmitTaskResponse>(await transport.Call("CorndogsService", "SubmitTask", Codec.Encode(submitTaskRequest)));
    public async System.Threading.Tasks.Task<GetTaskStateByIDResponse> GetTaskStateByIDAsync(GetTaskStateByIDRequest getTaskStateByIDRequest) =>
        Codec.Decode<GetTaskStateByIDResponse>(await transport.Call("CorndogsService", "GetTaskStateByID", Codec.Encode(getTaskStateByIDRequest)));
    public async System.Threading.Tasks.Task<GetNextTaskResponse> GetNextTaskAsync(GetNextTaskRequest getNextTaskRequest) =>
        Codec.Decode<GetNextTaskResponse>(await transport.Call("CorndogsService", "GetNextTask", Codec.Encode(getNextTaskRequest)));
    public async System.Threading.Tasks.Task<GetNextTaskGroupResponse> GetNextTaskGroupAsync(GetNextTaskGroupRequest getNextTaskGroupRequest) =>
        Codec.Decode<GetNextTaskGroupResponse>(await transport.Call("CorndogsService", "GetNextTaskGroup", Codec.Encode(getNextTaskGroupRequest)));
    public async System.Threading.Tasks.Task<UpdateTaskResponse> UpdateTaskAsync(UpdateTaskRequest updateTaskRequest) =>
        Codec.Decode<UpdateTaskResponse>(await transport.Call("CorndogsService", "UpdateTask", Codec.Encode(updateTaskRequest)));
    public async System.Threading.Tasks.Task<CompleteTaskResponse> CompleteTaskAsync(CompleteTaskRequest completeTaskRequest) =>
        Codec.Decode<CompleteTaskResponse>(await transport.Call("CorndogsService", "CompleteTask", Codec.Encode(completeTaskRequest)));
    public async System.Threading.Tasks.Task<CancelTaskResponse> CancelTaskAsync(CancelTaskRequest cancelTaskRequest) =>
        Codec.Decode<CancelTaskResponse>(await transport.Call("CorndogsService", "CancelTask", Codec.Encode(cancelTaskRequest)));
    public async System.Threading.Tasks.Task<CleanUpTimedOutResponse> CleanUpTimedOutAsync(CleanUpTimedOutRequest cleanUpTimedOutRequest) =>
        Codec.Decode<CleanUpTimedOutResponse>(await transport.Call("CorndogsService", "CleanUpTimedOut", Codec.Encode(cleanUpTimedOutRequest)));
    public async System.Threading.Tasks.Task<GetQueuesResponse> GetQueuesAsync(GetQueuesRequest getQueuesRequest) =>
        Codec.Decode<GetQueuesResponse>(await transport.Call("CorndogsService", "GetQueues", Codec.Encode(getQueuesRequest)));
    public async System.Threading.Tasks.Task<GetQueueTaskCountsResponse> GetQueueTaskCountsAsync(GetQueueTaskCountsRequest getQueueTaskCountsRequest) =>
        Codec.Decode<GetQueueTaskCountsResponse>(await transport.Call("CorndogsService", "GetQueueTaskCounts", Codec.Encode(getQueueTaskCountsRequest)));
    public async System.Threading.Tasks.Task<GetTaskStateCountsResponse> GetTaskStateCountsAsync(GetTaskStateCountsRequest getTaskStateCountsRequest) =>
        Codec.Decode<GetTaskStateCountsResponse>(await transport.Call("CorndogsService", "GetTaskStateCounts", Codec.Encode(getTaskStateCountsRequest)));
    public async System.Threading.Tasks.Task<GetQueueAndStateCountsResponse> GetQueueAndStateCountsAsync(GetQueueAndStateCountsRequest getQueueAndStateCountsRequest) =>
        Codec.Decode<GetQueueAndStateCountsResponse>(await transport.Call("CorndogsService", "GetQueueAndStateCounts", Codec.Encode(getQueueAndStateCountsRequest)));
    public async System.Threading.Tasks.Task<GetServerInfoResponse> GetServerInfoAsync(GetServerInfoRequest getServerInfoRequest) =>
        Codec.Decode<GetServerInfoResponse>(await transport.Call("CorndogsService", "GetServerInfo", Codec.Encode(getServerInfoRequest)));
    public async System.Threading.Tasks.Task<SubmitKeyedTaskResponse> SubmitKeyedTaskAsync(SubmitKeyedTaskRequest submitKeyedTaskRequest) =>
        Codec.Decode<SubmitKeyedTaskResponse>(await transport.Call("CorndogsService", "SubmitKeyedTask", Codec.Encode(submitKeyedTaskRequest)));
    public async System.Threading.Tasks.Task<LookupSubmissionResponse> LookupSubmissionAsync(LookupSubmissionRequest lookupSubmissionRequest) =>
        Codec.Decode<LookupSubmissionResponse>(await transport.Call("CorndogsService", "LookupSubmission", Codec.Encode(lookupSubmissionRequest)));
    public async System.Threading.Tasks.Task<ClaimGuardedTaskResponse> ClaimGuardedTaskAsync(ClaimGuardedTaskRequest claimGuardedTaskRequest) =>
        Codec.Decode<ClaimGuardedTaskResponse>(await transport.Call("CorndogsService", "ClaimGuardedTask", Codec.Encode(claimGuardedTaskRequest)));
    public async System.Threading.Tasks.Task<ClaimGuardedTaskGroupResponse> ClaimGuardedTaskGroupAsync(ClaimGuardedTaskGroupRequest claimGuardedTaskGroupRequest) =>
        Codec.Decode<ClaimGuardedTaskGroupResponse>(await transport.Call("CorndogsService", "ClaimGuardedTaskGroup", Codec.Encode(claimGuardedTaskGroupRequest)));
    public async System.Threading.Tasks.Task<UpdateGuardedTaskResponse> UpdateGuardedTaskAsync(UpdateGuardedTaskRequest updateGuardedTaskRequest) =>
        Codec.Decode<UpdateGuardedTaskResponse>(await transport.Call("CorndogsService", "UpdateGuardedTask", Codec.Encode(updateGuardedTaskRequest)));
    public async System.Threading.Tasks.Task<CompleteGuardedTaskResponse> CompleteGuardedTaskAsync(CompleteGuardedTaskRequest completeGuardedTaskRequest) =>
        Codec.Decode<CompleteGuardedTaskResponse>(await transport.Call("CorndogsService", "CompleteGuardedTask", Codec.Encode(completeGuardedTaskRequest)));
    public async System.Threading.Tasks.Task<CancelGuardedTaskResponse> CancelGuardedTaskAsync(CancelGuardedTaskRequest cancelGuardedTaskRequest) =>
        Codec.Decode<CancelGuardedTaskResponse>(await transport.Call("CorndogsService", "CancelGuardedTask", Codec.Encode(cancelGuardedTaskRequest)));
    public async System.Threading.Tasks.Task<GetGuardedTaskResponse> GetGuardedTaskAsync(GetGuardedTaskRequest getGuardedTaskRequest) =>
        Codec.Decode<GetGuardedTaskResponse>(await transport.Call("CorndogsService", "GetGuardedTask", Codec.Encode(getGuardedTaskRequest)));
    public async System.Threading.Tasks.Task<LookupOperationResponse> LookupOperationAsync(LookupOperationRequest lookupOperationRequest) =>
        Codec.Decode<LookupOperationResponse>(await transport.Call("CorndogsService", "LookupOperation", Codec.Encode(lookupOperationRequest)));
}

