// <auto-generated>
// Code generated by csilgen; DO NOT EDIT.
// </auto-generated>
#nullable enable

namespace corndogs;

/// <summary>The caller-supplied dumb byte transport seam (async variant). The generated
/// client owns (de)serialization (canonical CBOR via the generated codec); the transport
/// only moves bytes — it performs the call named by (service, op) with the already-encoded
/// request and returns a Task of the response bytes. The generated codec stays synchronous.</summary>
public interface ICsilAsyncTransport
{
    System.Threading.Tasks.Task<byte[]> Call(string service, string op, byte[] request);
}

/// <summary>Typed RPC client for the CorndogsService service. The client owns
/// (de)serialization via the generated codec; the transport only moves bytes.</summary>
public sealed class CorndogsAsyncClient(ICsilAsyncTransport transport)
{
    public async System.Threading.Tasks.Task<SubmitTaskResponse> SubmitTaskAsync(SubmitTaskRequest submitTaskRequest) =>
        Codec.Decode<SubmitTaskResponse>(await transport.Call("corndogs", "SubmitTask", Codec.Encode(submitTaskRequest)));
    public async System.Threading.Tasks.Task<GetTaskStateByIDResponse> GetTaskStateByIDAsync(GetTaskStateByIDRequest getTaskStateByIDRequest) =>
        Codec.Decode<GetTaskStateByIDResponse>(await transport.Call("corndogs", "GetTaskStateByID", Codec.Encode(getTaskStateByIDRequest)));
    public async System.Threading.Tasks.Task<GetNextTaskResponse> GetNextTaskAsync(GetNextTaskRequest getNextTaskRequest) =>
        Codec.Decode<GetNextTaskResponse>(await transport.Call("corndogs", "GetNextTask", Codec.Encode(getNextTaskRequest)));
    public async System.Threading.Tasks.Task<UpdateTaskResponse> UpdateTaskAsync(UpdateTaskRequest updateTaskRequest) =>
        Codec.Decode<UpdateTaskResponse>(await transport.Call("corndogs", "UpdateTask", Codec.Encode(updateTaskRequest)));
    public async System.Threading.Tasks.Task<CompleteTaskResponse> CompleteTaskAsync(CompleteTaskRequest completeTaskRequest) =>
        Codec.Decode<CompleteTaskResponse>(await transport.Call("corndogs", "CompleteTask", Codec.Encode(completeTaskRequest)));
    public async System.Threading.Tasks.Task<CancelTaskResponse> CancelTaskAsync(CancelTaskRequest cancelTaskRequest) =>
        Codec.Decode<CancelTaskResponse>(await transport.Call("corndogs", "CancelTask", Codec.Encode(cancelTaskRequest)));
    public async System.Threading.Tasks.Task<CleanUpTimedOutResponse> CleanUpTimedOutAsync(CleanUpTimedOutRequest cleanUpTimedOutRequest) =>
        Codec.Decode<CleanUpTimedOutResponse>(await transport.Call("corndogs", "CleanUpTimedOut", Codec.Encode(cleanUpTimedOutRequest)));
    public async System.Threading.Tasks.Task<GetQueuesResponse> GetQueuesAsync(GetQueuesRequest getQueuesRequest) =>
        Codec.Decode<GetQueuesResponse>(await transport.Call("corndogs", "GetQueues", Codec.Encode(getQueuesRequest)));
    public async System.Threading.Tasks.Task<GetQueueTaskCountsResponse> GetQueueTaskCountsAsync(GetQueueTaskCountsRequest getQueueTaskCountsRequest) =>
        Codec.Decode<GetQueueTaskCountsResponse>(await transport.Call("corndogs", "GetQueueTaskCounts", Codec.Encode(getQueueTaskCountsRequest)));
    public async System.Threading.Tasks.Task<GetTaskStateCountsResponse> GetTaskStateCountsAsync(GetTaskStateCountsRequest getTaskStateCountsRequest) =>
        Codec.Decode<GetTaskStateCountsResponse>(await transport.Call("corndogs", "GetTaskStateCounts", Codec.Encode(getTaskStateCountsRequest)));
    public async System.Threading.Tasks.Task<GetQueueAndStateCountsResponse> GetQueueAndStateCountsAsync(GetQueueAndStateCountsRequest getQueueAndStateCountsRequest) =>
        Codec.Decode<GetQueueAndStateCountsResponse>(await transport.Call("corndogs", "GetQueueAndStateCounts", Codec.Encode(getQueueAndStateCountsRequest)));
}

