// <auto-generated>
// Code generated by csilgen; DO NOT EDIT.
// </auto-generated>
#nullable enable

using System.Linq;

namespace corndogs;

/// <summary>A minimal canonical-CBOR value tree: the closed set of variants the
/// generated codec builds and walks.</summary>
public abstract record CborValue
{
    public sealed record Uint(ulong Value) : CborValue;
    public sealed record Int(long Value) : CborValue;
    public sealed record Bool(bool Value) : CborValue;
    public sealed record Float(double Value) : CborValue;
    public sealed record Null : CborValue;
    public sealed record Text(string Value) : CborValue;
    public sealed record Bytes(byte[] Value) : CborValue;
    public sealed record Array(System.Collections.Generic.IReadOnlyList<CborValue> Items) : CborValue;
    public sealed record Map(System.Collections.Generic.IReadOnlyList<(CborValue Key, CborValue Value)> Entries) : CborValue;
    public sealed record Tag(ulong Number, CborValue Inner) : CborValue;
}

/// <summary>Raised when a CBOR payload is malformed or a value has an unexpected type.</summary>
public sealed class CborException : System.Exception
{
    public CborException(string message) : base(message) { }
}

/// <summary>The canonical-CBOR encoder, decoder, and typed accessors.</summary>
public static partial class Cbor
{
    public static byte[] Encode(CborValue value)
    {
        var csilOut = new System.Collections.Generic.List<byte>();
        Enc(value, csilOut);
        return csilOut.ToArray();
    }

    static void Head(byte major, ulong n, System.Collections.Generic.List<byte> csilOut)
    {
        var mt = (byte)(major << 5);
        if (n < 24)
        {
            csilOut.Add((byte)(mt | (byte)n));
        }
        else if (n < 0x100)
        {
            csilOut.Add((byte)(mt | 24));
            csilOut.Add((byte)n);
        }
        else if (n < 0x1_0000)
        {
            csilOut.Add((byte)(mt | 25));
            csilOut.Add((byte)(n >> 8));
            csilOut.Add((byte)(n & 0xff));
        }
        else if (n < 0x1_0000_0000)
        {
            csilOut.Add((byte)(mt | 26));
            for (int csilI = 24; csilI >= 0; csilI -= 8) { csilOut.Add((byte)((n >> csilI) & 0xff)); }
        }
        else
        {
            csilOut.Add((byte)(mt | 27));
            for (int csilI = 56; csilI >= 0; csilI -= 8) { csilOut.Add((byte)((n >> csilI) & 0xff)); }
        }
    }

    static void Enc(CborValue v, System.Collections.Generic.List<byte> csilOut)
    {
        switch (v)
        {
            case CborValue.Uint x:
                Head(0, x.Value, csilOut);
                break;
            case CborValue.Int x:
                if (x.Value >= 0) { Head(0, (ulong)x.Value, csilOut); }
                else { Head(1, (ulong)(-(x.Value + 1)), csilOut); }
                break;
            case CborValue.Bool x:
                csilOut.Add(x.Value ? (byte)0xf5 : (byte)0xf4);
                break;
            case CborValue.Null:
                csilOut.Add(0xf6);
                break;
            case CborValue.Float x:
                csilOut.Add(0xfb);
                var csilBits = System.BitConverter.DoubleToUInt64Bits(x.Value);
                for (int csilI = 56; csilI >= 0; csilI -= 8) { csilOut.Add((byte)((csilBits >> csilI) & 0xff)); }
                break;
            case CborValue.Text x:
                var csilU = System.Text.Encoding.UTF8.GetBytes(x.Value);
                Head(3, (ulong)csilU.Length, csilOut);
                csilOut.AddRange(csilU);
                break;
            case CborValue.Bytes x:
                Head(2, (ulong)x.Value.Length, csilOut);
                csilOut.AddRange(x.Value);
                break;
            case CborValue.Array x:
                Head(4, (ulong)x.Items.Count, csilOut);
                foreach (var csilItem in x.Items) { Enc(csilItem, csilOut); }
                break;
            case CborValue.Map x:
                Head(5, (ulong)x.Entries.Count, csilOut);
                foreach (var csilEntry in x.Entries) { Enc(csilEntry.Key, csilOut); Enc(csilEntry.Value, csilOut); }
                break;
            case CborValue.Tag x:
                Head(6, x.Number, csilOut);
                Enc(x.Inner, csilOut);
                break;
            default:
                throw new CborException("unknown CBOR value");
        }
    }

    public static CborValue Decode(byte[] b)
    {
        int csilPos = 0;
        var v = Dec(b, ref csilPos, 0);
        if (csilPos != b.Length) { throw new CborException("trailing bytes"); }
        return v;
    }

    static ulong ReadArg(byte[] b, ref int csilPos, byte low)
    {
        if (low < 24) { csilPos += 1; return low; }
        int csilWidth = low == 24 ? 1 : low == 25 ? 2 : low == 26 ? 4 : low == 27 ? 8 : 0;
        if (csilWidth == 0 || csilPos >= b.Length || b.Length - csilPos - 1 < csilWidth)
        {
            throw new CborException("truncated argument");
        }
        switch (low)
        {
            case 24:
            {
                ulong v = b[csilPos + 1];
                csilPos += 2;
                return v;
            }
            case 25:
            {
                ulong v = ((ulong)b[csilPos + 1] << 8) | b[csilPos + 2];
                csilPos += 3;
                return v;
            }
            case 26:
            {
                ulong v = 0;
                for (int csilI = 1; csilI <= 4; csilI++) { v = (v << 8) | b[csilPos + csilI]; }
                csilPos += 5;
                return v;
            }
            case 27:
            {
                ulong v = 0;
                for (int csilI = 1; csilI <= 8; csilI++) { v = (v << 8) | b[csilPos + csilI]; }
                csilPos += 9;
                return v;
            }
            default:
                throw new CborException("malformed");
        }
    }

    // PreallocLimit bounds the elements a decoded array or map reserves before it reads
    // them. The declared length is checked against the remaining input, but one input
    // byte can become a much larger value, so reserving the full declared length lets a
    // small frame reserve a large multiple of its size at every nesting level.
    const int PreallocLimit = 1024;

    static CborValue Dec(byte[] b, ref int csilPos, int csilDepth)
    {
        if (csilDepth > 64) { throw new CborException("nesting limit exceeded"); }
        if (csilPos >= b.Length) { throw new CborException("unexpected end of input"); }
        var ib = b[csilPos];
        var major = (byte)(ib >> 5);
        var low = (byte)(ib & 0x1f);
        if (major == 7)
        {
            switch (low)
            {
                case 20: csilPos += 1; return new CborValue.Bool(false);
                case 21: csilPos += 1; return new CborValue.Bool(true);
                case 22:
                case 23: csilPos += 1; return new CborValue.Null();
                case 26:
                {
                    var bits = ReadArg(b, ref csilPos, low);
                    return new CborValue.Float(System.BitConverter.UInt32BitsToSingle((uint)bits));
                }
                case 27:
                {
                    var bits = ReadArg(b, ref csilPos, low);
                    return new CborValue.Float(System.BitConverter.UInt64BitsToDouble(bits));
                }
                default:
                    throw new CborException("malformed");
            }
        }
        var arg = ReadArg(b, ref csilPos, low);
        switch (major)
        {
            case 0:
                return new CborValue.Uint(arg);
            case 1:
                if (arg > long.MaxValue) { throw new CborException("malformed"); }
                return new CborValue.Int(-1 - (long)arg);
            case 2:
            {
                if (arg > (ulong)(b.Length - csilPos)) { throw new CborException("truncated byte string"); }
                var n = (int)arg;
                var slice = new byte[n];
                System.Array.Copy(b, csilPos, slice, 0, n);
                csilPos += n;
                return new CborValue.Bytes(slice);
            }
            case 3:
            {
                if (arg > (ulong)(b.Length - csilPos)) { throw new CborException("truncated text string"); }
                var n = (int)arg;
                string s;
                try { s = new System.Text.UTF8Encoding(false, true).GetString(b, csilPos, n); }
                catch (System.Text.DecoderFallbackException) { throw new CborException("invalid utf-8"); }
                csilPos += n;
                return new CborValue.Text(s);
            }
            case 4:
            {
                if (arg > (ulong)(b.Length - csilPos)) { throw new CborException("array length exceeds remaining input"); }
                var n = (int)arg;
                var items = new System.Collections.Generic.List<CborValue>(System.Math.Min(n, PreallocLimit));
                for (int csilI = 0; csilI < n; csilI++) { items.Add(Dec(b, ref csilPos, csilDepth + 1)); }
                return new CborValue.Array(items);
            }
            case 5:
            {
                if (arg > (ulong)(b.Length - csilPos)) { throw new CborException("map length exceeds remaining input"); }
                var n = (int)arg;
                var kvs = new System.Collections.Generic.List<(CborValue, CborValue)>(System.Math.Min(n, PreallocLimit));
                for (int csilI = 0; csilI < n; csilI++)
                {
                    var k = Dec(b, ref csilPos, csilDepth + 1);
                    var val = Dec(b, ref csilPos, csilDepth + 1);
                    kvs.Add((k, val));
                }
                return new CborValue.Map(kvs);
            }
            case 6:
            {
                var inner = Dec(b, ref csilPos, csilDepth + 1);
                return new CborValue.Tag(arg, inner);
            }
            default:
                throw new CborException("malformed");
        }
    }

    public static CborValue? MapGet(CborValue v, string key)
    {
        if (v is CborValue.Map m)
        {
            foreach (var e in m.Entries)
            {
                if (e.Key is CborValue.Text t && t.Value == key) { return e.Value; }
            }
        }
        return null;
    }

    public static CborValue Require(CborValue v, string key) =>
        MapGet(v, key) ?? throw new CborException($"missing field '{key}'");

    public static T ExpectLiteral<T>(CborValue actual, CborValue expected, T value)
    {
        if (!ValueEquals(actual, expected))
            throw new CborException("literal mismatch");
        return value;
    }

    static bool ValueEquals(CborValue actual, CborValue expected) => (actual, expected) switch
    {
        (CborValue.Uint a, CborValue.Uint b) => a.Value == b.Value,
        (CborValue.Int a, CborValue.Int b) => a.Value == b.Value,
        (CborValue.Bool a, CborValue.Bool b) => a.Value == b.Value,
        (CborValue.Float a, CborValue.Float b) => a.Value == b.Value,
        (CborValue.Null, CborValue.Null) => true,
        (CborValue.Text a, CborValue.Text b) => a.Value == b.Value,
        (CborValue.Bytes a, CborValue.Bytes b) => a.Value.SequenceEqual(b.Value),
        (CborValue.Array a, CborValue.Array b) => a.Items.Count == b.Items.Count && a.Items.Zip(b.Items).All(p => ValueEquals(p.First, p.Second)),
        _ => false,
    };

    public static long AsI64(CborValue v) => v switch
    {
        CborValue.Uint x when x.Value <= long.MaxValue => (long)x.Value,
        CborValue.Int x => x.Value,
        _ => throw new CborException("expected integer"),
    };

    public static ulong AsU64(CborValue v) => v switch
    {
        CborValue.Uint x => x.Value,
        CborValue.Int x when x.Value >= 0 => (ulong)x.Value,
        _ => throw new CborException("expected unsigned integer"),
    };

    public static double AsDouble(CborValue v) => v switch
    {
        CborValue.Float x => x.Value,
        CborValue.Uint x => x.Value,
        CborValue.Int x => x.Value,
        _ => throw new CborException("expected float"),
    };

    public static bool AsBool(CborValue v) =>
        v is CborValue.Bool x ? x.Value : throw new CborException("expected bool");

    public static string AsText(CborValue v) =>
        v is CborValue.Text x ? x.Value : throw new CborException("expected text");

    public static byte[] AsBytes(CborValue v) =>
        v is CborValue.Bytes x ? x.Value : throw new CborException("expected bytes");

    public static System.Collections.Generic.IReadOnlyList<CborValue> AsArray(CborValue v) =>
        v is CborValue.Array x ? x.Items : throw new CborException("expected array");

    public static System.Collections.Generic.IReadOnlyList<(CborValue Key, CborValue Value)> AsMap(CborValue v) =>
        v is CborValue.Map x ? x.Entries : throw new CborException("expected map");

    public static string AsTaggedText(CborValue v, ulong num) =>
        v is CborValue.Tag x && x.Number == num ? AsText(x.Inner) : throw new CborException("expected tagged text");
}

/// <summary>The typed CBOR codec: encodes/decodes a generated record to and
/// from canonical CSIL CBOR bytes. Static type dispatch, never reflection.</summary>
public static class Codec
{
    public static byte[] Encode<T>(T value) => Cbor.Encode(ToCborValue(value!));

    public static T Decode<T>(byte[] data) => (T)FromCborValue(typeof(T), Cbor.Decode(data));

    static CborValue ToCborValue(object value) => value switch
    {
        Task csilTyped => TaskToCborValue(csilTyped),
        TaskDelivery csilTyped => TaskDeliveryToCborValue(csilTyped),
        SubmitTaskRequest csilTyped => SubmitTaskRequestToCborValue(csilTyped),
        SubmitTaskResponse csilTyped => SubmitTaskResponseToCborValue(csilTyped),
        GetTaskStateByIDRequest csilTyped => GetTaskStateByIDRequestToCborValue(csilTyped),
        GetTaskStateByIDResponse csilTyped => GetTaskStateByIDResponseToCborValue(csilTyped),
        GetNextTaskRequest csilTyped => GetNextTaskRequestToCborValue(csilTyped),
        GetNextTaskResponse csilTyped => GetNextTaskResponseToCborValue(csilTyped),
        GetNextTaskGroupRequest csilTyped => GetNextTaskGroupRequestToCborValue(csilTyped),
        GetNextTaskGroupResponse csilTyped => GetNextTaskGroupResponseToCborValue(csilTyped),
        CompleteTaskRequest csilTyped => CompleteTaskRequestToCborValue(csilTyped),
        CompleteTaskResponse csilTyped => CompleteTaskResponseToCborValue(csilTyped),
        UpdateTaskRequest csilTyped => UpdateTaskRequestToCborValue(csilTyped),
        UpdateTaskResponse csilTyped => UpdateTaskResponseToCborValue(csilTyped),
        CancelTaskRequest csilTyped => CancelTaskRequestToCborValue(csilTyped),
        CancelTaskResponse csilTyped => CancelTaskResponseToCborValue(csilTyped),
        CleanUpTimedOutRequest csilTyped => CleanUpTimedOutRequestToCborValue(csilTyped),
        CleanUpTimedOutResponse csilTyped => CleanUpTimedOutResponseToCborValue(csilTyped),
        GetQueuesRequest csilTyped => GetQueuesRequestToCborValue(csilTyped),
        GetQueuesResponse csilTyped => GetQueuesResponseToCborValue(csilTyped),
        GetQueueTaskCountsRequest csilTyped => GetQueueTaskCountsRequestToCborValue(csilTyped),
        GetQueueTaskCountsResponse csilTyped => GetQueueTaskCountsResponseToCborValue(csilTyped),
        GetTaskStateCountsRequest csilTyped => GetTaskStateCountsRequestToCborValue(csilTyped),
        GetTaskStateCountsResponse csilTyped => GetTaskStateCountsResponseToCborValue(csilTyped),
        QueueAndStateCounts csilTyped => QueueAndStateCountsToCborValue(csilTyped),
        GetQueueAndStateCountsRequest csilTyped => GetQueueAndStateCountsRequestToCborValue(csilTyped),
        GetQueueAndStateCountsResponse csilTyped => GetQueueAndStateCountsResponseToCborValue(csilTyped),
        GetServerInfoRequest csilTyped => GetServerInfoRequestToCborValue(csilTyped),
        GetServerInfoResponse csilTyped => GetServerInfoResponseToCborValue(csilTyped),
        GuardedTask csilTyped => GuardedTaskToCborValue(csilTyped),
        SubmissionReceipt csilTyped => SubmissionReceiptToCborValue(csilTyped),
        SubmitKeyedTaskRequest csilTyped => SubmitKeyedTaskRequestToCborValue(csilTyped),
        SubmitKeyedTaskResponse csilTyped => SubmitKeyedTaskResponseToCborValue(csilTyped),
        LookupSubmissionRequest csilTyped => LookupSubmissionRequestToCborValue(csilTyped),
        LookupSubmissionResponse csilTyped => LookupSubmissionResponseToCborValue(csilTyped),
        ClaimGuardedTaskRequest csilTyped => ClaimGuardedTaskRequestToCborValue(csilTyped),
        GuardedDelivery csilTyped => GuardedDeliveryToCborValue(csilTyped),
        ClaimGuardedTaskResponse csilTyped => ClaimGuardedTaskResponseToCborValue(csilTyped),
        ClaimGuardedTaskGroupRequest csilTyped => ClaimGuardedTaskGroupRequestToCborValue(csilTyped),
        ClaimGuardedTaskGroupResponse csilTyped => ClaimGuardedTaskGroupResponseToCborValue(csilTyped),
        UpdateGuardedTaskRequest csilTyped => UpdateGuardedTaskRequestToCborValue(csilTyped),
        UpdateGuardedTaskResponse csilTyped => UpdateGuardedTaskResponseToCborValue(csilTyped),
        CompleteGuardedTaskRequest csilTyped => CompleteGuardedTaskRequestToCborValue(csilTyped),
        CompleteGuardedTaskResponse csilTyped => CompleteGuardedTaskResponseToCborValue(csilTyped),
        CancelGuardedTaskRequest csilTyped => CancelGuardedTaskRequestToCborValue(csilTyped),
        CancelGuardedTaskResponse csilTyped => CancelGuardedTaskResponseToCborValue(csilTyped),
        GetGuardedTaskRequest csilTyped => GetGuardedTaskRequestToCborValue(csilTyped),
        GetGuardedTaskResponse csilTyped => GetGuardedTaskResponseToCborValue(csilTyped),
        OperationReceipt csilTyped => OperationReceiptToCborValue(csilTyped),
        LookupOperationRequest csilTyped => LookupOperationRequestToCborValue(csilTyped),
        LookupOperationResponse csilTyped => LookupOperationResponseToCborValue(csilTyped),
        ServiceError csilTyped => ServiceErrorToCborValue(csilTyped),
        _ => throw new System.ArgumentException("csilgen: no CSIL codec for the requested type"),
    };

    static object FromCborValue(System.Type csilType, CborValue value)
    {
        if (csilType == typeof(Task)) return TaskFromCborValue(value);
        if (csilType == typeof(TaskDelivery)) return TaskDeliveryFromCborValue(value);
        if (csilType == typeof(SubmitTaskRequest)) return SubmitTaskRequestFromCborValue(value);
        if (csilType == typeof(SubmitTaskResponse)) return SubmitTaskResponseFromCborValue(value);
        if (csilType == typeof(GetTaskStateByIDRequest)) return GetTaskStateByIDRequestFromCborValue(value);
        if (csilType == typeof(GetTaskStateByIDResponse)) return GetTaskStateByIDResponseFromCborValue(value);
        if (csilType == typeof(GetNextTaskRequest)) return GetNextTaskRequestFromCborValue(value);
        if (csilType == typeof(GetNextTaskResponse)) return GetNextTaskResponseFromCborValue(value);
        if (csilType == typeof(GetNextTaskGroupRequest)) return GetNextTaskGroupRequestFromCborValue(value);
        if (csilType == typeof(GetNextTaskGroupResponse)) return GetNextTaskGroupResponseFromCborValue(value);
        if (csilType == typeof(CompleteTaskRequest)) return CompleteTaskRequestFromCborValue(value);
        if (csilType == typeof(CompleteTaskResponse)) return CompleteTaskResponseFromCborValue(value);
        if (csilType == typeof(UpdateTaskRequest)) return UpdateTaskRequestFromCborValue(value);
        if (csilType == typeof(UpdateTaskResponse)) return UpdateTaskResponseFromCborValue(value);
        if (csilType == typeof(CancelTaskRequest)) return CancelTaskRequestFromCborValue(value);
        if (csilType == typeof(CancelTaskResponse)) return CancelTaskResponseFromCborValue(value);
        if (csilType == typeof(CleanUpTimedOutRequest)) return CleanUpTimedOutRequestFromCborValue(value);
        if (csilType == typeof(CleanUpTimedOutResponse)) return CleanUpTimedOutResponseFromCborValue(value);
        if (csilType == typeof(GetQueuesRequest)) return GetQueuesRequestFromCborValue(value);
        if (csilType == typeof(GetQueuesResponse)) return GetQueuesResponseFromCborValue(value);
        if (csilType == typeof(GetQueueTaskCountsRequest)) return GetQueueTaskCountsRequestFromCborValue(value);
        if (csilType == typeof(GetQueueTaskCountsResponse)) return GetQueueTaskCountsResponseFromCborValue(value);
        if (csilType == typeof(GetTaskStateCountsRequest)) return GetTaskStateCountsRequestFromCborValue(value);
        if (csilType == typeof(GetTaskStateCountsResponse)) return GetTaskStateCountsResponseFromCborValue(value);
        if (csilType == typeof(QueueAndStateCounts)) return QueueAndStateCountsFromCborValue(value);
        if (csilType == typeof(GetQueueAndStateCountsRequest)) return GetQueueAndStateCountsRequestFromCborValue(value);
        if (csilType == typeof(GetQueueAndStateCountsResponse)) return GetQueueAndStateCountsResponseFromCborValue(value);
        if (csilType == typeof(GetServerInfoRequest)) return GetServerInfoRequestFromCborValue(value);
        if (csilType == typeof(GetServerInfoResponse)) return GetServerInfoResponseFromCborValue(value);
        if (csilType == typeof(GuardedTask)) return GuardedTaskFromCborValue(value);
        if (csilType == typeof(SubmissionReceipt)) return SubmissionReceiptFromCborValue(value);
        if (csilType == typeof(SubmitKeyedTaskRequest)) return SubmitKeyedTaskRequestFromCborValue(value);
        if (csilType == typeof(SubmitKeyedTaskResponse)) return SubmitKeyedTaskResponseFromCborValue(value);
        if (csilType == typeof(LookupSubmissionRequest)) return LookupSubmissionRequestFromCborValue(value);
        if (csilType == typeof(LookupSubmissionResponse)) return LookupSubmissionResponseFromCborValue(value);
        if (csilType == typeof(ClaimGuardedTaskRequest)) return ClaimGuardedTaskRequestFromCborValue(value);
        if (csilType == typeof(GuardedDelivery)) return GuardedDeliveryFromCborValue(value);
        if (csilType == typeof(ClaimGuardedTaskResponse)) return ClaimGuardedTaskResponseFromCborValue(value);
        if (csilType == typeof(ClaimGuardedTaskGroupRequest)) return ClaimGuardedTaskGroupRequestFromCborValue(value);
        if (csilType == typeof(ClaimGuardedTaskGroupResponse)) return ClaimGuardedTaskGroupResponseFromCborValue(value);
        if (csilType == typeof(UpdateGuardedTaskRequest)) return UpdateGuardedTaskRequestFromCborValue(value);
        if (csilType == typeof(UpdateGuardedTaskResponse)) return UpdateGuardedTaskResponseFromCborValue(value);
        if (csilType == typeof(CompleteGuardedTaskRequest)) return CompleteGuardedTaskRequestFromCborValue(value);
        if (csilType == typeof(CompleteGuardedTaskResponse)) return CompleteGuardedTaskResponseFromCborValue(value);
        if (csilType == typeof(CancelGuardedTaskRequest)) return CancelGuardedTaskRequestFromCborValue(value);
        if (csilType == typeof(CancelGuardedTaskResponse)) return CancelGuardedTaskResponseFromCborValue(value);
        if (csilType == typeof(GetGuardedTaskRequest)) return GetGuardedTaskRequestFromCborValue(value);
        if (csilType == typeof(GetGuardedTaskResponse)) return GetGuardedTaskResponseFromCborValue(value);
        if (csilType == typeof(OperationReceipt)) return OperationReceiptFromCborValue(value);
        if (csilType == typeof(LookupOperationRequest)) return LookupOperationRequestFromCborValue(value);
        if (csilType == typeof(LookupOperationResponse)) return LookupOperationResponseFromCborValue(value);
        if (csilType == typeof(ServiceError)) return ServiceErrorFromCborValue(value);
        throw new System.ArgumentException("csilgen: no CSIL codec for the requested type");
    }

    /// <summary>The canonical CBOR value tree for a Task.</summary>
    public static CborValue TaskToCborValue(Task value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("timeout"), new CborValue.Int(value.Timeout)));
        csilEntries.Add((new CborValue.Text("priority"), new CborValue.Int(value.Priority)));
        csilEntries.Add((new CborValue.Text("submit_time"), new CborValue.Int(value.SubmitTime)));
        csilEntries.Add((new CborValue.Text("update_time"), new CborValue.Int(value.UpdateTime)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("auto_target_state"), new CborValue.Text(value.AutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a Task from a decoded CBOR value tree.</summary>
    public static Task TaskFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField3 = Cbor.AsText(Cbor.Require(value, "auto_target_state"));
        var csilField4 = Cbor.AsI64(Cbor.Require(value, "submit_time"));
        var csilField5 = Cbor.AsI64(Cbor.Require(value, "update_time"));
        var csilField6 = Cbor.AsI64(Cbor.Require(value, "timeout"));
        var csilField7 = Cbor.AsI64(Cbor.Require(value, "priority"));
        return new Task
        {
            Uuid = csilField0,
            Queue = csilField1,
            CurrentState = csilField2,
            AutoTargetState = csilField3,
            SubmitTime = csilField4,
            UpdateTime = csilField5,
            Timeout = csilField6,
            Priority = csilField7,
        };
    }

    /// <summary>The canonical CBOR value tree for a TaskDelivery.</summary>
    public static CborValue TaskDeliveryToCborValue(TaskDelivery value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("task"), TaskToCborValue(value.Task)));
        csilEntries.Add((new CborValue.Text("payload"), new CborValue.Bytes(value.Payload)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a TaskDelivery from a decoded CBOR value tree.</summary>
    public static TaskDelivery TaskDeliveryFromCborValue(CborValue value)
    {
        var csilField0 = TaskFromCborValue(Cbor.Require(value, "task"));
        var csilField1 = Cbor.AsBytes(Cbor.Require(value, "payload"));
        return new TaskDelivery
        {
            Task = csilField0,
            Payload = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a SubmitTaskRequest.</summary>
    public static CborValue SubmitTaskRequestToCborValue(SubmitTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("payload"), new CborValue.Bytes(value.Payload)));
        csilEntries.Add((new CborValue.Text("timeout"), new CborValue.Int(value.Timeout)));
        csilEntries.Add((new CborValue.Text("priority"), new CborValue.Int(value.Priority)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("auto_target_state"), new CborValue.Text(value.AutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a SubmitTaskRequest from a decoded CBOR value tree.</summary>
    public static SubmitTaskRequest SubmitTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "auto_target_state"));
        var csilField3 = Cbor.AsI64(Cbor.Require(value, "timeout"));
        var csilField4 = Cbor.AsBytes(Cbor.Require(value, "payload"));
        var csilField5 = Cbor.AsI64(Cbor.Require(value, "priority"));
        return new SubmitTaskRequest
        {
            Queue = csilField0,
            CurrentState = csilField1,
            AutoTargetState = csilField2,
            Timeout = csilField3,
            Payload = csilField4,
            Priority = csilField5,
        };
    }

    /// <summary>The canonical CBOR value tree for a SubmitTaskResponse.</summary>
    public static CborValue SubmitTaskResponseToCborValue(SubmitTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), TaskToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a SubmitTaskResponse from a decoded CBOR value tree.</summary>
    public static SubmitTaskResponse SubmitTaskResponseFromCborValue(CborValue value)
    {
        Task? csilField0 = Cbor.MapGet(value, "task") is { } csilRaw0 ? TaskFromCborValue(csilRaw0) : null;
        return new SubmitTaskResponse
        {
            Task = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetTaskStateByIDRequest.</summary>
    public static CborValue GetTaskStateByIDRequestToCborValue(GetTaskStateByIDRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetTaskStateByIDRequest from a decoded CBOR value tree.</summary>
    public static GetTaskStateByIDRequest GetTaskStateByIDRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        return new GetTaskStateByIDRequest
        {
            Uuid = csilField0,
            Queue = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetTaskStateByIDResponse.</summary>
    public static CborValue GetTaskStateByIDResponseToCborValue(GetTaskStateByIDResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), TaskToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetTaskStateByIDResponse from a decoded CBOR value tree.</summary>
    public static GetTaskStateByIDResponse GetTaskStateByIDResponseFromCborValue(CborValue value)
    {
        Task? csilField0 = Cbor.MapGet(value, "task") is { } csilRaw0 ? TaskFromCborValue(csilRaw0) : null;
        return new GetTaskStateByIDResponse
        {
            Task = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetNextTaskRequest.</summary>
    public static CborValue GetNextTaskRequestToCborValue(GetNextTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("override_timeout"), new CborValue.Int(value.OverrideTimeout)));
        csilEntries.Add((new CborValue.Text("override_current_state"), new CborValue.Text(value.OverrideCurrentState)));
        csilEntries.Add((new CborValue.Text("override_auto_target_state"), new CborValue.Text(value.OverrideAutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetNextTaskRequest from a decoded CBOR value tree.</summary>
    public static GetNextTaskRequest GetNextTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField2 = Cbor.AsI64(Cbor.Require(value, "override_timeout"));
        var csilField3 = Cbor.AsText(Cbor.Require(value, "override_current_state"));
        var csilField4 = Cbor.AsText(Cbor.Require(value, "override_auto_target_state"));
        return new GetNextTaskRequest
        {
            Queue = csilField0,
            CurrentState = csilField1,
            OverrideTimeout = csilField2,
            OverrideCurrentState = csilField3,
            OverrideAutoTargetState = csilField4,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetNextTaskResponse.</summary>
    public static CborValue GetNextTaskResponseToCborValue(GetNextTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Delivery is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("delivery"), TaskDeliveryToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetNextTaskResponse from a decoded CBOR value tree.</summary>
    public static GetNextTaskResponse GetNextTaskResponseFromCborValue(CborValue value)
    {
        TaskDelivery? csilField0 = Cbor.MapGet(value, "delivery") is { } csilRaw0 ? TaskDeliveryFromCborValue(csilRaw0) : null;
        return new GetNextTaskResponse
        {
            Delivery = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetNextTaskGroupRequest.</summary>
    public static CborValue GetNextTaskGroupRequestToCborValue(GetNextTaskGroupRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queues"), new CborValue.Array(value.Queues.Select(csilElem => (CborValue)new CborValue.Text(csilElem)).ToList())));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("override_timeout"), new CborValue.Int(value.OverrideTimeout)));
        csilEntries.Add((new CborValue.Text("override_current_state"), new CborValue.Text(value.OverrideCurrentState)));
        csilEntries.Add((new CborValue.Text("override_auto_target_state"), new CborValue.Text(value.OverrideAutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetNextTaskGroupRequest from a decoded CBOR value tree.</summary>
    public static GetNextTaskGroupRequest GetNextTaskGroupRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsArray(Cbor.Require(value, "queues")).Select(csilElem => Cbor.AsText(csilElem)).ToList();
        var csilField1 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField2 = Cbor.AsI64(Cbor.Require(value, "override_timeout"));
        var csilField3 = Cbor.AsText(Cbor.Require(value, "override_current_state"));
        var csilField4 = Cbor.AsText(Cbor.Require(value, "override_auto_target_state"));
        return new GetNextTaskGroupRequest
        {
            Queues = csilField0,
            CurrentState = csilField1,
            OverrideTimeout = csilField2,
            OverrideCurrentState = csilField3,
            OverrideAutoTargetState = csilField4,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetNextTaskGroupResponse.</summary>
    public static CborValue GetNextTaskGroupResponseToCborValue(GetNextTaskGroupResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Delivery is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("delivery"), TaskDeliveryToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetNextTaskGroupResponse from a decoded CBOR value tree.</summary>
    public static GetNextTaskGroupResponse GetNextTaskGroupResponseFromCborValue(CborValue value)
    {
        TaskDelivery? csilField0 = Cbor.MapGet(value, "delivery") is { } csilRaw0 ? TaskDeliveryFromCborValue(csilRaw0) : null;
        return new GetNextTaskGroupResponse
        {
            Delivery = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a CompleteTaskRequest.</summary>
    public static CborValue CompleteTaskRequestToCborValue(CompleteTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CompleteTaskRequest from a decoded CBOR value tree.</summary>
    public static CompleteTaskRequest CompleteTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "current_state"));
        return new CompleteTaskRequest
        {
            Uuid = csilField0,
            Queue = csilField1,
            CurrentState = csilField2,
        };
    }

    /// <summary>The canonical CBOR value tree for a CompleteTaskResponse.</summary>
    public static CborValue CompleteTaskResponseToCborValue(CompleteTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), TaskToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CompleteTaskResponse from a decoded CBOR value tree.</summary>
    public static CompleteTaskResponse CompleteTaskResponseFromCborValue(CborValue value)
    {
        Task? csilField0 = Cbor.MapGet(value, "task") is { } csilRaw0 ? TaskFromCborValue(csilRaw0) : null;
        return new CompleteTaskResponse
        {
            Task = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a UpdateTaskRequest.</summary>
    public static CborValue UpdateTaskRequestToCborValue(UpdateTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        if (value.Payload is { } csilV2)
        {
            csilEntries.Add((new CborValue.Text("payload"), new CborValue.Bytes(csilV2)));
        }
        csilEntries.Add((new CborValue.Text("timeout"), new CborValue.Int(value.Timeout)));
        if (value.Priority is { } csilV4)
        {
            csilEntries.Add((new CborValue.Text("priority"), new CborValue.Int(csilV4)));
        }
        csilEntries.Add((new CborValue.Text("new_state"), new CborValue.Text(value.NewState)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("auto_target_state"), new CborValue.Text(value.AutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a UpdateTaskRequest from a decoded CBOR value tree.</summary>
    public static UpdateTaskRequest UpdateTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField3 = Cbor.AsText(Cbor.Require(value, "auto_target_state"));
        var csilField4 = Cbor.AsI64(Cbor.Require(value, "timeout"));
        var csilField5 = Cbor.AsText(Cbor.Require(value, "new_state"));
        byte[]? csilField6 = Cbor.MapGet(value, "payload") is { } csilRaw6 ? Cbor.AsBytes(csilRaw6) : null;
        long? csilField7 = Cbor.MapGet(value, "priority") is { } csilRaw7 ? Cbor.AsI64(csilRaw7) : null;
        return new UpdateTaskRequest
        {
            Uuid = csilField0,
            Queue = csilField1,
            CurrentState = csilField2,
            AutoTargetState = csilField3,
            Timeout = csilField4,
            NewState = csilField5,
            Payload = csilField6,
            Priority = csilField7,
        };
    }

    /// <summary>The canonical CBOR value tree for a UpdateTaskResponse.</summary>
    public static CborValue UpdateTaskResponseToCborValue(UpdateTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), TaskToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a UpdateTaskResponse from a decoded CBOR value tree.</summary>
    public static UpdateTaskResponse UpdateTaskResponseFromCborValue(CborValue value)
    {
        Task? csilField0 = Cbor.MapGet(value, "task") is { } csilRaw0 ? TaskFromCborValue(csilRaw0) : null;
        return new UpdateTaskResponse
        {
            Task = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a CancelTaskRequest.</summary>
    public static CborValue CancelTaskRequestToCborValue(CancelTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CancelTaskRequest from a decoded CBOR value tree.</summary>
    public static CancelTaskRequest CancelTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "current_state"));
        return new CancelTaskRequest
        {
            Uuid = csilField0,
            Queue = csilField1,
            CurrentState = csilField2,
        };
    }

    /// <summary>The canonical CBOR value tree for a CancelTaskResponse.</summary>
    public static CborValue CancelTaskResponseToCborValue(CancelTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), TaskToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CancelTaskResponse from a decoded CBOR value tree.</summary>
    public static CancelTaskResponse CancelTaskResponseFromCborValue(CborValue value)
    {
        Task? csilField0 = Cbor.MapGet(value, "task") is { } csilRaw0 ? TaskFromCborValue(csilRaw0) : null;
        return new CancelTaskResponse
        {
            Task = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a CleanUpTimedOutRequest.</summary>
    public static CborValue CleanUpTimedOutRequestToCborValue(CleanUpTimedOutRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("at_time"), new CborValue.Int(value.AtTime)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CleanUpTimedOutRequest from a decoded CBOR value tree.</summary>
    public static CleanUpTimedOutRequest CleanUpTimedOutRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsI64(Cbor.Require(value, "at_time"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        return new CleanUpTimedOutRequest
        {
            AtTime = csilField0,
            Queue = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a CleanUpTimedOutResponse.</summary>
    public static CborValue CleanUpTimedOutResponseToCborValue(CleanUpTimedOutResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("timed_out"), new CborValue.Int(value.TimedOut)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CleanUpTimedOutResponse from a decoded CBOR value tree.</summary>
    public static CleanUpTimedOutResponse CleanUpTimedOutResponseFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsI64(Cbor.Require(value, "timed_out"));
        return new CleanUpTimedOutResponse
        {
            TimedOut = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetQueuesRequest.</summary>
    public static CborValue GetQueuesRequestToCborValue(GetQueuesRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetQueuesRequest from a decoded CBOR value tree.</summary>
    public static GetQueuesRequest GetQueuesRequestFromCborValue(CborValue value)
    {
        return new GetQueuesRequest
        {
        };
    }

    /// <summary>The canonical CBOR value tree for a GetQueuesResponse.</summary>
    public static CborValue GetQueuesResponseToCborValue(GetQueuesResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queues"), new CborValue.Array(value.Queues.Select(csilElem => (CborValue)new CborValue.Text(csilElem)).ToList())));
        csilEntries.Add((new CborValue.Text("total_task_count"), new CborValue.Int(value.TotalTaskCount)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetQueuesResponse from a decoded CBOR value tree.</summary>
    public static GetQueuesResponse GetQueuesResponseFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsArray(Cbor.Require(value, "queues")).Select(csilElem => Cbor.AsText(csilElem)).ToList();
        var csilField1 = Cbor.AsI64(Cbor.Require(value, "total_task_count"));
        return new GetQueuesResponse
        {
            Queues = csilField0,
            TotalTaskCount = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetQueueTaskCountsRequest.</summary>
    public static CborValue GetQueueTaskCountsRequestToCborValue(GetQueueTaskCountsRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetQueueTaskCountsRequest from a decoded CBOR value tree.</summary>
    public static GetQueueTaskCountsRequest GetQueueTaskCountsRequestFromCborValue(CborValue value)
    {
        return new GetQueueTaskCountsRequest
        {
        };
    }

    /// <summary>The canonical CBOR value tree for a GetQueueTaskCountsResponse.</summary>
    public static CborValue GetQueueTaskCountsResponseToCborValue(GetQueueTaskCountsResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue_counts"), new CborValue.Map(value.QueueCounts.Select(csilKv => ((CborValue)new CborValue.Text(csilKv.Key), (CborValue)new CborValue.Int(csilKv.Value))).ToList())));
        csilEntries.Add((new CborValue.Text("total_task_count"), new CborValue.Int(value.TotalTaskCount)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetQueueTaskCountsResponse from a decoded CBOR value tree.</summary>
    public static GetQueueTaskCountsResponse GetQueueTaskCountsResponseFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsMap(Cbor.Require(value, "queue_counts")).ToDictionary(csilKv => Cbor.AsText(csilKv.Key), csilKv => Cbor.AsI64(csilKv.Value));
        var csilField1 = Cbor.AsI64(Cbor.Require(value, "total_task_count"));
        return new GetQueueTaskCountsResponse
        {
            QueueCounts = csilField0,
            TotalTaskCount = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetTaskStateCountsRequest.</summary>
    public static CborValue GetTaskStateCountsRequestToCborValue(GetTaskStateCountsRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetTaskStateCountsRequest from a decoded CBOR value tree.</summary>
    public static GetTaskStateCountsRequest GetTaskStateCountsRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "queue"));
        return new GetTaskStateCountsRequest
        {
            Queue = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetTaskStateCountsResponse.</summary>
    public static CborValue GetTaskStateCountsResponseToCborValue(GetTaskStateCountsResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("count"), new CborValue.Int(value.Count)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("state_counts"), new CborValue.Map(value.StateCounts.Select(csilKv => ((CborValue)new CborValue.Text(csilKv.Key), (CborValue)new CborValue.Int(csilKv.Value))).ToList())));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetTaskStateCountsResponse from a decoded CBOR value tree.</summary>
    public static GetTaskStateCountsResponse GetTaskStateCountsResponseFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField1 = Cbor.AsI64(Cbor.Require(value, "count"));
        var csilField2 = Cbor.AsMap(Cbor.Require(value, "state_counts")).ToDictionary(csilKv => Cbor.AsText(csilKv.Key), csilKv => Cbor.AsI64(csilKv.Value));
        return new GetTaskStateCountsResponse
        {
            Queue = csilField0,
            Count = csilField1,
            StateCounts = csilField2,
        };
    }

    /// <summary>The canonical CBOR value tree for a QueueAndStateCounts.</summary>
    public static CborValue QueueAndStateCountsToCborValue(QueueAndStateCounts value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("count"), new CborValue.Int(value.Count)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("state_counts"), new CborValue.Map(value.StateCounts.Select(csilKv => ((CborValue)new CborValue.Text(csilKv.Key), (CborValue)new CborValue.Int(csilKv.Value))).ToList())));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a QueueAndStateCounts from a decoded CBOR value tree.</summary>
    public static QueueAndStateCounts QueueAndStateCountsFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField1 = Cbor.AsI64(Cbor.Require(value, "count"));
        var csilField2 = Cbor.AsMap(Cbor.Require(value, "state_counts")).ToDictionary(csilKv => Cbor.AsText(csilKv.Key), csilKv => Cbor.AsI64(csilKv.Value));
        return new QueueAndStateCounts
        {
            Queue = csilField0,
            Count = csilField1,
            StateCounts = csilField2,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetQueueAndStateCountsRequest.</summary>
    public static CborValue GetQueueAndStateCountsRequestToCborValue(GetQueueAndStateCountsRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetQueueAndStateCountsRequest from a decoded CBOR value tree.</summary>
    public static GetQueueAndStateCountsRequest GetQueueAndStateCountsRequestFromCborValue(CborValue value)
    {
        return new GetQueueAndStateCountsRequest
        {
        };
    }

    /// <summary>The canonical CBOR value tree for a GetQueueAndStateCountsResponse.</summary>
    public static CborValue GetQueueAndStateCountsResponseToCborValue(GetQueueAndStateCountsResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue_and_state_counts"), new CborValue.Map(value.QueueAndStateCounts.Select(csilKv => ((CborValue)new CborValue.Text(csilKv.Key), (CborValue)QueueAndStateCountsToCborValue(csilKv.Value))).ToList())));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetQueueAndStateCountsResponse from a decoded CBOR value tree.</summary>
    public static GetQueueAndStateCountsResponse GetQueueAndStateCountsResponseFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsMap(Cbor.Require(value, "queue_and_state_counts")).ToDictionary(csilKv => Cbor.AsText(csilKv.Key), csilKv => QueueAndStateCountsFromCborValue(csilKv.Value));
        return new GetQueueAndStateCountsResponse
        {
            QueueAndStateCounts = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetServerInfoRequest.</summary>
    public static CborValue GetServerInfoRequestToCborValue(GetServerInfoRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetServerInfoRequest from a decoded CBOR value tree.</summary>
    public static GetServerInfoRequest GetServerInfoRequestFromCborValue(CborValue value)
    {
        return new GetServerInfoRequest
        {
        };
    }

    /// <summary>The canonical CBOR value tree for a GetServerInfoResponse.</summary>
    public static CborValue GetServerInfoResponseToCborValue(GetServerInfoResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("features"), new CborValue.Array(value.Features.Select(csilElem => (CborValue)new CborValue.Text(csilElem)).ToList())));
        csilEntries.Add((new CborValue.Text("server_version"), new CborValue.Text(value.ServerVersion)));
        csilEntries.Add((new CborValue.Text("task_guard_policy"), new CborValue.Text(value.TaskGuardPolicy)));
        csilEntries.Add((new CborValue.Text("submission_key_policy"), new CborValue.Text(value.SubmissionKeyPolicy)));
        csilEntries.Add((new CborValue.Text("receipt_retention_seconds"), new CborValue.Int(value.ReceiptRetentionSeconds)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetServerInfoResponse from a decoded CBOR value tree.</summary>
    public static GetServerInfoResponse GetServerInfoResponseFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "server_version"));
        var csilField1 = Cbor.AsArray(Cbor.Require(value, "features")).Select(csilElem => Cbor.AsText(csilElem)).ToList();
        var csilField2 = Cbor.AsText(Cbor.Require(value, "submission_key_policy"));
        var csilField3 = Cbor.AsText(Cbor.Require(value, "task_guard_policy"));
        var csilField4 = Cbor.AsI64(Cbor.Require(value, "receipt_retention_seconds"));
        return new GetServerInfoResponse
        {
            ServerVersion = csilField0,
            Features = csilField1,
            SubmissionKeyPolicy = csilField2,
            TaskGuardPolicy = csilField3,
            ReceiptRetentionSeconds = csilField4,
        };
    }

    /// <summary>The canonical CBOR value tree for a GuardedTask.</summary>
    public static CborValue GuardedTaskToCborValue(GuardedTask value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("task"), TaskToCborValue(value.Task)));
        csilEntries.Add((new CborValue.Text("guarded"), new CborValue.Bool(value.Guarded)));
        csilEntries.Add((new CborValue.Text("revision"), new CborValue.Int(value.Revision)));
        csilEntries.Add((new CborValue.Text("terminal"), new CborValue.Bool(value.Terminal)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GuardedTask from a decoded CBOR value tree.</summary>
    public static GuardedTask GuardedTaskFromCborValue(CborValue value)
    {
        var csilField0 = TaskFromCborValue(Cbor.Require(value, "task"));
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "guarded"));
        var csilField2 = Cbor.AsI64(Cbor.Require(value, "revision"));
        var csilField3 = Cbor.AsBool(Cbor.Require(value, "terminal"));
        return new GuardedTask
        {
            Task = csilField0,
            Guarded = csilField1,
            Revision = csilField2,
            Terminal = csilField3,
        };
    }

    /// <summary>The canonical CBOR value tree for a SubmissionReceipt.</summary>
    public static CborValue SubmissionReceiptToCborValue(SubmissionReceipt value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("guarded"), new CborValue.Bool(value.Guarded)));
        csilEntries.Add((new CborValue.Text("task_uuid"), new CborValue.Text(value.TaskUuid)));
        csilEntries.Add((new CborValue.Text("expires_at"), new CborValue.Int(value.ExpiresAt)));
        csilEntries.Add((new CborValue.Text("accepted_at"), new CborValue.Int(value.AcceptedAt)));
        csilEntries.Add((new CborValue.Text("submission_key"), new CborValue.Text(value.SubmissionKey)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a SubmissionReceipt from a decoded CBOR value tree.</summary>
    public static SubmissionReceipt SubmissionReceiptFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "submission_key"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "task_uuid"));
        var csilField3 = Cbor.AsI64(Cbor.Require(value, "accepted_at"));
        var csilField4 = Cbor.AsI64(Cbor.Require(value, "expires_at"));
        var csilField5 = Cbor.AsBool(Cbor.Require(value, "guarded"));
        return new SubmissionReceipt
        {
            Queue = csilField0,
            SubmissionKey = csilField1,
            TaskUuid = csilField2,
            AcceptedAt = csilField3,
            ExpiresAt = csilField4,
            Guarded = csilField5,
        };
    }

    /// <summary>The canonical CBOR value tree for a SubmitKeyedTaskRequest.</summary>
    public static CborValue SubmitKeyedTaskRequestToCborValue(SubmitKeyedTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("guarded"), new CborValue.Bool(value.Guarded)));
        csilEntries.Add((new CborValue.Text("payload"), new CborValue.Bytes(value.Payload)));
        csilEntries.Add((new CborValue.Text("timeout"), new CborValue.Int(value.Timeout)));
        csilEntries.Add((new CborValue.Text("priority"), new CborValue.Int(value.Priority)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("submission_key"), new CborValue.Text(value.SubmissionKey)));
        csilEntries.Add((new CborValue.Text("auto_target_state"), new CborValue.Text(value.AutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a SubmitKeyedTaskRequest from a decoded CBOR value tree.</summary>
    public static SubmitKeyedTaskRequest SubmitKeyedTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "submission_key"));
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "guarded"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField3 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField4 = Cbor.AsText(Cbor.Require(value, "auto_target_state"));
        var csilField5 = Cbor.AsI64(Cbor.Require(value, "timeout"));
        var csilField6 = Cbor.AsBytes(Cbor.Require(value, "payload"));
        var csilField7 = Cbor.AsI64(Cbor.Require(value, "priority"));
        return new SubmitKeyedTaskRequest
        {
            SubmissionKey = csilField0,
            Guarded = csilField1,
            Queue = csilField2,
            CurrentState = csilField3,
            AutoTargetState = csilField4,
            Timeout = csilField5,
            Payload = csilField6,
            Priority = csilField7,
        };
    }

    /// <summary>The canonical CBOR value tree for a SubmitKeyedTaskResponse.</summary>
    public static CborValue SubmitKeyedTaskResponseToCborValue(SubmitKeyedTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), GuardedTaskToCborValue(csilV0)));
        }
        csilEntries.Add((new CborValue.Text("receipt"), SubmissionReceiptToCborValue(value.Receipt)));
        csilEntries.Add((new CborValue.Text("replayed"), new CborValue.Bool(value.Replayed)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a SubmitKeyedTaskResponse from a decoded CBOR value tree.</summary>
    public static SubmitKeyedTaskResponse SubmitKeyedTaskResponseFromCborValue(CborValue value)
    {
        var csilField0 = SubmissionReceiptFromCborValue(Cbor.Require(value, "receipt"));
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "replayed"));
        GuardedTask? csilField2 = Cbor.MapGet(value, "task") is { } csilRaw2 ? GuardedTaskFromCborValue(csilRaw2) : null;
        return new SubmitKeyedTaskResponse
        {
            Receipt = csilField0,
            Replayed = csilField1,
            Task = csilField2,
        };
    }

    /// <summary>The canonical CBOR value tree for a LookupSubmissionRequest.</summary>
    public static CborValue LookupSubmissionRequestToCborValue(LookupSubmissionRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("submission_key"), new CborValue.Text(value.SubmissionKey)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a LookupSubmissionRequest from a decoded CBOR value tree.</summary>
    public static LookupSubmissionRequest LookupSubmissionRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "submission_key"));
        return new LookupSubmissionRequest
        {
            Queue = csilField0,
            SubmissionKey = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a LookupSubmissionResponse.</summary>
    public static CborValue LookupSubmissionResponseToCborValue(LookupSubmissionResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), GuardedTaskToCborValue(csilV0)));
        }
        if (value.Receipt is { } csilV1)
        {
            csilEntries.Add((new CborValue.Text("receipt"), SubmissionReceiptToCborValue(csilV1)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a LookupSubmissionResponse from a decoded CBOR value tree.</summary>
    public static LookupSubmissionResponse LookupSubmissionResponseFromCborValue(CborValue value)
    {
        SubmissionReceipt? csilField0 = Cbor.MapGet(value, "receipt") is { } csilRaw0 ? SubmissionReceiptFromCborValue(csilRaw0) : null;
        GuardedTask? csilField1 = Cbor.MapGet(value, "task") is { } csilRaw1 ? GuardedTaskFromCborValue(csilRaw1) : null;
        return new LookupSubmissionResponse
        {
            Receipt = csilField0,
            Task = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a ClaimGuardedTaskRequest.</summary>
    public static CborValue ClaimGuardedTaskRequestToCborValue(ClaimGuardedTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("operation_id"), new CborValue.Text(value.OperationId)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("override_timeout"), new CborValue.Int(value.OverrideTimeout)));
        csilEntries.Add((new CborValue.Text("override_current_state"), new CborValue.Text(value.OverrideCurrentState)));
        csilEntries.Add((new CborValue.Text("override_auto_target_state"), new CborValue.Text(value.OverrideAutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a ClaimGuardedTaskRequest from a decoded CBOR value tree.</summary>
    public static ClaimGuardedTaskRequest ClaimGuardedTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "operation_id"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField3 = Cbor.AsI64(Cbor.Require(value, "override_timeout"));
        var csilField4 = Cbor.AsText(Cbor.Require(value, "override_current_state"));
        var csilField5 = Cbor.AsText(Cbor.Require(value, "override_auto_target_state"));
        return new ClaimGuardedTaskRequest
        {
            OperationId = csilField0,
            Queue = csilField1,
            CurrentState = csilField2,
            OverrideTimeout = csilField3,
            OverrideCurrentState = csilField4,
            OverrideAutoTargetState = csilField5,
        };
    }

    /// <summary>The canonical CBOR value tree for a GuardedDelivery.</summary>
    public static CborValue GuardedDeliveryToCborValue(GuardedDelivery value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("task"), GuardedTaskToCborValue(value.Task)));
        csilEntries.Add((new CborValue.Text("payload"), new CborValue.Bytes(value.Payload)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GuardedDelivery from a decoded CBOR value tree.</summary>
    public static GuardedDelivery GuardedDeliveryFromCborValue(CborValue value)
    {
        var csilField0 = GuardedTaskFromCborValue(Cbor.Require(value, "task"));
        var csilField1 = Cbor.AsBytes(Cbor.Require(value, "payload"));
        return new GuardedDelivery
        {
            Task = csilField0,
            Payload = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a ClaimGuardedTaskResponse.</summary>
    public static CborValue ClaimGuardedTaskResponseToCborValue(ClaimGuardedTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Delivery is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("delivery"), GuardedDeliveryToCborValue(csilV0)));
        }
        csilEntries.Add((new CborValue.Text("replayed"), new CborValue.Bool(value.Replayed)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a ClaimGuardedTaskResponse from a decoded CBOR value tree.</summary>
    public static ClaimGuardedTaskResponse ClaimGuardedTaskResponseFromCborValue(CborValue value)
    {
        GuardedDelivery? csilField0 = Cbor.MapGet(value, "delivery") is { } csilRaw0 ? GuardedDeliveryFromCborValue(csilRaw0) : null;
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "replayed"));
        return new ClaimGuardedTaskResponse
        {
            Delivery = csilField0,
            Replayed = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a ClaimGuardedTaskGroupRequest.</summary>
    public static CborValue ClaimGuardedTaskGroupRequestToCborValue(ClaimGuardedTaskGroupRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("queues"), new CborValue.Array(value.Queues.Select(csilElem => (CborValue)new CborValue.Text(csilElem)).ToList())));
        csilEntries.Add((new CborValue.Text("operation_id"), new CborValue.Text(value.OperationId)));
        csilEntries.Add((new CborValue.Text("current_state"), new CborValue.Text(value.CurrentState)));
        csilEntries.Add((new CborValue.Text("override_timeout"), new CborValue.Int(value.OverrideTimeout)));
        csilEntries.Add((new CborValue.Text("override_current_state"), new CborValue.Text(value.OverrideCurrentState)));
        csilEntries.Add((new CborValue.Text("override_auto_target_state"), new CborValue.Text(value.OverrideAutoTargetState)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a ClaimGuardedTaskGroupRequest from a decoded CBOR value tree.</summary>
    public static ClaimGuardedTaskGroupRequest ClaimGuardedTaskGroupRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "operation_id"));
        var csilField1 = Cbor.AsArray(Cbor.Require(value, "queues")).Select(csilElem => Cbor.AsText(csilElem)).ToList();
        var csilField2 = Cbor.AsText(Cbor.Require(value, "current_state"));
        var csilField3 = Cbor.AsI64(Cbor.Require(value, "override_timeout"));
        var csilField4 = Cbor.AsText(Cbor.Require(value, "override_current_state"));
        var csilField5 = Cbor.AsText(Cbor.Require(value, "override_auto_target_state"));
        return new ClaimGuardedTaskGroupRequest
        {
            OperationId = csilField0,
            Queues = csilField1,
            CurrentState = csilField2,
            OverrideTimeout = csilField3,
            OverrideCurrentState = csilField4,
            OverrideAutoTargetState = csilField5,
        };
    }

    /// <summary>The canonical CBOR value tree for a ClaimGuardedTaskGroupResponse.</summary>
    public static CborValue ClaimGuardedTaskGroupResponseToCborValue(ClaimGuardedTaskGroupResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Delivery is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("delivery"), GuardedDeliveryToCborValue(csilV0)));
        }
        csilEntries.Add((new CborValue.Text("replayed"), new CborValue.Bool(value.Replayed)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a ClaimGuardedTaskGroupResponse from a decoded CBOR value tree.</summary>
    public static ClaimGuardedTaskGroupResponse ClaimGuardedTaskGroupResponseFromCborValue(CborValue value)
    {
        GuardedDelivery? csilField0 = Cbor.MapGet(value, "delivery") is { } csilRaw0 ? GuardedDeliveryFromCborValue(csilRaw0) : null;
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "replayed"));
        return new ClaimGuardedTaskGroupResponse
        {
            Delivery = csilField0,
            Replayed = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a UpdateGuardedTaskRequest.</summary>
    public static CborValue UpdateGuardedTaskRequestToCborValue(UpdateGuardedTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        if (value.Payload is { } csilV2)
        {
            csilEntries.Add((new CborValue.Text("payload"), new CborValue.Bytes(csilV2)));
        }
        csilEntries.Add((new CborValue.Text("timeout"), new CborValue.Int(value.Timeout)));
        if (value.Priority is { } csilV4)
        {
            csilEntries.Add((new CborValue.Text("priority"), new CborValue.Int(csilV4)));
        }
        csilEntries.Add((new CborValue.Text("new_state"), new CborValue.Text(value.NewState)));
        csilEntries.Add((new CborValue.Text("operation_id"), new CborValue.Text(value.OperationId)));
        if (value.ExpectedState is { } csilV7)
        {
            csilEntries.Add((new CborValue.Text("expected_state"), new CborValue.Text(csilV7)));
        }
        csilEntries.Add((new CborValue.Text("auto_target_state"), new CborValue.Text(value.AutoTargetState)));
        csilEntries.Add((new CborValue.Text("expected_revision"), new CborValue.Int(value.ExpectedRevision)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a UpdateGuardedTaskRequest from a decoded CBOR value tree.</summary>
    public static UpdateGuardedTaskRequest UpdateGuardedTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "operation_id"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField3 = Cbor.AsI64(Cbor.Require(value, "expected_revision"));
        string? csilField4 = Cbor.MapGet(value, "expected_state") is { } csilRaw4 ? Cbor.AsText(csilRaw4) : null;
        var csilField5 = Cbor.AsText(Cbor.Require(value, "new_state"));
        var csilField6 = Cbor.AsText(Cbor.Require(value, "auto_target_state"));
        var csilField7 = Cbor.AsI64(Cbor.Require(value, "timeout"));
        byte[]? csilField8 = Cbor.MapGet(value, "payload") is { } csilRaw8 ? Cbor.AsBytes(csilRaw8) : null;
        long? csilField9 = Cbor.MapGet(value, "priority") is { } csilRaw9 ? Cbor.AsI64(csilRaw9) : null;
        return new UpdateGuardedTaskRequest
        {
            OperationId = csilField0,
            Uuid = csilField1,
            Queue = csilField2,
            ExpectedRevision = csilField3,
            ExpectedState = csilField4,
            NewState = csilField5,
            AutoTargetState = csilField6,
            Timeout = csilField7,
            Payload = csilField8,
            Priority = csilField9,
        };
    }

    /// <summary>The canonical CBOR value tree for a UpdateGuardedTaskResponse.</summary>
    public static CborValue UpdateGuardedTaskResponseToCborValue(UpdateGuardedTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("task"), GuardedTaskToCborValue(value.Task)));
        csilEntries.Add((new CborValue.Text("replayed"), new CborValue.Bool(value.Replayed)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a UpdateGuardedTaskResponse from a decoded CBOR value tree.</summary>
    public static UpdateGuardedTaskResponse UpdateGuardedTaskResponseFromCborValue(CborValue value)
    {
        var csilField0 = GuardedTaskFromCborValue(Cbor.Require(value, "task"));
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "replayed"));
        return new UpdateGuardedTaskResponse
        {
            Task = csilField0,
            Replayed = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a CompleteGuardedTaskRequest.</summary>
    public static CborValue CompleteGuardedTaskRequestToCborValue(CompleteGuardedTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("operation_id"), new CborValue.Text(value.OperationId)));
        if (value.ExpectedState is { } csilV3)
        {
            csilEntries.Add((new CborValue.Text("expected_state"), new CborValue.Text(csilV3)));
        }
        csilEntries.Add((new CborValue.Text("expected_revision"), new CborValue.Int(value.ExpectedRevision)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CompleteGuardedTaskRequest from a decoded CBOR value tree.</summary>
    public static CompleteGuardedTaskRequest CompleteGuardedTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "operation_id"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField3 = Cbor.AsI64(Cbor.Require(value, "expected_revision"));
        string? csilField4 = Cbor.MapGet(value, "expected_state") is { } csilRaw4 ? Cbor.AsText(csilRaw4) : null;
        return new CompleteGuardedTaskRequest
        {
            OperationId = csilField0,
            Uuid = csilField1,
            Queue = csilField2,
            ExpectedRevision = csilField3,
            ExpectedState = csilField4,
        };
    }

    /// <summary>The canonical CBOR value tree for a CompleteGuardedTaskResponse.</summary>
    public static CborValue CompleteGuardedTaskResponseToCborValue(CompleteGuardedTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("task"), GuardedTaskToCborValue(value.Task)));
        csilEntries.Add((new CborValue.Text("replayed"), new CborValue.Bool(value.Replayed)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CompleteGuardedTaskResponse from a decoded CBOR value tree.</summary>
    public static CompleteGuardedTaskResponse CompleteGuardedTaskResponseFromCborValue(CborValue value)
    {
        var csilField0 = GuardedTaskFromCborValue(Cbor.Require(value, "task"));
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "replayed"));
        return new CompleteGuardedTaskResponse
        {
            Task = csilField0,
            Replayed = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a CancelGuardedTaskRequest.</summary>
    public static CborValue CancelGuardedTaskRequestToCborValue(CancelGuardedTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("operation_id"), new CborValue.Text(value.OperationId)));
        if (value.ExpectedState is { } csilV3)
        {
            csilEntries.Add((new CborValue.Text("expected_state"), new CborValue.Text(csilV3)));
        }
        csilEntries.Add((new CborValue.Text("expected_revision"), new CborValue.Int(value.ExpectedRevision)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CancelGuardedTaskRequest from a decoded CBOR value tree.</summary>
    public static CancelGuardedTaskRequest CancelGuardedTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "operation_id"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField3 = Cbor.AsI64(Cbor.Require(value, "expected_revision"));
        string? csilField4 = Cbor.MapGet(value, "expected_state") is { } csilRaw4 ? Cbor.AsText(csilRaw4) : null;
        return new CancelGuardedTaskRequest
        {
            OperationId = csilField0,
            Uuid = csilField1,
            Queue = csilField2,
            ExpectedRevision = csilField3,
            ExpectedState = csilField4,
        };
    }

    /// <summary>The canonical CBOR value tree for a CancelGuardedTaskResponse.</summary>
    public static CborValue CancelGuardedTaskResponseToCborValue(CancelGuardedTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("task"), GuardedTaskToCborValue(value.Task)));
        csilEntries.Add((new CborValue.Text("replayed"), new CborValue.Bool(value.Replayed)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a CancelGuardedTaskResponse from a decoded CBOR value tree.</summary>
    public static CancelGuardedTaskResponse CancelGuardedTaskResponseFromCborValue(CborValue value)
    {
        var csilField0 = GuardedTaskFromCborValue(Cbor.Require(value, "task"));
        var csilField1 = Cbor.AsBool(Cbor.Require(value, "replayed"));
        return new CancelGuardedTaskResponse
        {
            Task = csilField0,
            Replayed = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetGuardedTaskRequest.</summary>
    public static CborValue GetGuardedTaskRequestToCborValue(GetGuardedTaskRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("uuid"), new CborValue.Text(value.Uuid)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetGuardedTaskRequest from a decoded CBOR value tree.</summary>
    public static GetGuardedTaskRequest GetGuardedTaskRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "uuid"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "queue"));
        return new GetGuardedTaskRequest
        {
            Uuid = csilField0,
            Queue = csilField1,
        };
    }

    /// <summary>The canonical CBOR value tree for a GetGuardedTaskResponse.</summary>
    public static CborValue GetGuardedTaskResponseToCborValue(GetGuardedTaskResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Task is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("task"), GuardedTaskToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a GetGuardedTaskResponse from a decoded CBOR value tree.</summary>
    public static GetGuardedTaskResponse GetGuardedTaskResponseFromCborValue(CborValue value)
    {
        GuardedTask? csilField0 = Cbor.MapGet(value, "task") is { } csilRaw0 ? GuardedTaskFromCborValue(csilRaw0) : null;
        return new GetGuardedTaskResponse
        {
            Task = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a OperationReceipt.</summary>
    public static CborValue OperationReceiptToCborValue(OperationReceipt value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("at"), new CborValue.Int(value.At)));
        csilEntries.Add((new CborValue.Text("op"), new CborValue.Text(value.Op)));
        csilEntries.Add((new CborValue.Text("queue"), new CborValue.Text(value.Queue)));
        csilEntries.Add((new CborValue.Text("task_uuid"), new CborValue.Text(value.TaskUuid)));
        csilEntries.Add((new CborValue.Text("expires_at"), new CborValue.Int(value.ExpiresAt)));
        csilEntries.Add((new CborValue.Text("operation_id"), new CborValue.Text(value.OperationId)));
        csilEntries.Add((new CborValue.Text("result_state"), new CborValue.Text(value.ResultState)));
        csilEntries.Add((new CborValue.Text("result_revision"), new CborValue.Int(value.ResultRevision)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a OperationReceipt from a decoded CBOR value tree.</summary>
    public static OperationReceipt OperationReceiptFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "operation_id"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "op"));
        var csilField2 = Cbor.AsText(Cbor.Require(value, "task_uuid"));
        var csilField3 = Cbor.AsText(Cbor.Require(value, "queue"));
        var csilField4 = Cbor.AsI64(Cbor.Require(value, "result_revision"));
        var csilField5 = Cbor.AsText(Cbor.Require(value, "result_state"));
        var csilField6 = Cbor.AsI64(Cbor.Require(value, "at"));
        var csilField7 = Cbor.AsI64(Cbor.Require(value, "expires_at"));
        return new OperationReceipt
        {
            OperationId = csilField0,
            Op = csilField1,
            TaskUuid = csilField2,
            Queue = csilField3,
            ResultRevision = csilField4,
            ResultState = csilField5,
            At = csilField6,
            ExpiresAt = csilField7,
        };
    }

    /// <summary>The canonical CBOR value tree for a LookupOperationRequest.</summary>
    public static CborValue LookupOperationRequestToCborValue(LookupOperationRequest value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("operation_id"), new CborValue.Text(value.OperationId)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a LookupOperationRequest from a decoded CBOR value tree.</summary>
    public static LookupOperationRequest LookupOperationRequestFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsText(Cbor.Require(value, "operation_id"));
        return new LookupOperationRequest
        {
            OperationId = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a LookupOperationResponse.</summary>
    public static CborValue LookupOperationResponseToCborValue(LookupOperationResponse value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        if (value.Receipt is { } csilV0)
        {
            csilEntries.Add((new CborValue.Text("receipt"), OperationReceiptToCborValue(csilV0)));
        }
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a LookupOperationResponse from a decoded CBOR value tree.</summary>
    public static LookupOperationResponse LookupOperationResponseFromCborValue(CborValue value)
    {
        OperationReceipt? csilField0 = Cbor.MapGet(value, "receipt") is { } csilRaw0 ? OperationReceiptFromCborValue(csilRaw0) : null;
        return new LookupOperationResponse
        {
            Receipt = csilField0,
        };
    }

    /// <summary>The canonical CBOR value tree for a ServiceError.</summary>
    public static CborValue ServiceErrorToCborValue(ServiceError value)
    {
        var csilEntries = new System.Collections.Generic.List<(CborValue, CborValue)>();
        csilEntries.Add((new CborValue.Text("code"), new CborValue.Uint(value.Code)));
        csilEntries.Add((new CborValue.Text("message"), new CborValue.Text(value.Message)));
        return new CborValue.Map(csilEntries);
    }

    /// <summary>Reconstruct a ServiceError from a decoded CBOR value tree.</summary>
    public static ServiceError ServiceErrorFromCborValue(CborValue value)
    {
        var csilField0 = Cbor.AsU64(Cbor.Require(value, "code"));
        var csilField1 = Cbor.AsText(Cbor.Require(value, "message"));
        return new ServiceError
        {
            Code = csilField0,
            Message = csilField1,
        };
    }
}
