// <auto-generated>
// Code generated by csilgen; DO NOT EDIT.
// </auto-generated>
#nullable enable

namespace corndogs;

/// <summary>Server handler interface for the CorndogsService service.</summary>
public interface ICorndogsService
{
    SubmitTaskResponse SubmitTask(SubmitTaskRequest submitTaskRequest);
    GetTaskStateByIDResponse GetTaskStateByID(GetTaskStateByIDRequest getTaskStateByIDRequest);
    GetNextTaskResponse GetNextTask(GetNextTaskRequest getNextTaskRequest);
    GetNextTaskGroupResponse GetNextTaskGroup(GetNextTaskGroupRequest getNextTaskGroupRequest);
    UpdateTaskResponse UpdateTask(UpdateTaskRequest updateTaskRequest);
    CompleteTaskResponse CompleteTask(CompleteTaskRequest completeTaskRequest);
    CancelTaskResponse CancelTask(CancelTaskRequest cancelTaskRequest);
    CleanUpTimedOutResponse CleanUpTimedOut(CleanUpTimedOutRequest cleanUpTimedOutRequest);
    GetQueuesResponse GetQueues(GetQueuesRequest getQueuesRequest);
    GetQueueTaskCountsResponse GetQueueTaskCounts(GetQueueTaskCountsRequest getQueueTaskCountsRequest);
    GetTaskStateCountsResponse GetTaskStateCounts(GetTaskStateCountsRequest getTaskStateCountsRequest);
    GetQueueAndStateCountsResponse GetQueueAndStateCounts(GetQueueAndStateCountsRequest getQueueAndStateCountsRequest);
    GetServerInfoResponse GetServerInfo(GetServerInfoRequest getServerInfoRequest);
    SubmitKeyedTaskResponse SubmitKeyedTask(SubmitKeyedTaskRequest submitKeyedTaskRequest);
    LookupSubmissionResponse LookupSubmission(LookupSubmissionRequest lookupSubmissionRequest);
    ClaimGuardedTaskResponse ClaimGuardedTask(ClaimGuardedTaskRequest claimGuardedTaskRequest);
    ClaimGuardedTaskGroupResponse ClaimGuardedTaskGroup(ClaimGuardedTaskGroupRequest claimGuardedTaskGroupRequest);
    UpdateGuardedTaskResponse UpdateGuardedTask(UpdateGuardedTaskRequest updateGuardedTaskRequest);
    CompleteGuardedTaskResponse CompleteGuardedTask(CompleteGuardedTaskRequest completeGuardedTaskRequest);
    CancelGuardedTaskResponse CancelGuardedTask(CancelGuardedTaskRequest cancelGuardedTaskRequest);
    GetGuardedTaskResponse GetGuardedTask(GetGuardedTaskRequest getGuardedTaskRequest);
    LookupOperationResponse LookupOperation(LookupOperationRequest lookupOperationRequest);
}

