// <auto-generated>
// Code generated by csilgen; DO NOT EDIT.
// </auto-generated>
#nullable enable

global using StringInt64Map = System.Collections.Generic.Dictionary<string, long>;
global using QueueAndStateCountsMap = System.Collections.Generic.Dictionary<string, corndogs.QueueAndStateCounts>;

namespace corndogs;

public sealed record Task
{
    // CBOR key: uuid
    public required string Uuid { get; init; }
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: current_state
    public required string CurrentState { get; init; }
    // CBOR key: auto_target_state
    public required string AutoTargetState { get; init; }
    // CBOR key: submit_time
    public required long SubmitTime { get; init; }
    // CBOR key: update_time
    public required long UpdateTime { get; init; }
    // CBOR key: timeout
    public required long Timeout { get; init; }
    // CBOR key: payload
    public required byte[] Payload { get; init; }
    // CBOR key: priority
    public required long Priority { get; init; }
}

public sealed record SubmitTaskRequest
{
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: current_state
    public required string CurrentState { get; init; }
    // CBOR key: auto_target_state
    public required string AutoTargetState { get; init; }
    // CBOR key: timeout
    public required long Timeout { get; init; }
    // CBOR key: payload
    public required byte[] Payload { get; init; }
    // CBOR key: priority
    public required long Priority { get; init; }
}

public sealed record SubmitTaskResponse
{
    // CBOR key: task
    public Task? Task { get; init; }
}

public sealed record GetTaskStateByIDRequest
{
    // CBOR key: uuid
    public required string Uuid { get; init; }
    // CBOR key: queue
    public required string Queue { get; init; }
}

public sealed record GetTaskStateByIDResponse
{
    // CBOR key: task
    public Task? Task { get; init; }
}

public sealed record GetNextTaskRequest
{
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: current_state
    public required string CurrentState { get; init; }
    // CBOR key: override_timeout
    public required long OverrideTimeout { get; init; }
    // CBOR key: override_current_state
    public required string OverrideCurrentState { get; init; }
    // CBOR key: override_auto_target_state
    public required string OverrideAutoTargetState { get; init; }
}

public sealed record GetNextTaskResponse
{
    // CBOR key: task
    public Task? Task { get; init; }
}

public sealed record CompleteTaskRequest
{
    // CBOR key: uuid
    public required string Uuid { get; init; }
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: current_state
    public required string CurrentState { get; init; }
}

public sealed record CompleteTaskResponse
{
    // CBOR key: task
    public Task? Task { get; init; }
}

public sealed record UpdateTaskRequest
{
    // CBOR key: uuid
    public required string Uuid { get; init; }
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: current_state
    public required string CurrentState { get; init; }
    // CBOR key: auto_target_state
    public required string AutoTargetState { get; init; }
    // CBOR key: timeout
    public required long Timeout { get; init; }
    // CBOR key: new_state
    public required string NewState { get; init; }
    // CBOR key: payload
    public required byte[] Payload { get; init; }
    // CBOR key: priority
    public required long Priority { get; init; }
}

public sealed record UpdateTaskResponse
{
    // CBOR key: task
    public Task? Task { get; init; }
}

public sealed record CancelTaskRequest
{
    // CBOR key: uuid
    public required string Uuid { get; init; }
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: current_state
    public required string CurrentState { get; init; }
}

public sealed record CancelTaskResponse
{
    // CBOR key: task
    public Task? Task { get; init; }
}

public sealed record CleanUpTimedOutRequest
{
    // CBOR key: at_time
    public required long AtTime { get; init; }
    // CBOR key: queue
    public required string Queue { get; init; }
}

public sealed record CleanUpTimedOutResponse
{
    // CBOR key: timed_out
    public required long TimedOut { get; init; }
}

public sealed record GetQueuesRequest
{
}

public sealed record GetQueuesResponse
{
    // CBOR key: queues
    public required System.Collections.Generic.List<string> Queues { get; init; }
    // CBOR key: total_task_count
    public required long TotalTaskCount { get; init; }
}

public sealed record GetQueueTaskCountsRequest
{
}

public sealed record GetQueueTaskCountsResponse
{
    // CBOR key: queue_counts
    public required StringInt64Map QueueCounts { get; init; }
    // CBOR key: total_task_count
    public required long TotalTaskCount { get; init; }
}

public sealed record GetTaskStateCountsRequest
{
    // CBOR key: queue
    public required string Queue { get; init; }
}

public sealed record GetTaskStateCountsResponse
{
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: count
    public required long Count { get; init; }
    // CBOR key: state_counts
    public required StringInt64Map StateCounts { get; init; }
}

public sealed record QueueAndStateCounts
{
    // CBOR key: queue
    public required string Queue { get; init; }
    // CBOR key: count
    public required long Count { get; init; }
    // CBOR key: state_counts
    public required StringInt64Map StateCounts { get; init; }
}

public sealed record GetQueueAndStateCountsRequest
{
}

public sealed record GetQueueAndStateCountsResponse
{
    // CBOR key: queue_and_state_counts
    public required QueueAndStateCountsMap QueueAndStateCounts { get; init; }
}

public sealed record ServiceError
{
    // CBOR key: code
    public required ulong Code { get; init; }
    // CBOR key: message
    public required string Message { get; init; }
}

