id: corndogs-pr-clients
name: Corndogs PR Clients
description: "Test generated clients when client, CSIL, or server files change."

on:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main

paths:
  include:
    - "clients/**"
    - "csil/**"
    - "corndogs/**"

jobs:
  corndogs-client-tests:
    job_file: client-tests.yaml
