id: corndogs-pr-helm
name: Corndogs PR Helm
description: "Validate the Helm chart when chart files change."

on:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main

paths:
  include:
    - "helm_chart/chart/**"

jobs:
  corndogs-helm-validate:
    job_file: helm-validate.yaml
