id: corndogs-pr-server
name: Corndogs PR Server
description: "Build and test the server when server or CSIL files change."

on:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main

paths:
  include:
    - "corndogs/**"
    - "csil/**"

jobs:
  corndogs-test-server:
    job_file: test-server.yaml
