/* Generated CBOR (de)serializers for the CSIL value types. */
/* Code generated by csilgen; DO NOT EDIT. */
#ifndef CSILGEN_CODEC_GEN_H
#define CSILGEN_CODEC_GEN_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "types.gen.h"

/* ===== self-contained canonical CBOR codec (RFC 8949 subset) ===== */

/* The codec emits every primitive even when a spec uses only some of them; the
 * unused attribute keeps a host's -Wunused warnings quiet on the leftovers. */
#if defined(__GNUC__)
#define CSILC_UNUSED __attribute__((unused))
#else
#define CSILC_UNUSED
#endif

typedef struct csilc_buf {
    uint8_t *data;
    size_t len;
    size_t cap;
} csilc_buf;

static inline void csilc_buf_init(csilc_buf *b) {
    b->data = NULL;
    b->len = 0;
    b->cap = 0;
}

static inline void csilc_buf_dispose(csilc_buf *b) {
    free(b->data);
    b->data = NULL;
    b->len = 0;
    b->cap = 0;
}

static inline int csilc_buf_reserve(csilc_buf *b, size_t extra) {
    if (extra > SIZE_MAX - b->len) return -1;
    size_t need = b->len + extra;
    if (need <= b->cap) return 0;
    size_t cap = b->cap ? b->cap : 64;
    while (cap < need) {
        if (cap > SIZE_MAX / 2) { cap = need; break; }
        cap *= 2;
    }
    uint8_t *p = (uint8_t *)realloc(b->data, cap);
    if (!p) return -1;
    b->data = p;
    b->cap = cap;
    return 0;
}

static inline int csilc_buf_push(csilc_buf *b, uint8_t byte) {
    if (csilc_buf_reserve(b, 1)) return -1;
    b->data[b->len++] = byte;
    return 0;
}

static inline int csilc_buf_append(csilc_buf *b, const uint8_t *p, size_t n) {
    if (n == 0) return 0;
    if (csilc_buf_reserve(b, n)) return -1;
    memcpy(b->data + b->len, p, n);
    b->len += n;
    return 0;
}

/* Emit the initial byte (major type in the high three bits) plus the shortest-form
 * argument bytes for n, per deterministic encoding. */
static inline int csilc_head(csilc_buf *b, uint8_t major, uint64_t n) {
    uint8_t mt = (uint8_t)(major << 5);
    if (n < 24) return csilc_buf_push(b, (uint8_t)(mt | (uint8_t)n));
    if (n < 0x100ULL) {
        uint8_t t[2] = {(uint8_t)(mt | 24), (uint8_t)n};
        return csilc_buf_append(b, t, 2);
    }
    if (n < 0x10000ULL) {
        uint8_t t[3] = {(uint8_t)(mt | 25), (uint8_t)(n >> 8), (uint8_t)n};
        return csilc_buf_append(b, t, 3);
    }
    if (n < 0x100000000ULL) {
        uint8_t t[5] = {(uint8_t)(mt | 26), (uint8_t)(n >> 24), (uint8_t)(n >> 16),
                        (uint8_t)(n >> 8), (uint8_t)n};
        return csilc_buf_append(b, t, 5);
    }
    uint8_t t[9] = {(uint8_t)(mt | 27), (uint8_t)(n >> 56), (uint8_t)(n >> 48),
                    (uint8_t)(n >> 40), (uint8_t)(n >> 32), (uint8_t)(n >> 24),
                    (uint8_t)(n >> 16), (uint8_t)(n >> 8), (uint8_t)n};
    return csilc_buf_append(b, t, 9);
}

static inline int csilc_w_uint(csilc_buf *b, uint64_t n) { return csilc_head(b, 0, n); }

static inline int csilc_w_int(csilc_buf *b, int64_t x) {
    if (x >= 0) return csilc_head(b, 0, (uint64_t)x);
    /* CBOR negative ints encode -1-x; the magnitude is computed in unsigned to stay
     * defined even at INT64_MIN. */
    uint64_t mag = (uint64_t)(-(x + 1));
    return csilc_head(b, 1, mag);
}

static inline int csilc_w_text(csilc_buf *b, const char *s, size_t n) {
    if (csilc_head(b, 3, (uint64_t)n)) return -1;
    return csilc_buf_append(b, (const uint8_t *)s, n);
}

static inline int csilc_w_bytes(csilc_buf *b, const uint8_t *p, size_t n) {
    if (csilc_head(b, 2, (uint64_t)n)) return -1;
    return csilc_buf_append(b, p, n);
}

static inline int csilc_w_bool(csilc_buf *b, bool v) { return csilc_buf_push(b, v ? 0xf5 : 0xf4); }
static inline int csilc_w_null(csilc_buf *b) { return csilc_buf_push(b, 0xf6); }
static inline int csilc_w_array_head(csilc_buf *b, uint64_t n) { return csilc_head(b, 4, n); }
static inline int csilc_w_map_head(csilc_buf *b, uint64_t n) { return csilc_head(b, 5, n); }
static inline int csilc_w_tag(csilc_buf *b, uint64_t n) { return csilc_head(b, 6, n); }

static inline int csilc_w_f64(csilc_buf *b, double x) {
    uint64_t bits;
    memcpy(&bits, &x, 8);
    uint8_t t[9] = {0xfb, (uint8_t)(bits >> 56), (uint8_t)(bits >> 48), (uint8_t)(bits >> 40),
                    (uint8_t)(bits >> 32), (uint8_t)(bits >> 24), (uint8_t)(bits >> 16),
                    (uint8_t)(bits >> 8), (uint8_t)bits};
    return csilc_buf_append(b, t, 9);
}

static inline int csilc_w_f32(csilc_buf *b, float x) {
    uint32_t bits;
    memcpy(&bits, &x, 4);
    uint8_t t[5] = {0xfa, (uint8_t)(bits >> 24), (uint8_t)(bits >> 16),
                    (uint8_t)(bits >> 8), (uint8_t)bits};
    return csilc_buf_append(b, t, 5);
}

/* ---- bump arena (decode side) --------------------------------------------- */

typedef struct csilc_arena_block {
    struct csilc_arena_block *next;
    size_t used;
    size_t cap;
} csilc_arena_block;

typedef struct CsilCodecArena {
    csilc_arena_block *head;
} CsilCodecArena;

static inline CsilCodecArena *csilc_arena_new(void) {
    return (CsilCodecArena *)calloc(1, sizeof(CsilCodecArena));
}

static inline uint8_t *csilc_block_data(csilc_arena_block *blk) {
    return (uint8_t *)blk + sizeof(csilc_arena_block);
}

static inline void *csilc_arena_alloc(CsilCodecArena *a, size_t size) {
    if (!a) return NULL;
    size_t aligned = (size + 15u) & ~(size_t)15u;
    if (aligned < size) return NULL;
    csilc_arena_block *blk = a->head;
    if (!blk || blk->cap - blk->used < aligned) {
        size_t cap = aligned > 4096u ? aligned : 4096u;
        if (cap > SIZE_MAX - sizeof(csilc_arena_block)) return NULL;
        blk = (csilc_arena_block *)malloc(sizeof(csilc_arena_block) + cap);
        if (!blk) return NULL;
        blk->used = 0;
        blk->cap = cap;
        blk->next = a->head;
        a->head = blk;
    }
    void *p = csilc_block_data(blk) + blk->used;
    blk->used += aligned;
    return p;
}

/* Free the whole decoded value tree (and the C arrays mapped out of it) at once. */
static inline void csil_codec_arena_free(CsilCodecArena *a) {
    if (!a) return;
    csilc_arena_block *blk = a->head;
    while (blk) {
        csilc_arena_block *next = blk->next;
        free(blk);
        blk = next;
    }
    free(a);
}

/* ---- decoded value tree --------------------------------------------------- */

typedef enum csilc_kind {
    CSILC_UINT,
    CSILC_NINT,
    CSILC_TEXT,
    CSILC_BYTES,
    CSILC_ARRAY,
    CSILC_MAP,
    CSILC_TAG,
    CSILC_FLOAT,
    CSILC_BOOL,
    CSILC_NULL
} csilc_kind;

typedef struct csilc_value csilc_value;
typedef struct csilc_pair {
    csilc_value *key;
    csilc_value *val;
} csilc_pair;

struct csilc_value {
    csilc_kind kind;
    union {
        uint64_t u;
        int64_t i;
        double f;
        bool boolean;
        struct {
            const uint8_t *ptr; /* TEXT is NUL-terminated in the arena; BYTES is raw */
            size_t len;
        } bytes;
        struct {
            csilc_value *items;
            size_t count;
        } array;
        struct {
            csilc_pair *pairs;
            size_t count;
        } map;
        struct {
            uint64_t num;
            csilc_value *content;
        } tag;
    } as;
};

static inline int csilc_read_arg(const uint8_t *b, size_t len, uint8_t low, uint64_t *arg,
                          size_t *head_len) {
    if (low < 24) { *arg = low; *head_len = 1; return 0; }
    if (low == 24) {
        if (len < 2) return -1;
        *arg = b[1];
        *head_len = 2;
        return 0;
    }
    if (low == 25) {
        if (len < 3) return -1;
        *arg = ((uint64_t)b[1] << 8) | (uint64_t)b[2];
        *head_len = 3;
        return 0;
    }
    if (low == 26) {
        if (len < 5) return -1;
        *arg = ((uint64_t)b[1] << 24) | ((uint64_t)b[2] << 16) | ((uint64_t)b[3] << 8) |
               (uint64_t)b[4];
        *head_len = 5;
        return 0;
    }
    if (low == 27) {
        if (len < 9) return -1;
        uint64_t v = 0;
        for (int i = 1; i <= 8; i++) v = (v << 8) | (uint64_t)b[i];
        *arg = v;
        *head_len = 9;
        return 0;
    }
    return -1; /* 28..31 (indefinite/reserved) are forbidden */
}

static inline const uint8_t *csilc_arena_copy(CsilCodecArena *a, const uint8_t *src, size_t n,
                                       bool as_text) {
    size_t total = as_text ? n + 1 : (n ? n : 1);
    uint8_t *dst = (uint8_t *)csilc_arena_alloc(a, total);
    if (!dst) return NULL;
    if (n) memcpy(dst, src, n);
    if (as_text) dst[n] = 0;
    return dst;
}

/* Decode a half-precision float (only ever seen on decode; encode never emits one). */
static inline double csilc_half_to_double(uint16_t h) {
    uint32_t sign = (uint32_t)(h & 0x8000u) << 16;
    uint32_t exp = (h >> 10) & 0x1f;
    uint32_t mant = h & 0x3ff;
    uint32_t bits;
    if (exp == 0) {
        if (mant == 0) {
            bits = sign;
        } else {
            exp = 127 - 15 + 1;
            while ((mant & 0x400) == 0) { mant <<= 1; exp--; }
            mant &= 0x3ff;
            bits = sign | (exp << 23) | (mant << 13);
        }
    } else if (exp == 0x1f) {
        bits = sign | 0x7f800000u | (mant << 13);
    } else {
        bits = sign | ((exp + (127 - 15)) << 23) | (mant << 13);
    }
    float f;
    memcpy(&f, &bits, 4);
    return (double)f;
}

static inline int csilc_decode_value(CsilCodecArena *a, const uint8_t *b, size_t len,
                              csilc_value *out, size_t *consumed) {
    if (len == 0) return -1;
    uint8_t ib = b[0];
    uint8_t major = ib >> 5;
    uint8_t low = ib & 0x1f;
    uint64_t arg = 0;
    size_t head = 0;
    if (csilc_read_arg(b, len, low, &arg, &head)) return -1;
    switch (major) {
    case 0:
        out->kind = CSILC_UINT;
        out->as.u = arg;
        *consumed = head;
        return 0;
    case 1:
        if (arg > (uint64_t)INT64_MAX) return -1;
        out->kind = CSILC_NINT;
        out->as.i = -1 - (int64_t)arg;
        *consumed = head;
        return 0;
    case 2:
    case 3: {
        if (arg > len - head) return -1;
        bool as_text = major == 3;
        const uint8_t *copy = csilc_arena_copy(a, b + head, (size_t)arg, as_text);
        if (!copy) return -1;
        out->kind = as_text ? CSILC_TEXT : CSILC_BYTES;
        out->as.bytes.ptr = copy;
        out->as.bytes.len = (size_t)arg;
        *consumed = head + (size_t)arg;
        return 0;
    }
    case 4: {
        csilc_value *items = NULL;
        if (arg) {
            items = (csilc_value *)csilc_arena_alloc(a, (size_t)arg * sizeof(*items));
            if (!items) return -1;
        }
        size_t off = head;
        for (uint64_t i = 0; i < arg; i++) {
            size_t m = 0;
            if (csilc_decode_value(a, b + off, len - off, &items[i], &m)) return -1;
            off += m;
        }
        out->kind = CSILC_ARRAY;
        out->as.array.items = items;
        out->as.array.count = (size_t)arg;
        *consumed = off;
        return 0;
    }
    case 5: {
        csilc_pair *pairs = NULL;
        if (arg) {
            pairs = (csilc_pair *)csilc_arena_alloc(a, (size_t)arg * sizeof(*pairs));
            if (!pairs) return -1;
        }
        size_t off = head;
        for (uint64_t i = 0; i < arg; i++) {
            csilc_value *k = (csilc_value *)csilc_arena_alloc(a, sizeof(*k));
            csilc_value *v = (csilc_value *)csilc_arena_alloc(a, sizeof(*v));
            if (!k || !v) return -1;
            size_t m = 0;
            if (csilc_decode_value(a, b + off, len - off, k, &m)) return -1;
            off += m;
            if (csilc_decode_value(a, b + off, len - off, v, &m)) return -1;
            off += m;
            pairs[i].key = k;
            pairs[i].val = v;
        }
        out->kind = CSILC_MAP;
        out->as.map.pairs = pairs;
        out->as.map.count = (size_t)arg;
        *consumed = off;
        return 0;
    }
    case 6: {
        csilc_value *content = (csilc_value *)csilc_arena_alloc(a, sizeof(*content));
        if (!content) return -1;
        size_t m = 0;
        if (csilc_decode_value(a, b + head, len - head, content, &m)) return -1;
        out->kind = CSILC_TAG;
        out->as.tag.num = arg;
        out->as.tag.content = content;
        *consumed = head + m;
        return 0;
    }
    case 7:
        switch (low) {
        case 20:
            out->kind = CSILC_BOOL;
            out->as.boolean = false;
            *consumed = head;
            return 0;
        case 21:
            out->kind = CSILC_BOOL;
            out->as.boolean = true;
            *consumed = head;
            return 0;
        case 22:
        case 23:
            out->kind = CSILC_NULL;
            *consumed = head;
            return 0;
        case 25:
            out->kind = CSILC_FLOAT;
            out->as.f = csilc_half_to_double((uint16_t)arg);
            *consumed = head;
            return 0;
        case 26: {
            uint32_t bits = (uint32_t)arg;
            float f;
            memcpy(&f, &bits, 4);
            out->kind = CSILC_FLOAT;
            out->as.f = (double)f;
            *consumed = head;
            return 0;
        }
        case 27: {
            double d;
            memcpy(&d, &arg, 8);
            out->kind = CSILC_FLOAT;
            out->as.f = d;
            *consumed = head;
            return 0;
        }
        default:
            return -1;
        }
    default:
        return -1;
    }
}

static inline int csilc_decode(const uint8_t *b, size_t len, CsilCodecArena **out_arena,
                        const csilc_value **out) {
    *out_arena = NULL;
    *out = NULL;
    CsilCodecArena *a = csilc_arena_new();
    if (!a) return -1;
    csilc_value *root = (csilc_value *)csilc_arena_alloc(a, sizeof(*root));
    if (!root) {
        csil_codec_arena_free(a);
        return -1;
    }
    size_t consumed = 0;
    if (csilc_decode_value(a, b, len, root, &consumed)) {
        csil_codec_arena_free(a);
        return -1;
    }
    if (consumed != len) { /* a payload is a single self-contained item */
        csil_codec_arena_free(a);
        return -1;
    }
    *out_arena = a;
    *out = root;
    return 0;
}

static inline const csilc_value *csilc_map_get(const csilc_value *v, const char *key) {
    if (!v || v->kind != CSILC_MAP) return NULL;
    size_t klen = strlen(key);
    for (size_t i = 0; i < v->as.map.count; i++) {
        const csilc_value *k = v->as.map.pairs[i].key;
        if (k->kind == CSILC_TEXT && k->as.bytes.len == klen &&
            memcmp(k->as.bytes.ptr, key, klen) == 0) {
            return v->as.map.pairs[i].val;
        }
    }
    return NULL;
}

static inline bool csilc_as_u64(const csilc_value *v, uint64_t *out) {
    if (!v) return false;
    if (v->kind == CSILC_UINT) { *out = v->as.u; return true; }
    if (v->kind == CSILC_NINT && v->as.i >= 0) { *out = (uint64_t)v->as.i; return true; }
    return false;
}

static inline bool csilc_as_i64(const csilc_value *v, int64_t *out) {
    if (!v) return false;
    if (v->kind == CSILC_UINT) {
        if (v->as.u > (uint64_t)INT64_MAX) return false;
        *out = (int64_t)v->as.u;
        return true;
    }
    if (v->kind == CSILC_NINT) { *out = v->as.i; return true; }
    return false;
}

static inline bool csilc_as_f64(const csilc_value *v, double *out) {
    if (!v) return false;
    if (v->kind == CSILC_FLOAT) { *out = v->as.f; return true; }
    if (v->kind == CSILC_UINT) { *out = (double)v->as.u; return true; }
    if (v->kind == CSILC_NINT) { *out = (double)v->as.i; return true; }
    return false;
}

static inline bool csilc_as_bool(const csilc_value *v, bool *out) {
    if (v && v->kind == CSILC_BOOL) { *out = v->as.boolean; return true; }
    return false;
}

/* Typed field readers. Taking the value by pointer (rather than inlining a
 * `!&items[i]` test at the call site) keeps -Waddress quiet when the source is an
 * array element whose address is never NULL. */
static inline bool csilc_get_text(const csilc_value *v, char **out) {
    if (!v || v->kind != CSILC_TEXT) return false;
    *out = (char *)v->as.bytes.ptr;
    return true;
}

static inline bool csilc_get_bytes(const csilc_value *v, uint8_t **out, size_t *out_len) {
    if (!v || v->kind != CSILC_BYTES) return false;
    *out = (uint8_t *)v->as.bytes.ptr;
    *out_len = v->as.bytes.len;
    return true;
}

static inline bool csilc_get_tagged_text(const csilc_value *v, uint64_t num, const char **out) {
    if (!v || v->kind != CSILC_TAG || v->as.tag.num != num ||
        v->as.tag.content->kind != CSILC_TEXT) {
        return false;
    }
    *out = (const char *)v->as.tag.content->as.bytes.ptr;
    return true;
}

static inline bool csilc_get_decimal(const csilc_value *v, int64_t *exp, int64_t *mant) {
    if (!v || v->kind != CSILC_TAG || v->as.tag.num != 4) return false;
    const csilc_value *arr = v->as.tag.content;
    if (arr->kind != CSILC_ARRAY || arr->as.array.count != 2) return false;
    return csilc_as_i64(&arr->as.array.items[0], exp) &&
           csilc_as_i64(&arr->as.array.items[1], mant);
}

/* Re-emit a decoded value tree as CBOR, used by `any` fields that carry an opaque
 * value through verbatim. A value decoded from canonical input re-encodes to
 * identical bytes (maps keep their already-canonical input order). */
static inline int csilc_w_value(csilc_buf *b, const csilc_value *v) {
    if (!v) return csilc_w_null(b);
    switch (v->kind) {
    case CSILC_UINT: return csilc_w_uint(b, v->as.u);
    case CSILC_NINT: return csilc_w_int(b, v->as.i);
    case CSILC_TEXT: return csilc_w_text(b, (const char *)v->as.bytes.ptr, v->as.bytes.len);
    case CSILC_BYTES: return csilc_w_bytes(b, v->as.bytes.ptr, v->as.bytes.len);
    case CSILC_BOOL: return csilc_w_bool(b, v->as.boolean);
    case CSILC_NULL: return csilc_w_null(b);
    case CSILC_FLOAT: return csilc_w_f64(b, v->as.f);
    case CSILC_ARRAY:
        if (csilc_w_array_head(b, v->as.array.count)) return -1;
        for (size_t csilc_i = 0; csilc_i < v->as.array.count; csilc_i++) {
            if (csilc_w_value(b, &v->as.array.items[csilc_i])) return -1;
        }
        return 0;
    case CSILC_MAP:
        if (csilc_w_map_head(b, v->as.map.count)) return -1;
        for (size_t csilc_i = 0; csilc_i < v->as.map.count; csilc_i++) {
            if (csilc_w_value(b, v->as.map.pairs[csilc_i].key)) return -1;
            if (csilc_w_value(b, v->as.map.pairs[csilc_i].val)) return -1;
        }
        return 0;
    case CSILC_TAG:
        if (csilc_w_tag(b, v->as.tag.num)) return -1;
        return csilc_w_value(b, v->as.tag.content);
    }
    return -1;
}

/* ---- per-type codec forward declarations ---- */
static inline int csilc_enc_StringInt64Map(csilc_buf *b, const StringInt64Map *v);
static inline int csilc_dec_StringInt64Map(const csilc_value *m, CsilCodecArena *a, StringInt64Map *out);
static inline int csilc_enc_Task(csilc_buf *b, const Task *v);
static inline int csilc_dec_Task(const csilc_value *m, CsilCodecArena *a, Task *out);
static inline int csilc_enc_SubmitTaskRequest(csilc_buf *b, const SubmitTaskRequest *v);
static inline int csilc_dec_SubmitTaskRequest(const csilc_value *m, CsilCodecArena *a, SubmitTaskRequest *out);
static inline int csilc_enc_SubmitTaskResponse(csilc_buf *b, const SubmitTaskResponse *v);
static inline int csilc_dec_SubmitTaskResponse(const csilc_value *m, CsilCodecArena *a, SubmitTaskResponse *out);
static inline int csilc_enc_GetTaskStateByIDRequest(csilc_buf *b, const GetTaskStateByIDRequest *v);
static inline int csilc_dec_GetTaskStateByIDRequest(const csilc_value *m, CsilCodecArena *a, GetTaskStateByIDRequest *out);
static inline int csilc_enc_GetTaskStateByIDResponse(csilc_buf *b, const GetTaskStateByIDResponse *v);
static inline int csilc_dec_GetTaskStateByIDResponse(const csilc_value *m, CsilCodecArena *a, GetTaskStateByIDResponse *out);
static inline int csilc_enc_GetNextTaskRequest(csilc_buf *b, const GetNextTaskRequest *v);
static inline int csilc_dec_GetNextTaskRequest(const csilc_value *m, CsilCodecArena *a, GetNextTaskRequest *out);
static inline int csilc_enc_GetNextTaskResponse(csilc_buf *b, const GetNextTaskResponse *v);
static inline int csilc_dec_GetNextTaskResponse(const csilc_value *m, CsilCodecArena *a, GetNextTaskResponse *out);
static inline int csilc_enc_CompleteTaskRequest(csilc_buf *b, const CompleteTaskRequest *v);
static inline int csilc_dec_CompleteTaskRequest(const csilc_value *m, CsilCodecArena *a, CompleteTaskRequest *out);
static inline int csilc_enc_CompleteTaskResponse(csilc_buf *b, const CompleteTaskResponse *v);
static inline int csilc_dec_CompleteTaskResponse(const csilc_value *m, CsilCodecArena *a, CompleteTaskResponse *out);
static inline int csilc_enc_UpdateTaskRequest(csilc_buf *b, const UpdateTaskRequest *v);
static inline int csilc_dec_UpdateTaskRequest(const csilc_value *m, CsilCodecArena *a, UpdateTaskRequest *out);
static inline int csilc_enc_UpdateTaskResponse(csilc_buf *b, const UpdateTaskResponse *v);
static inline int csilc_dec_UpdateTaskResponse(const csilc_value *m, CsilCodecArena *a, UpdateTaskResponse *out);
static inline int csilc_enc_CancelTaskRequest(csilc_buf *b, const CancelTaskRequest *v);
static inline int csilc_dec_CancelTaskRequest(const csilc_value *m, CsilCodecArena *a, CancelTaskRequest *out);
static inline int csilc_enc_CancelTaskResponse(csilc_buf *b, const CancelTaskResponse *v);
static inline int csilc_dec_CancelTaskResponse(const csilc_value *m, CsilCodecArena *a, CancelTaskResponse *out);
static inline int csilc_enc_CleanUpTimedOutRequest(csilc_buf *b, const CleanUpTimedOutRequest *v);
static inline int csilc_dec_CleanUpTimedOutRequest(const csilc_value *m, CsilCodecArena *a, CleanUpTimedOutRequest *out);
static inline int csilc_enc_CleanUpTimedOutResponse(csilc_buf *b, const CleanUpTimedOutResponse *v);
static inline int csilc_dec_CleanUpTimedOutResponse(const csilc_value *m, CsilCodecArena *a, CleanUpTimedOutResponse *out);
static inline int csilc_enc_GetQueuesRequest(csilc_buf *b, const GetQueuesRequest *v);
static inline int csilc_dec_GetQueuesRequest(const csilc_value *m, CsilCodecArena *a, GetQueuesRequest *out);
static inline int csilc_enc_GetQueuesResponse(csilc_buf *b, const GetQueuesResponse *v);
static inline int csilc_dec_GetQueuesResponse(const csilc_value *m, CsilCodecArena *a, GetQueuesResponse *out);
static inline int csilc_enc_GetQueueTaskCountsRequest(csilc_buf *b, const GetQueueTaskCountsRequest *v);
static inline int csilc_dec_GetQueueTaskCountsRequest(const csilc_value *m, CsilCodecArena *a, GetQueueTaskCountsRequest *out);
static inline int csilc_enc_GetQueueTaskCountsResponse(csilc_buf *b, const GetQueueTaskCountsResponse *v);
static inline int csilc_dec_GetQueueTaskCountsResponse(const csilc_value *m, CsilCodecArena *a, GetQueueTaskCountsResponse *out);
static inline int csilc_enc_GetTaskStateCountsRequest(csilc_buf *b, const GetTaskStateCountsRequest *v);
static inline int csilc_dec_GetTaskStateCountsRequest(const csilc_value *m, CsilCodecArena *a, GetTaskStateCountsRequest *out);
static inline int csilc_enc_GetTaskStateCountsResponse(csilc_buf *b, const GetTaskStateCountsResponse *v);
static inline int csilc_dec_GetTaskStateCountsResponse(const csilc_value *m, CsilCodecArena *a, GetTaskStateCountsResponse *out);
static inline int csilc_enc_QueueAndStateCounts(csilc_buf *b, const QueueAndStateCounts *v);
static inline int csilc_dec_QueueAndStateCounts(const csilc_value *m, CsilCodecArena *a, QueueAndStateCounts *out);
static inline int csilc_enc_QueueAndStateCountsMap(csilc_buf *b, const QueueAndStateCountsMap *v);
static inline int csilc_dec_QueueAndStateCountsMap(const csilc_value *m, CsilCodecArena *a, QueueAndStateCountsMap *out);
static inline int csilc_enc_GetQueueAndStateCountsRequest(csilc_buf *b, const GetQueueAndStateCountsRequest *v);
static inline int csilc_dec_GetQueueAndStateCountsRequest(const csilc_value *m, CsilCodecArena *a, GetQueueAndStateCountsRequest *out);
static inline int csilc_enc_GetQueueAndStateCountsResponse(csilc_buf *b, const GetQueueAndStateCountsResponse *v);
static inline int csilc_dec_GetQueueAndStateCountsResponse(const csilc_value *m, CsilCodecArena *a, GetQueueAndStateCountsResponse *out);
static inline int csilc_enc_ServiceError(csilc_buf *b, const ServiceError *v);
static inline int csilc_dec_ServiceError(const csilc_value *m, CsilCodecArena *a, ServiceError *out);

/* csilc_enc_StringInt64Map writes StringInt64Map as a CBOR map of text keys to encoded values. */
static inline int csilc_enc_StringInt64Map(csilc_buf *b, const StringInt64Map *v) {
    if (csilc_w_map_head(b, v->count)) return -1;
    for (size_t csilc_i = 0; csilc_i < v->count; csilc_i++) {
        if (csilc_w_text(b, (v->keys[csilc_i]), (v->keys[csilc_i]) ? strlen(v->keys[csilc_i]) : 0)) return -1;
        if (csilc_w_int(b, (int64_t)(v->values[csilc_i]))) return -1;
    }
    return 0;
}

/* csilc_dec_StringInt64Map reads StringInt64Map from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_StringInt64Map(const csilc_value *m, CsilCodecArena *a, StringInt64Map *out) {
    if (!m || m->kind != CSILC_MAP) return -1;
    out->count = m->as.map.count;
    out->keys = NULL;
    out->values = NULL;
    if (out->count) {
        out->keys = (char * *)csilc_arena_alloc(a, out->count * sizeof(char *));
        out->values = (int64_t *)csilc_arena_alloc(a, out->count * sizeof(int64_t));
        if (!out->keys || !out->values) return -1;
        for (size_t csilc_i = 0; csilc_i < out->count; csilc_i++) {
            if (!csilc_get_text(m->as.map.pairs[csilc_i].key, &(out->keys[csilc_i]))) return -1;
            if (!csilc_as_i64(m->as.map.pairs[csilc_i].val, &(out->values[csilc_i]))) return -1;
        }
    }
    return 0;
}

/* csilc_enc_Task writes Task as a canonical CBOR map. */
static inline int csilc_enc_Task(csilc_buf *b, const Task *v) {
    size_t csilc_n = 9;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "uuid", 4)) return -1;
    if (csilc_w_text(b, (v->uuid), (v->uuid) ? strlen(v->uuid) : 0)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "payload", 7)) return -1;
    if (csilc_w_bytes(b, (v->payload).data, (v->payload).len)) return -1;
    if (csilc_w_text(b, "timeout", 7)) return -1;
    if (csilc_w_int(b, (int64_t)(v->timeout))) return -1;
    if (csilc_w_text(b, "priority", 8)) return -1;
    if (csilc_w_int(b, (int64_t)(v->priority))) return -1;
    if (csilc_w_text(b, "submit_time", 11)) return -1;
    if (csilc_w_int(b, (int64_t)(v->submit_time))) return -1;
    if (csilc_w_text(b, "update_time", 11)) return -1;
    if (csilc_w_int(b, (int64_t)(v->update_time))) return -1;
    if (csilc_w_text(b, "current_state", 13)) return -1;
    if (csilc_w_text(b, (v->current_state), (v->current_state) ? strlen(v->current_state) : 0)) return -1;
    if (csilc_w_text(b, "auto_target_state", 17)) return -1;
    if (csilc_w_text(b, (v->auto_target_state), (v->auto_target_state) ? strlen(v->auto_target_state) : 0)) return -1;
    return 0;
}

/* csilc_dec_Task reads Task from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_Task(const csilc_value *m, CsilCodecArena *a, Task *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "uuid");
    if (!csilc_get_text(csilc_f, &(out->uuid))) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "payload");
    if (!csilc_get_bytes(csilc_f, &(out->payload).data, &(out->payload).len)) return -1;
    csilc_f = csilc_map_get(m, "timeout");
    if (!csilc_as_i64(csilc_f, &(out->timeout))) return -1;
    csilc_f = csilc_map_get(m, "priority");
    if (!csilc_as_i64(csilc_f, &(out->priority))) return -1;
    csilc_f = csilc_map_get(m, "submit_time");
    if (!csilc_as_i64(csilc_f, &(out->submit_time))) return -1;
    csilc_f = csilc_map_get(m, "update_time");
    if (!csilc_as_i64(csilc_f, &(out->update_time))) return -1;
    csilc_f = csilc_map_get(m, "current_state");
    if (!csilc_get_text(csilc_f, &(out->current_state))) return -1;
    csilc_f = csilc_map_get(m, "auto_target_state");
    if (!csilc_get_text(csilc_f, &(out->auto_target_state))) return -1;
    return 0;
}

/* csilc_enc_SubmitTaskRequest writes SubmitTaskRequest as a canonical CBOR map. */
static inline int csilc_enc_SubmitTaskRequest(csilc_buf *b, const SubmitTaskRequest *v) {
    size_t csilc_n = 6;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "payload", 7)) return -1;
    if (csilc_w_bytes(b, (v->payload).data, (v->payload).len)) return -1;
    if (csilc_w_text(b, "timeout", 7)) return -1;
    if (csilc_w_int(b, (int64_t)(v->timeout))) return -1;
    if (csilc_w_text(b, "priority", 8)) return -1;
    if (csilc_w_int(b, (int64_t)(v->priority))) return -1;
    if (csilc_w_text(b, "current_state", 13)) return -1;
    if (csilc_w_text(b, (v->current_state), (v->current_state) ? strlen(v->current_state) : 0)) return -1;
    if (csilc_w_text(b, "auto_target_state", 17)) return -1;
    if (csilc_w_text(b, (v->auto_target_state), (v->auto_target_state) ? strlen(v->auto_target_state) : 0)) return -1;
    return 0;
}

/* csilc_dec_SubmitTaskRequest reads SubmitTaskRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_SubmitTaskRequest(const csilc_value *m, CsilCodecArena *a, SubmitTaskRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "payload");
    if (!csilc_get_bytes(csilc_f, &(out->payload).data, &(out->payload).len)) return -1;
    csilc_f = csilc_map_get(m, "timeout");
    if (!csilc_as_i64(csilc_f, &(out->timeout))) return -1;
    csilc_f = csilc_map_get(m, "priority");
    if (!csilc_as_i64(csilc_f, &(out->priority))) return -1;
    csilc_f = csilc_map_get(m, "current_state");
    if (!csilc_get_text(csilc_f, &(out->current_state))) return -1;
    csilc_f = csilc_map_get(m, "auto_target_state");
    if (!csilc_get_text(csilc_f, &(out->auto_target_state))) return -1;
    return 0;
}

/* csilc_enc_SubmitTaskResponse writes SubmitTaskResponse as a canonical CBOR map. */
static inline int csilc_enc_SubmitTaskResponse(csilc_buf *b, const SubmitTaskResponse *v) {
    size_t csilc_n = 0;
    if (v->task) csilc_n++;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (v->task) {
        if (csilc_w_text(b, "task", 4)) return -1;
        if (csilc_enc_Task(b, &((*v->task)))) return -1;
    }
    return 0;
}

/* csilc_dec_SubmitTaskResponse reads SubmitTaskResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_SubmitTaskResponse(const csilc_value *m, CsilCodecArena *a, SubmitTaskResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "task");
    out->task = NULL;
    if (csilc_f) {
        Task *csilc_p = (Task *)csilc_arena_alloc(a, sizeof(Task));
        if (!csilc_p) return -1;
        if (csilc_dec_Task(csilc_f, a, &((*csilc_p)))) return -1;
        out->task = csilc_p;
    }
    return 0;
}

/* csilc_enc_GetTaskStateByIDRequest writes GetTaskStateByIDRequest as a canonical CBOR map. */
static inline int csilc_enc_GetTaskStateByIDRequest(csilc_buf *b, const GetTaskStateByIDRequest *v) {
    size_t csilc_n = 2;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "uuid", 4)) return -1;
    if (csilc_w_text(b, (v->uuid), (v->uuid) ? strlen(v->uuid) : 0)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    return 0;
}

/* csilc_dec_GetTaskStateByIDRequest reads GetTaskStateByIDRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetTaskStateByIDRequest(const csilc_value *m, CsilCodecArena *a, GetTaskStateByIDRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "uuid");
    if (!csilc_get_text(csilc_f, &(out->uuid))) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    return 0;
}

/* csilc_enc_GetTaskStateByIDResponse writes GetTaskStateByIDResponse as a canonical CBOR map. */
static inline int csilc_enc_GetTaskStateByIDResponse(csilc_buf *b, const GetTaskStateByIDResponse *v) {
    size_t csilc_n = 0;
    if (v->task) csilc_n++;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (v->task) {
        if (csilc_w_text(b, "task", 4)) return -1;
        if (csilc_enc_Task(b, &((*v->task)))) return -1;
    }
    return 0;
}

/* csilc_dec_GetTaskStateByIDResponse reads GetTaskStateByIDResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetTaskStateByIDResponse(const csilc_value *m, CsilCodecArena *a, GetTaskStateByIDResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "task");
    out->task = NULL;
    if (csilc_f) {
        Task *csilc_p = (Task *)csilc_arena_alloc(a, sizeof(Task));
        if (!csilc_p) return -1;
        if (csilc_dec_Task(csilc_f, a, &((*csilc_p)))) return -1;
        out->task = csilc_p;
    }
    return 0;
}

/* csilc_enc_GetNextTaskRequest writes GetNextTaskRequest as a canonical CBOR map. */
static inline int csilc_enc_GetNextTaskRequest(csilc_buf *b, const GetNextTaskRequest *v) {
    size_t csilc_n = 5;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "current_state", 13)) return -1;
    if (csilc_w_text(b, (v->current_state), (v->current_state) ? strlen(v->current_state) : 0)) return -1;
    if (csilc_w_text(b, "override_timeout", 16)) return -1;
    if (csilc_w_int(b, (int64_t)(v->override_timeout))) return -1;
    if (csilc_w_text(b, "override_current_state", 22)) return -1;
    if (csilc_w_text(b, (v->override_current_state), (v->override_current_state) ? strlen(v->override_current_state) : 0)) return -1;
    if (csilc_w_text(b, "override_auto_target_state", 26)) return -1;
    if (csilc_w_text(b, (v->override_auto_target_state), (v->override_auto_target_state) ? strlen(v->override_auto_target_state) : 0)) return -1;
    return 0;
}

/* csilc_dec_GetNextTaskRequest reads GetNextTaskRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetNextTaskRequest(const csilc_value *m, CsilCodecArena *a, GetNextTaskRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "current_state");
    if (!csilc_get_text(csilc_f, &(out->current_state))) return -1;
    csilc_f = csilc_map_get(m, "override_timeout");
    if (!csilc_as_i64(csilc_f, &(out->override_timeout))) return -1;
    csilc_f = csilc_map_get(m, "override_current_state");
    if (!csilc_get_text(csilc_f, &(out->override_current_state))) return -1;
    csilc_f = csilc_map_get(m, "override_auto_target_state");
    if (!csilc_get_text(csilc_f, &(out->override_auto_target_state))) return -1;
    return 0;
}

/* csilc_enc_GetNextTaskResponse writes GetNextTaskResponse as a canonical CBOR map. */
static inline int csilc_enc_GetNextTaskResponse(csilc_buf *b, const GetNextTaskResponse *v) {
    size_t csilc_n = 0;
    if (v->task) csilc_n++;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (v->task) {
        if (csilc_w_text(b, "task", 4)) return -1;
        if (csilc_enc_Task(b, &((*v->task)))) return -1;
    }
    return 0;
}

/* csilc_dec_GetNextTaskResponse reads GetNextTaskResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetNextTaskResponse(const csilc_value *m, CsilCodecArena *a, GetNextTaskResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "task");
    out->task = NULL;
    if (csilc_f) {
        Task *csilc_p = (Task *)csilc_arena_alloc(a, sizeof(Task));
        if (!csilc_p) return -1;
        if (csilc_dec_Task(csilc_f, a, &((*csilc_p)))) return -1;
        out->task = csilc_p;
    }
    return 0;
}

/* csilc_enc_CompleteTaskRequest writes CompleteTaskRequest as a canonical CBOR map. */
static inline int csilc_enc_CompleteTaskRequest(csilc_buf *b, const CompleteTaskRequest *v) {
    size_t csilc_n = 3;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "uuid", 4)) return -1;
    if (csilc_w_text(b, (v->uuid), (v->uuid) ? strlen(v->uuid) : 0)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "current_state", 13)) return -1;
    if (csilc_w_text(b, (v->current_state), (v->current_state) ? strlen(v->current_state) : 0)) return -1;
    return 0;
}

/* csilc_dec_CompleteTaskRequest reads CompleteTaskRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_CompleteTaskRequest(const csilc_value *m, CsilCodecArena *a, CompleteTaskRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "uuid");
    if (!csilc_get_text(csilc_f, &(out->uuid))) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "current_state");
    if (!csilc_get_text(csilc_f, &(out->current_state))) return -1;
    return 0;
}

/* csilc_enc_CompleteTaskResponse writes CompleteTaskResponse as a canonical CBOR map. */
static inline int csilc_enc_CompleteTaskResponse(csilc_buf *b, const CompleteTaskResponse *v) {
    size_t csilc_n = 0;
    if (v->task) csilc_n++;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (v->task) {
        if (csilc_w_text(b, "task", 4)) return -1;
        if (csilc_enc_Task(b, &((*v->task)))) return -1;
    }
    return 0;
}

/* csilc_dec_CompleteTaskResponse reads CompleteTaskResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_CompleteTaskResponse(const csilc_value *m, CsilCodecArena *a, CompleteTaskResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "task");
    out->task = NULL;
    if (csilc_f) {
        Task *csilc_p = (Task *)csilc_arena_alloc(a, sizeof(Task));
        if (!csilc_p) return -1;
        if (csilc_dec_Task(csilc_f, a, &((*csilc_p)))) return -1;
        out->task = csilc_p;
    }
    return 0;
}

/* csilc_enc_UpdateTaskRequest writes UpdateTaskRequest as a canonical CBOR map. */
static inline int csilc_enc_UpdateTaskRequest(csilc_buf *b, const UpdateTaskRequest *v) {
    size_t csilc_n = 8;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "uuid", 4)) return -1;
    if (csilc_w_text(b, (v->uuid), (v->uuid) ? strlen(v->uuid) : 0)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "payload", 7)) return -1;
    if (csilc_w_bytes(b, (v->payload).data, (v->payload).len)) return -1;
    if (csilc_w_text(b, "timeout", 7)) return -1;
    if (csilc_w_int(b, (int64_t)(v->timeout))) return -1;
    if (csilc_w_text(b, "priority", 8)) return -1;
    if (csilc_w_int(b, (int64_t)(v->priority))) return -1;
    if (csilc_w_text(b, "new_state", 9)) return -1;
    if (csilc_w_text(b, (v->new_state), (v->new_state) ? strlen(v->new_state) : 0)) return -1;
    if (csilc_w_text(b, "current_state", 13)) return -1;
    if (csilc_w_text(b, (v->current_state), (v->current_state) ? strlen(v->current_state) : 0)) return -1;
    if (csilc_w_text(b, "auto_target_state", 17)) return -1;
    if (csilc_w_text(b, (v->auto_target_state), (v->auto_target_state) ? strlen(v->auto_target_state) : 0)) return -1;
    return 0;
}

/* csilc_dec_UpdateTaskRequest reads UpdateTaskRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_UpdateTaskRequest(const csilc_value *m, CsilCodecArena *a, UpdateTaskRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "uuid");
    if (!csilc_get_text(csilc_f, &(out->uuid))) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "payload");
    if (!csilc_get_bytes(csilc_f, &(out->payload).data, &(out->payload).len)) return -1;
    csilc_f = csilc_map_get(m, "timeout");
    if (!csilc_as_i64(csilc_f, &(out->timeout))) return -1;
    csilc_f = csilc_map_get(m, "priority");
    if (!csilc_as_i64(csilc_f, &(out->priority))) return -1;
    csilc_f = csilc_map_get(m, "new_state");
    if (!csilc_get_text(csilc_f, &(out->new_state))) return -1;
    csilc_f = csilc_map_get(m, "current_state");
    if (!csilc_get_text(csilc_f, &(out->current_state))) return -1;
    csilc_f = csilc_map_get(m, "auto_target_state");
    if (!csilc_get_text(csilc_f, &(out->auto_target_state))) return -1;
    return 0;
}

/* csilc_enc_UpdateTaskResponse writes UpdateTaskResponse as a canonical CBOR map. */
static inline int csilc_enc_UpdateTaskResponse(csilc_buf *b, const UpdateTaskResponse *v) {
    size_t csilc_n = 0;
    if (v->task) csilc_n++;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (v->task) {
        if (csilc_w_text(b, "task", 4)) return -1;
        if (csilc_enc_Task(b, &((*v->task)))) return -1;
    }
    return 0;
}

/* csilc_dec_UpdateTaskResponse reads UpdateTaskResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_UpdateTaskResponse(const csilc_value *m, CsilCodecArena *a, UpdateTaskResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "task");
    out->task = NULL;
    if (csilc_f) {
        Task *csilc_p = (Task *)csilc_arena_alloc(a, sizeof(Task));
        if (!csilc_p) return -1;
        if (csilc_dec_Task(csilc_f, a, &((*csilc_p)))) return -1;
        out->task = csilc_p;
    }
    return 0;
}

/* csilc_enc_CancelTaskRequest writes CancelTaskRequest as a canonical CBOR map. */
static inline int csilc_enc_CancelTaskRequest(csilc_buf *b, const CancelTaskRequest *v) {
    size_t csilc_n = 3;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "uuid", 4)) return -1;
    if (csilc_w_text(b, (v->uuid), (v->uuid) ? strlen(v->uuid) : 0)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "current_state", 13)) return -1;
    if (csilc_w_text(b, (v->current_state), (v->current_state) ? strlen(v->current_state) : 0)) return -1;
    return 0;
}

/* csilc_dec_CancelTaskRequest reads CancelTaskRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_CancelTaskRequest(const csilc_value *m, CsilCodecArena *a, CancelTaskRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "uuid");
    if (!csilc_get_text(csilc_f, &(out->uuid))) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "current_state");
    if (!csilc_get_text(csilc_f, &(out->current_state))) return -1;
    return 0;
}

/* csilc_enc_CancelTaskResponse writes CancelTaskResponse as a canonical CBOR map. */
static inline int csilc_enc_CancelTaskResponse(csilc_buf *b, const CancelTaskResponse *v) {
    size_t csilc_n = 0;
    if (v->task) csilc_n++;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (v->task) {
        if (csilc_w_text(b, "task", 4)) return -1;
        if (csilc_enc_Task(b, &((*v->task)))) return -1;
    }
    return 0;
}

/* csilc_dec_CancelTaskResponse reads CancelTaskResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_CancelTaskResponse(const csilc_value *m, CsilCodecArena *a, CancelTaskResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "task");
    out->task = NULL;
    if (csilc_f) {
        Task *csilc_p = (Task *)csilc_arena_alloc(a, sizeof(Task));
        if (!csilc_p) return -1;
        if (csilc_dec_Task(csilc_f, a, &((*csilc_p)))) return -1;
        out->task = csilc_p;
    }
    return 0;
}

/* csilc_enc_CleanUpTimedOutRequest writes CleanUpTimedOutRequest as a canonical CBOR map. */
static inline int csilc_enc_CleanUpTimedOutRequest(csilc_buf *b, const CleanUpTimedOutRequest *v) {
    size_t csilc_n = 2;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "at_time", 7)) return -1;
    if (csilc_w_int(b, (int64_t)(v->at_time))) return -1;
    return 0;
}

/* csilc_dec_CleanUpTimedOutRequest reads CleanUpTimedOutRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_CleanUpTimedOutRequest(const csilc_value *m, CsilCodecArena *a, CleanUpTimedOutRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "at_time");
    if (!csilc_as_i64(csilc_f, &(out->at_time))) return -1;
    return 0;
}

/* csilc_enc_CleanUpTimedOutResponse writes CleanUpTimedOutResponse as a canonical CBOR map. */
static inline int csilc_enc_CleanUpTimedOutResponse(csilc_buf *b, const CleanUpTimedOutResponse *v) {
    size_t csilc_n = 1;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "timed_out", 9)) return -1;
    if (csilc_w_int(b, (int64_t)(v->timed_out))) return -1;
    return 0;
}

/* csilc_dec_CleanUpTimedOutResponse reads CleanUpTimedOutResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_CleanUpTimedOutResponse(const csilc_value *m, CsilCodecArena *a, CleanUpTimedOutResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "timed_out");
    if (!csilc_as_i64(csilc_f, &(out->timed_out))) return -1;
    return 0;
}

/* csilc_enc_GetQueuesRequest writes GetQueuesRequest as a canonical CBOR map. */
static inline int csilc_enc_GetQueuesRequest(csilc_buf *b, const GetQueuesRequest *v) {
    size_t csilc_n = 0;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    (void)v;
    return 0;
}

/* csilc_dec_GetQueuesRequest reads GetQueuesRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetQueuesRequest(const csilc_value *m, CsilCodecArena *a, GetQueuesRequest *out) {
    (void)a;
    (void)out;
    if (!m || m->kind != CSILC_MAP) return -1;
    return 0;
}

/* csilc_enc_GetQueuesResponse writes GetQueuesResponse as a canonical CBOR map. */
static inline int csilc_enc_GetQueuesResponse(csilc_buf *b, const GetQueuesResponse *v) {
    size_t csilc_n = 2;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "queues", 6)) return -1;
    if (csilc_w_array_head(b, v->queues_count)) return -1;
    for (size_t csilc_i = 0; csilc_i < v->queues_count; csilc_i++) {
        if (csilc_w_text(b, (v->queues[csilc_i]), (v->queues[csilc_i]) ? strlen(v->queues[csilc_i]) : 0)) return -1;
    }
    if (csilc_w_text(b, "total_task_count", 16)) return -1;
    if (csilc_w_int(b, (int64_t)(v->total_task_count))) return -1;
    return 0;
}

/* csilc_dec_GetQueuesResponse reads GetQueuesResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetQueuesResponse(const csilc_value *m, CsilCodecArena *a, GetQueuesResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "queues");
    if (!csilc_f || csilc_f->kind != CSILC_ARRAY) return -1;
    out->queues_count = csilc_f->as.array.count;
    out->queues = NULL;
    if (out->queues_count) {
        out->queues = (char * *)csilc_arena_alloc(a, out->queues_count * sizeof(char *));
        if (!out->queues) return -1;
        for (size_t csilc_i = 0; csilc_i < out->queues_count; csilc_i++) {
            if (!csilc_get_text(&csilc_f->as.array.items[csilc_i], &(out->queues[csilc_i]))) return -1;
        }
    }
    csilc_f = csilc_map_get(m, "total_task_count");
    if (!csilc_as_i64(csilc_f, &(out->total_task_count))) return -1;
    return 0;
}

/* csilc_enc_GetQueueTaskCountsRequest writes GetQueueTaskCountsRequest as a canonical CBOR map. */
static inline int csilc_enc_GetQueueTaskCountsRequest(csilc_buf *b, const GetQueueTaskCountsRequest *v) {
    size_t csilc_n = 0;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    (void)v;
    return 0;
}

/* csilc_dec_GetQueueTaskCountsRequest reads GetQueueTaskCountsRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetQueueTaskCountsRequest(const csilc_value *m, CsilCodecArena *a, GetQueueTaskCountsRequest *out) {
    (void)a;
    (void)out;
    if (!m || m->kind != CSILC_MAP) return -1;
    return 0;
}

/* csilc_enc_GetQueueTaskCountsResponse writes GetQueueTaskCountsResponse as a canonical CBOR map. */
static inline int csilc_enc_GetQueueTaskCountsResponse(csilc_buf *b, const GetQueueTaskCountsResponse *v) {
    size_t csilc_n = 2;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "queue_counts", 12)) return -1;
    if (csilc_enc_StringInt64Map(b, &(v->queue_counts))) return -1;
    if (csilc_w_text(b, "total_task_count", 16)) return -1;
    if (csilc_w_int(b, (int64_t)(v->total_task_count))) return -1;
    return 0;
}

/* csilc_dec_GetQueueTaskCountsResponse reads GetQueueTaskCountsResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetQueueTaskCountsResponse(const csilc_value *m, CsilCodecArena *a, GetQueueTaskCountsResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "queue_counts");
    if (csilc_dec_StringInt64Map(csilc_f, a, &(out->queue_counts))) return -1;
    csilc_f = csilc_map_get(m, "total_task_count");
    if (!csilc_as_i64(csilc_f, &(out->total_task_count))) return -1;
    return 0;
}

/* csilc_enc_GetTaskStateCountsRequest writes GetTaskStateCountsRequest as a canonical CBOR map. */
static inline int csilc_enc_GetTaskStateCountsRequest(csilc_buf *b, const GetTaskStateCountsRequest *v) {
    size_t csilc_n = 1;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    return 0;
}

/* csilc_dec_GetTaskStateCountsRequest reads GetTaskStateCountsRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetTaskStateCountsRequest(const csilc_value *m, CsilCodecArena *a, GetTaskStateCountsRequest *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    return 0;
}

/* csilc_enc_GetTaskStateCountsResponse writes GetTaskStateCountsResponse as a canonical CBOR map. */
static inline int csilc_enc_GetTaskStateCountsResponse(csilc_buf *b, const GetTaskStateCountsResponse *v) {
    size_t csilc_n = 3;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "count", 5)) return -1;
    if (csilc_w_int(b, (int64_t)(v->count))) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "state_counts", 12)) return -1;
    if (csilc_enc_StringInt64Map(b, &(v->state_counts))) return -1;
    return 0;
}

/* csilc_dec_GetTaskStateCountsResponse reads GetTaskStateCountsResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetTaskStateCountsResponse(const csilc_value *m, CsilCodecArena *a, GetTaskStateCountsResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "count");
    if (!csilc_as_i64(csilc_f, &(out->count))) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "state_counts");
    if (csilc_dec_StringInt64Map(csilc_f, a, &(out->state_counts))) return -1;
    return 0;
}

/* csilc_enc_QueueAndStateCounts writes QueueAndStateCounts as a canonical CBOR map. */
static inline int csilc_enc_QueueAndStateCounts(csilc_buf *b, const QueueAndStateCounts *v) {
    size_t csilc_n = 3;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "count", 5)) return -1;
    if (csilc_w_int(b, (int64_t)(v->count))) return -1;
    if (csilc_w_text(b, "queue", 5)) return -1;
    if (csilc_w_text(b, (v->queue), (v->queue) ? strlen(v->queue) : 0)) return -1;
    if (csilc_w_text(b, "state_counts", 12)) return -1;
    if (csilc_enc_StringInt64Map(b, &(v->state_counts))) return -1;
    return 0;
}

/* csilc_dec_QueueAndStateCounts reads QueueAndStateCounts from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_QueueAndStateCounts(const csilc_value *m, CsilCodecArena *a, QueueAndStateCounts *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "count");
    if (!csilc_as_i64(csilc_f, &(out->count))) return -1;
    csilc_f = csilc_map_get(m, "queue");
    if (!csilc_get_text(csilc_f, &(out->queue))) return -1;
    csilc_f = csilc_map_get(m, "state_counts");
    if (csilc_dec_StringInt64Map(csilc_f, a, &(out->state_counts))) return -1;
    return 0;
}

/* csilc_enc_QueueAndStateCountsMap writes QueueAndStateCountsMap as a CBOR map of text keys to encoded values. */
static inline int csilc_enc_QueueAndStateCountsMap(csilc_buf *b, const QueueAndStateCountsMap *v) {
    if (csilc_w_map_head(b, v->count)) return -1;
    for (size_t csilc_i = 0; csilc_i < v->count; csilc_i++) {
        if (csilc_w_text(b, (v->keys[csilc_i]), (v->keys[csilc_i]) ? strlen(v->keys[csilc_i]) : 0)) return -1;
        if (csilc_enc_QueueAndStateCounts(b, &(v->values[csilc_i]))) return -1;
    }
    return 0;
}

/* csilc_dec_QueueAndStateCountsMap reads QueueAndStateCountsMap from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_QueueAndStateCountsMap(const csilc_value *m, CsilCodecArena *a, QueueAndStateCountsMap *out) {
    if (!m || m->kind != CSILC_MAP) return -1;
    out->count = m->as.map.count;
    out->keys = NULL;
    out->values = NULL;
    if (out->count) {
        out->keys = (char * *)csilc_arena_alloc(a, out->count * sizeof(char *));
        out->values = (QueueAndStateCounts *)csilc_arena_alloc(a, out->count * sizeof(QueueAndStateCounts));
        if (!out->keys || !out->values) return -1;
        for (size_t csilc_i = 0; csilc_i < out->count; csilc_i++) {
            if (!csilc_get_text(m->as.map.pairs[csilc_i].key, &(out->keys[csilc_i]))) return -1;
            if (csilc_dec_QueueAndStateCounts(m->as.map.pairs[csilc_i].val, a, &(out->values[csilc_i]))) return -1;
        }
    }
    return 0;
}

/* csilc_enc_GetQueueAndStateCountsRequest writes GetQueueAndStateCountsRequest as a canonical CBOR map. */
static inline int csilc_enc_GetQueueAndStateCountsRequest(csilc_buf *b, const GetQueueAndStateCountsRequest *v) {
    size_t csilc_n = 0;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    (void)v;
    return 0;
}

/* csilc_dec_GetQueueAndStateCountsRequest reads GetQueueAndStateCountsRequest from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetQueueAndStateCountsRequest(const csilc_value *m, CsilCodecArena *a, GetQueueAndStateCountsRequest *out) {
    (void)a;
    (void)out;
    if (!m || m->kind != CSILC_MAP) return -1;
    return 0;
}

/* csilc_enc_GetQueueAndStateCountsResponse writes GetQueueAndStateCountsResponse as a canonical CBOR map. */
static inline int csilc_enc_GetQueueAndStateCountsResponse(csilc_buf *b, const GetQueueAndStateCountsResponse *v) {
    size_t csilc_n = 1;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "queue_and_state_counts", 22)) return -1;
    if (csilc_enc_QueueAndStateCountsMap(b, &(v->queue_and_state_counts))) return -1;
    return 0;
}

/* csilc_dec_GetQueueAndStateCountsResponse reads GetQueueAndStateCountsResponse from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_GetQueueAndStateCountsResponse(const csilc_value *m, CsilCodecArena *a, GetQueueAndStateCountsResponse *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "queue_and_state_counts");
    if (csilc_dec_QueueAndStateCountsMap(csilc_f, a, &(out->queue_and_state_counts))) return -1;
    return 0;
}

/* csilc_enc_ServiceError writes ServiceError as a canonical CBOR map. */
static inline int csilc_enc_ServiceError(csilc_buf *b, const ServiceError *v) {
    size_t csilc_n = 2;
    if (csilc_w_map_head(b, csilc_n)) return -1;
    if (csilc_w_text(b, "code", 4)) return -1;
    if (csilc_w_uint(b, (uint64_t)(v->code))) return -1;
    if (csilc_w_text(b, "message", 7)) return -1;
    if (csilc_w_text(b, (v->message), (v->message) ? strlen(v->message) : 0)) return -1;
    return 0;
}

/* csilc_dec_ServiceError reads ServiceError from a decoded CBOR map (arena-borrowed). */
static inline int csilc_dec_ServiceError(const csilc_value *m, CsilCodecArena *a, ServiceError *out) {
    (void)a;
    const csilc_value *csilc_f;
    if (!m || m->kind != CSILC_MAP) return -1;
    csilc_f = csilc_map_get(m, "code");
    if (!csilc_as_u64(csilc_f, &(out->code))) return -1;
    csilc_f = csilc_map_get(m, "message");
    if (!csilc_get_text(csilc_f, &(out->message))) return -1;
    return 0;
}

/* Encode a StringInt64Map to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_StringInt64Map(const StringInt64Map *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_StringInt64Map(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a StringInt64Map. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_StringInt64Map(const uint8_t *in, size_t len, StringInt64Map *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_StringInt64Map(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a Task to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_Task(const Task *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_Task(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a Task. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_Task(const uint8_t *in, size_t len, Task *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_Task(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a SubmitTaskRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_SubmitTaskRequest(const SubmitTaskRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_SubmitTaskRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a SubmitTaskRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_SubmitTaskRequest(const uint8_t *in, size_t len, SubmitTaskRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_SubmitTaskRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a SubmitTaskResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_SubmitTaskResponse(const SubmitTaskResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_SubmitTaskResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a SubmitTaskResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_SubmitTaskResponse(const uint8_t *in, size_t len, SubmitTaskResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_SubmitTaskResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetTaskStateByIDRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetTaskStateByIDRequest(const GetTaskStateByIDRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetTaskStateByIDRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetTaskStateByIDRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetTaskStateByIDRequest(const uint8_t *in, size_t len, GetTaskStateByIDRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetTaskStateByIDRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetTaskStateByIDResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetTaskStateByIDResponse(const GetTaskStateByIDResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetTaskStateByIDResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetTaskStateByIDResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetTaskStateByIDResponse(const uint8_t *in, size_t len, GetTaskStateByIDResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetTaskStateByIDResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetNextTaskRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetNextTaskRequest(const GetNextTaskRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetNextTaskRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetNextTaskRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetNextTaskRequest(const uint8_t *in, size_t len, GetNextTaskRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetNextTaskRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetNextTaskResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetNextTaskResponse(const GetNextTaskResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetNextTaskResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetNextTaskResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetNextTaskResponse(const uint8_t *in, size_t len, GetNextTaskResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetNextTaskResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a CompleteTaskRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_CompleteTaskRequest(const CompleteTaskRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_CompleteTaskRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a CompleteTaskRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_CompleteTaskRequest(const uint8_t *in, size_t len, CompleteTaskRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_CompleteTaskRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a CompleteTaskResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_CompleteTaskResponse(const CompleteTaskResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_CompleteTaskResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a CompleteTaskResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_CompleteTaskResponse(const uint8_t *in, size_t len, CompleteTaskResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_CompleteTaskResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a UpdateTaskRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_UpdateTaskRequest(const UpdateTaskRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_UpdateTaskRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a UpdateTaskRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_UpdateTaskRequest(const uint8_t *in, size_t len, UpdateTaskRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_UpdateTaskRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a UpdateTaskResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_UpdateTaskResponse(const UpdateTaskResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_UpdateTaskResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a UpdateTaskResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_UpdateTaskResponse(const uint8_t *in, size_t len, UpdateTaskResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_UpdateTaskResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a CancelTaskRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_CancelTaskRequest(const CancelTaskRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_CancelTaskRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a CancelTaskRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_CancelTaskRequest(const uint8_t *in, size_t len, CancelTaskRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_CancelTaskRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a CancelTaskResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_CancelTaskResponse(const CancelTaskResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_CancelTaskResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a CancelTaskResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_CancelTaskResponse(const uint8_t *in, size_t len, CancelTaskResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_CancelTaskResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a CleanUpTimedOutRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_CleanUpTimedOutRequest(const CleanUpTimedOutRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_CleanUpTimedOutRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a CleanUpTimedOutRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_CleanUpTimedOutRequest(const uint8_t *in, size_t len, CleanUpTimedOutRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_CleanUpTimedOutRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a CleanUpTimedOutResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_CleanUpTimedOutResponse(const CleanUpTimedOutResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_CleanUpTimedOutResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a CleanUpTimedOutResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_CleanUpTimedOutResponse(const uint8_t *in, size_t len, CleanUpTimedOutResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_CleanUpTimedOutResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetQueuesRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetQueuesRequest(const GetQueuesRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetQueuesRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetQueuesRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetQueuesRequest(const uint8_t *in, size_t len, GetQueuesRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetQueuesRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetQueuesResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetQueuesResponse(const GetQueuesResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetQueuesResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetQueuesResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetQueuesResponse(const uint8_t *in, size_t len, GetQueuesResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetQueuesResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetQueueTaskCountsRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetQueueTaskCountsRequest(const GetQueueTaskCountsRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetQueueTaskCountsRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetQueueTaskCountsRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetQueueTaskCountsRequest(const uint8_t *in, size_t len, GetQueueTaskCountsRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetQueueTaskCountsRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetQueueTaskCountsResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetQueueTaskCountsResponse(const GetQueueTaskCountsResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetQueueTaskCountsResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetQueueTaskCountsResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetQueueTaskCountsResponse(const uint8_t *in, size_t len, GetQueueTaskCountsResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetQueueTaskCountsResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetTaskStateCountsRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetTaskStateCountsRequest(const GetTaskStateCountsRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetTaskStateCountsRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetTaskStateCountsRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetTaskStateCountsRequest(const uint8_t *in, size_t len, GetTaskStateCountsRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetTaskStateCountsRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetTaskStateCountsResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetTaskStateCountsResponse(const GetTaskStateCountsResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetTaskStateCountsResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetTaskStateCountsResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetTaskStateCountsResponse(const uint8_t *in, size_t len, GetTaskStateCountsResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetTaskStateCountsResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a QueueAndStateCounts to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_QueueAndStateCounts(const QueueAndStateCounts *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_QueueAndStateCounts(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a QueueAndStateCounts. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_QueueAndStateCounts(const uint8_t *in, size_t len, QueueAndStateCounts *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_QueueAndStateCounts(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a QueueAndStateCountsMap to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_QueueAndStateCountsMap(const QueueAndStateCountsMap *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_QueueAndStateCountsMap(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a QueueAndStateCountsMap. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_QueueAndStateCountsMap(const uint8_t *in, size_t len, QueueAndStateCountsMap *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_QueueAndStateCountsMap(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetQueueAndStateCountsRequest to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetQueueAndStateCountsRequest(const GetQueueAndStateCountsRequest *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetQueueAndStateCountsRequest(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetQueueAndStateCountsRequest. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetQueueAndStateCountsRequest(const uint8_t *in, size_t len, GetQueueAndStateCountsRequest *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetQueueAndStateCountsRequest(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a GetQueueAndStateCountsResponse to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_GetQueueAndStateCountsResponse(const GetQueueAndStateCountsResponse *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_GetQueueAndStateCountsResponse(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a GetQueueAndStateCountsResponse. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_GetQueueAndStateCountsResponse(const uint8_t *in, size_t len, GetQueueAndStateCountsResponse *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_GetQueueAndStateCountsResponse(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

/* Encode a ServiceError to CBOR. On success *out is a malloc'd buffer of
 * *out_len bytes the caller frees with free(); returns non-zero on failure. */
static inline int csil_encode_ServiceError(const ServiceError *v, uint8_t **out, size_t *out_len) {
    csilc_buf b;
    csilc_buf_init(&b);
    if (csilc_enc_ServiceError(&b, v)) { csilc_buf_dispose(&b); return -1; }
    *out = b.data;
    *out_len = b.len;
    return 0;
}

/* Decode CBOR into a ServiceError. On success *owner holds the backing
 * storage (every string/bytes/array inside *out borrows from it); free it
 * once with csil_codec_arena_free when done. Returns non-zero on failure. */
static inline int csil_decode_ServiceError(const uint8_t *in, size_t len, ServiceError *out, CsilCodecArena **owner) {
    CsilCodecArena *a;
    const csilc_value *root;
    if (csilc_decode(in, len, &a, &root)) return -1;
    if (csilc_dec_ServiceError(root, a, out)) { csil_codec_arena_free(a); return -1; }
    *owner = a;
    return 0;
}

#endif /* CSILGEN_CODEC_GEN_H */
