# frozen_string_literal: true

# Code generated by csilgen; DO NOT EDIT.

require_relative "codec"

# Each generated client owns (de)serialization via the generated CBOR codec and
# delegates only byte movement to a host-supplied transport seam: a duck-typed
# object responding to `call(service, op, req_bytes) -> resp_bytes`. The carrier
# moves bytes (HTTP, a queue, an in-process loop); it never sees the typed values.

# Typed client for the CorndogsService service.
class CorndogsClient
  def initialize(transport)
    @transport = transport
  end

  # SubmitTask: -> SubmitTaskResponse
  def submit_task(req)
    SubmitTaskResponse.from_cbor(@transport.call("corndogs", "SubmitTask", req.to_cbor))
  end

  # GetTaskStateByID: -> GetTaskStateByIdResponse
  def get_task_state_by_id(req)
    GetTaskStateByIdResponse.from_cbor(@transport.call("corndogs", "GetTaskStateByID", req.to_cbor))
  end

  # GetNextTask: -> GetNextTaskResponse
  def get_next_task(req)
    GetNextTaskResponse.from_cbor(@transport.call("corndogs", "GetNextTask", req.to_cbor))
  end

  # UpdateTask: -> UpdateTaskResponse
  def update_task(req)
    UpdateTaskResponse.from_cbor(@transport.call("corndogs", "UpdateTask", req.to_cbor))
  end

  # CompleteTask: -> CompleteTaskResponse
  def complete_task(req)
    CompleteTaskResponse.from_cbor(@transport.call("corndogs", "CompleteTask", req.to_cbor))
  end

  # CancelTask: -> CancelTaskResponse
  def cancel_task(req)
    CancelTaskResponse.from_cbor(@transport.call("corndogs", "CancelTask", req.to_cbor))
  end

  # CleanUpTimedOut: -> CleanUpTimedOutResponse
  def clean_up_timed_out(req)
    CleanUpTimedOutResponse.from_cbor(@transport.call("corndogs", "CleanUpTimedOut", req.to_cbor))
  end

  # GetQueues: -> GetQueuesResponse
  def get_queues(req)
    GetQueuesResponse.from_cbor(@transport.call("corndogs", "GetQueues", req.to_cbor))
  end

  # GetQueueTaskCounts: -> GetQueueTaskCountsResponse
  def get_queue_task_counts(req)
    GetQueueTaskCountsResponse.from_cbor(@transport.call("corndogs", "GetQueueTaskCounts", req.to_cbor))
  end

  # GetTaskStateCounts: -> GetTaskStateCountsResponse
  def get_task_state_counts(req)
    GetTaskStateCountsResponse.from_cbor(@transport.call("corndogs", "GetTaskStateCounts", req.to_cbor))
  end

  # GetQueueAndStateCounts: -> GetQueueAndStateCountsResponse
  def get_queue_and_state_counts(req)
    GetQueueAndStateCountsResponse.from_cbor(@transport.call("corndogs", "GetQueueAndStateCounts", req.to_cbor))
  end
end
