# frozen_string_literal: true

# Code generated by csilgen; DO NOT EDIT.

require_relative "codec"

# Each generated client owns (de)serialization via the generated CBOR codec and
# delegates only byte movement to a host-supplied transport seam: a duck-typed
# object responding to `call(service, op, req_bytes) -> resp_bytes`. The carrier
# moves bytes (HTTP, a queue, an in-process loop); it never sees the typed values.

# Typed client for the CorndogsService service.
class CorndogsClient
  def initialize(transport)
    @transport = transport
  end

  # SubmitTask: -> SubmitTaskResponse
  def submit_task(req)
    SubmitTaskResponse.from_cbor(@transport.call("CorndogsService", "SubmitTask", req.to_cbor))
  end

  # GetTaskStateByID: -> GetTaskStateByIdResponse
  def get_task_state_by_id(req)
    GetTaskStateByIdResponse.from_cbor(@transport.call("CorndogsService", "GetTaskStateByID", req.to_cbor))
  end

  # GetNextTask: -> GetNextTaskResponse
  def get_next_task(req)
    GetNextTaskResponse.from_cbor(@transport.call("CorndogsService", "GetNextTask", req.to_cbor))
  end

  # GetNextTaskGroup: -> GetNextTaskGroupResponse
  def get_next_task_group(req)
    GetNextTaskGroupResponse.from_cbor(@transport.call("CorndogsService", "GetNextTaskGroup", req.to_cbor))
  end

  # UpdateTask: -> UpdateTaskResponse
  def update_task(req)
    UpdateTaskResponse.from_cbor(@transport.call("CorndogsService", "UpdateTask", req.to_cbor))
  end

  # CompleteTask: -> CompleteTaskResponse
  def complete_task(req)
    CompleteTaskResponse.from_cbor(@transport.call("CorndogsService", "CompleteTask", req.to_cbor))
  end

  # CancelTask: -> CancelTaskResponse
  def cancel_task(req)
    CancelTaskResponse.from_cbor(@transport.call("CorndogsService", "CancelTask", req.to_cbor))
  end

  # CleanUpTimedOut: -> CleanUpTimedOutResponse
  def clean_up_timed_out(req)
    CleanUpTimedOutResponse.from_cbor(@transport.call("CorndogsService", "CleanUpTimedOut", req.to_cbor))
  end

  # GetQueues: -> GetQueuesResponse
  def get_queues(req)
    GetQueuesResponse.from_cbor(@transport.call("CorndogsService", "GetQueues", req.to_cbor))
  end

  # GetQueueTaskCounts: -> GetQueueTaskCountsResponse
  def get_queue_task_counts(req)
    GetQueueTaskCountsResponse.from_cbor(@transport.call("CorndogsService", "GetQueueTaskCounts", req.to_cbor))
  end

  # GetTaskStateCounts: -> GetTaskStateCountsResponse
  def get_task_state_counts(req)
    GetTaskStateCountsResponse.from_cbor(@transport.call("CorndogsService", "GetTaskStateCounts", req.to_cbor))
  end

  # GetQueueAndStateCounts: -> GetQueueAndStateCountsResponse
  def get_queue_and_state_counts(req)
    GetQueueAndStateCountsResponse.from_cbor(@transport.call("CorndogsService", "GetQueueAndStateCounts", req.to_cbor))
  end

  # GetServerInfo: -> GetServerInfoResponse
  def get_server_info(req)
    GetServerInfoResponse.from_cbor(@transport.call("CorndogsService", "GetServerInfo", req.to_cbor))
  end

  # SubmitKeyedTask: -> SubmitKeyedTaskResponse
  def submit_keyed_task(req)
    SubmitKeyedTaskResponse.from_cbor(@transport.call("CorndogsService", "SubmitKeyedTask", req.to_cbor))
  end

  # LookupSubmission: -> LookupSubmissionResponse
  def lookup_submission(req)
    LookupSubmissionResponse.from_cbor(@transport.call("CorndogsService", "LookupSubmission", req.to_cbor))
  end

  # ClaimGuardedTask: -> ClaimGuardedTaskResponse
  def claim_guarded_task(req)
    ClaimGuardedTaskResponse.from_cbor(@transport.call("CorndogsService", "ClaimGuardedTask", req.to_cbor))
  end

  # ClaimGuardedTaskGroup: -> ClaimGuardedTaskGroupResponse
  def claim_guarded_task_group(req)
    ClaimGuardedTaskGroupResponse.from_cbor(@transport.call("CorndogsService", "ClaimGuardedTaskGroup", req.to_cbor))
  end

  # UpdateGuardedTask: -> UpdateGuardedTaskResponse
  def update_guarded_task(req)
    UpdateGuardedTaskResponse.from_cbor(@transport.call("CorndogsService", "UpdateGuardedTask", req.to_cbor))
  end

  # CompleteGuardedTask: -> CompleteGuardedTaskResponse
  def complete_guarded_task(req)
    CompleteGuardedTaskResponse.from_cbor(@transport.call("CorndogsService", "CompleteGuardedTask", req.to_cbor))
  end

  # CancelGuardedTask: -> CancelGuardedTaskResponse
  def cancel_guarded_task(req)
    CancelGuardedTaskResponse.from_cbor(@transport.call("CorndogsService", "CancelGuardedTask", req.to_cbor))
  end

  # GetGuardedTask: -> GetGuardedTaskResponse
  def get_guarded_task(req)
    GetGuardedTaskResponse.from_cbor(@transport.call("CorndogsService", "GetGuardedTask", req.to_cbor))
  end

  # LookupOperation: -> LookupOperationResponse
  def lookup_operation(req)
    LookupOperationResponse.from_cbor(@transport.call("CorndogsService", "LookupOperation", req.to_cbor))
  end
end
