# frozen_string_literal: true

# Code generated by csilgen; DO NOT EDIT.

# Server-side handlers for the CorndogsService service. Subclass and override each
# operation; the unimplemented base raises NotImplementedError.
class CorndogsHandlers
  # SubmitTask
  def submit_task(req)
    raise NotImplementedError, "CorndogsHandlers#submit_task"
  end

  # GetTaskStateByID
  def get_task_state_by_id(req)
    raise NotImplementedError, "CorndogsHandlers#get_task_state_by_id"
  end

  # GetNextTask
  def get_next_task(req)
    raise NotImplementedError, "CorndogsHandlers#get_next_task"
  end

  # UpdateTask
  def update_task(req)
    raise NotImplementedError, "CorndogsHandlers#update_task"
  end

  # CompleteTask
  def complete_task(req)
    raise NotImplementedError, "CorndogsHandlers#complete_task"
  end

  # CancelTask
  def cancel_task(req)
    raise NotImplementedError, "CorndogsHandlers#cancel_task"
  end

  # CleanUpTimedOut
  def clean_up_timed_out(req)
    raise NotImplementedError, "CorndogsHandlers#clean_up_timed_out"
  end

  # GetQueues
  def get_queues(req)
    raise NotImplementedError, "CorndogsHandlers#get_queues"
  end

  # GetQueueTaskCounts
  def get_queue_task_counts(req)
    raise NotImplementedError, "CorndogsHandlers#get_queue_task_counts"
  end

  # GetTaskStateCounts
  def get_task_state_counts(req)
    raise NotImplementedError, "CorndogsHandlers#get_task_state_counts"
  end

  # GetQueueAndStateCounts
  def get_queue_and_state_counts(req)
    raise NotImplementedError, "CorndogsHandlers#get_queue_and_state_counts"
  end
end
