# frozen_string_literal: true

# Code generated by csilgen; DO NOT EDIT.

# Server-side handlers for the CorndogsService service. Subclass and override each
# operation; the unimplemented base raises NotImplementedError.
class CorndogsHandlers
  # SubmitTask
  def submit_task(req)
    raise NotImplementedError, "CorndogsHandlers#submit_task"
  end

  # GetTaskStateByID
  def get_task_state_by_id(req)
    raise NotImplementedError, "CorndogsHandlers#get_task_state_by_id"
  end

  # GetNextTask
  def get_next_task(req)
    raise NotImplementedError, "CorndogsHandlers#get_next_task"
  end

  # GetNextTaskGroup
  def get_next_task_group(req)
    raise NotImplementedError, "CorndogsHandlers#get_next_task_group"
  end

  # UpdateTask
  def update_task(req)
    raise NotImplementedError, "CorndogsHandlers#update_task"
  end

  # CompleteTask
  def complete_task(req)
    raise NotImplementedError, "CorndogsHandlers#complete_task"
  end

  # CancelTask
  def cancel_task(req)
    raise NotImplementedError, "CorndogsHandlers#cancel_task"
  end

  # CleanUpTimedOut
  def clean_up_timed_out(req)
    raise NotImplementedError, "CorndogsHandlers#clean_up_timed_out"
  end

  # GetQueues
  def get_queues(req)
    raise NotImplementedError, "CorndogsHandlers#get_queues"
  end

  # GetQueueTaskCounts
  def get_queue_task_counts(req)
    raise NotImplementedError, "CorndogsHandlers#get_queue_task_counts"
  end

  # GetTaskStateCounts
  def get_task_state_counts(req)
    raise NotImplementedError, "CorndogsHandlers#get_task_state_counts"
  end

  # GetQueueAndStateCounts
  def get_queue_and_state_counts(req)
    raise NotImplementedError, "CorndogsHandlers#get_queue_and_state_counts"
  end

  # GetServerInfo
  def get_server_info(req)
    raise NotImplementedError, "CorndogsHandlers#get_server_info"
  end

  # SubmitKeyedTask
  def submit_keyed_task(req)
    raise NotImplementedError, "CorndogsHandlers#submit_keyed_task"
  end

  # LookupSubmission
  def lookup_submission(req)
    raise NotImplementedError, "CorndogsHandlers#lookup_submission"
  end

  # ClaimGuardedTask
  def claim_guarded_task(req)
    raise NotImplementedError, "CorndogsHandlers#claim_guarded_task"
  end

  # ClaimGuardedTaskGroup
  def claim_guarded_task_group(req)
    raise NotImplementedError, "CorndogsHandlers#claim_guarded_task_group"
  end

  # UpdateGuardedTask
  def update_guarded_task(req)
    raise NotImplementedError, "CorndogsHandlers#update_guarded_task"
  end

  # CompleteGuardedTask
  def complete_guarded_task(req)
    raise NotImplementedError, "CorndogsHandlers#complete_guarded_task"
  end

  # CancelGuardedTask
  def cancel_guarded_task(req)
    raise NotImplementedError, "CorndogsHandlers#cancel_guarded_task"
  end

  # GetGuardedTask
  def get_guarded_task(req)
    raise NotImplementedError, "CorndogsHandlers#get_guarded_task"
  end

  # LookupOperation
  def lookup_operation(req)
    raise NotImplementedError, "CorndogsHandlers#lookup_operation"
  end
end
