# frozen_string_literal: true

# Code generated by csilgen; DO NOT EDIT.

# StringInt64Map is an alias for Hash<String, Integer>.

# A task as returned by the service. Response-only shape.
# uuid [String]
# queue [String]
# current_state [String]
# auto_target_state [String]
# submit_time [Integer]
# update_time [Integer]
# timeout [Integer]
# payload [String]
# priority [Integer]
Task = Data.define(:uuid, :queue, :current_state, :auto_target_state, :submit_time, :update_time, :timeout, :payload, :priority)

# queue [String]
# current_state [String]
# auto_target_state [String]
# timeout [Integer]
# payload [String]
# priority [Integer]
SubmitTaskRequest = Data.define(:queue, :current_state, :auto_target_state, :timeout, :payload, :priority)

# task [Task]
SubmitTaskResponse = Data.define(:task) do
  def initialize(task: nil)
    super
  end
end

# uuid [String]
# queue [String]
GetTaskStateByIdRequest = Data.define(:uuid, :queue)

# task [Task]
GetTaskStateByIdResponse = Data.define(:task) do
  def initialize(task: nil)
    super
  end
end

# queue [String]
# current_state [String]
# override_timeout [Integer]
# override_current_state [String]
# override_auto_target_state [String]
GetNextTaskRequest = Data.define(:queue, :current_state, :override_timeout, :override_current_state, :override_auto_target_state)

# task [Task]
GetNextTaskResponse = Data.define(:task) do
  def initialize(task: nil)
    super
  end
end

# uuid [String]
# queue [String]
# current_state [String]
CompleteTaskRequest = Data.define(:uuid, :queue, :current_state)

# task [Task]
CompleteTaskResponse = Data.define(:task) do
  def initialize(task: nil)
    super
  end
end

# uuid [String]
# queue [String]
# current_state [String]
# auto_target_state [String]
# timeout [Integer]
# new_state [String]
# payload [String]
# priority [Integer]
UpdateTaskRequest = Data.define(:uuid, :queue, :current_state, :auto_target_state, :timeout, :new_state, :payload, :priority)

# task [Task]
UpdateTaskResponse = Data.define(:task) do
  def initialize(task: nil)
    super
  end
end

# uuid [String]
# queue [String]
# current_state [String]
CancelTaskRequest = Data.define(:uuid, :queue, :current_state)

# task [Task]
CancelTaskResponse = Data.define(:task) do
  def initialize(task: nil)
    super
  end
end

# at_time [Integer]
# queue [String]
CleanUpTimedOutRequest = Data.define(:at_time, :queue)

# timed_out [Integer]
CleanUpTimedOutResponse = Data.define(:timed_out)

GetQueuesRequest = Data.define

# queues [Array<String>]
# total_task_count [Integer]
GetQueuesResponse = Data.define(:queues, :total_task_count)

GetQueueTaskCountsRequest = Data.define

# queue_counts [StringInt64Map]
# total_task_count [Integer]
GetQueueTaskCountsResponse = Data.define(:queue_counts, :total_task_count)

# queue [String]
GetTaskStateCountsRequest = Data.define(:queue)

# queue [String]
# count [Integer]
# state_counts [StringInt64Map]
GetTaskStateCountsResponse = Data.define(:queue, :count, :state_counts)

# queue [String]
# count [Integer]
# state_counts [StringInt64Map]
QueueAndStateCounts = Data.define(:queue, :count, :state_counts)

# QueueAndStateCountsMap is an alias for Hash<String, QueueAndStateCounts>.

GetQueueAndStateCountsRequest = Data.define

# queue_and_state_counts [QueueAndStateCountsMap]
GetQueueAndStateCountsResponse = Data.define(:queue_and_state_counts)

# code [Integer]
# message [String]
ServiceError = Data.define(:code, :message)
