// Package corndogs contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package corndogs

import (
	"context"
)

// CorndogsService defines the service interface
type CorndogsService interface {
	SubmitTask(ctx context.Context, req SubmitTaskRequest) (SubmitTaskResponse, error)
	GetTaskStateByID(ctx context.Context, req GetTaskStateByIDRequest) (GetTaskStateByIDResponse, error)
	GetNextTask(ctx context.Context, req GetNextTaskRequest) (GetNextTaskResponse, error)
	GetNextTaskGroup(ctx context.Context, req GetNextTaskGroupRequest) (GetNextTaskGroupResponse, error)
	UpdateTask(ctx context.Context, req UpdateTaskRequest) (UpdateTaskResponse, error)
	CompleteTask(ctx context.Context, req CompleteTaskRequest) (CompleteTaskResponse, error)
	CancelTask(ctx context.Context, req CancelTaskRequest) (CancelTaskResponse, error)
	CleanUpTimedOut(ctx context.Context, req CleanUpTimedOutRequest) (CleanUpTimedOutResponse, error)
	GetQueues(ctx context.Context, req GetQueuesRequest) (GetQueuesResponse, error)
	GetQueueTaskCounts(ctx context.Context, req GetQueueTaskCountsRequest) (GetQueueTaskCountsResponse, error)
	GetTaskStateCounts(ctx context.Context, req GetTaskStateCountsRequest) (GetTaskStateCountsResponse, error)
	GetQueueAndStateCounts(ctx context.Context, req GetQueueAndStateCountsRequest) (GetQueueAndStateCountsResponse, error)
	GetServerInfo(ctx context.Context, req GetServerInfoRequest) (GetServerInfoResponse, error)
	SubmitKeyedTask(ctx context.Context, req SubmitKeyedTaskRequest) (SubmitKeyedTaskResponse, error)
	LookupSubmission(ctx context.Context, req LookupSubmissionRequest) (LookupSubmissionResponse, error)
	ClaimGuardedTask(ctx context.Context, req ClaimGuardedTaskRequest) (ClaimGuardedTaskResponse, error)
	ClaimGuardedTaskGroup(ctx context.Context, req ClaimGuardedTaskGroupRequest) (ClaimGuardedTaskGroupResponse, error)
	UpdateGuardedTask(ctx context.Context, req UpdateGuardedTaskRequest) (UpdateGuardedTaskResponse, error)
	CompleteGuardedTask(ctx context.Context, req CompleteGuardedTaskRequest) (CompleteGuardedTaskResponse, error)
	CancelGuardedTask(ctx context.Context, req CancelGuardedTaskRequest) (CancelGuardedTaskResponse, error)
	GetGuardedTask(ctx context.Context, req GetGuardedTaskRequest) (GetGuardedTaskResponse, error)
	LookupOperation(ctx context.Context, req LookupOperationRequest) (LookupOperationResponse, error)
}
