// Generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.

import 'csil_cbor.gen.dart';
import 'types.gen.dart';

/// The carrier seam a generated client delegates to. The generated client owns
/// (de)serialization — it encodes the typed request to CBOR and decodes the typed
/// response — so the carrier only moves bytes for the named (service, op).
abstract interface class CsilTransport {
  /// Perform the (service, op) call with the already-encoded request bytes and
  /// return the response bytes.
  List<int> call(String service, String op, List<int> request);
}

/// A typed, transport-agnostic client for the CorndogsService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class CorndogsClient {
  final CsilTransport transport;
  const CorndogsClient(this.transport);

  SubmitTaskResponse submitTask(SubmitTaskRequest request) {
    final csilResp = transport.call('corndogs', 'SubmitTask', request.toCbor());
    return SubmitTaskResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  GetTaskStateByIdResponse getTaskStateById(GetTaskStateByIdRequest request) {
    final csilResp = transport.call('corndogs', 'GetTaskStateByID', request.toCbor());
    return GetTaskStateByIdResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  GetNextTaskResponse getNextTask(GetNextTaskRequest request) {
    final csilResp = transport.call('corndogs', 'GetNextTask', request.toCbor());
    return GetNextTaskResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  UpdateTaskResponse updateTask(UpdateTaskRequest request) {
    final csilResp = transport.call('corndogs', 'UpdateTask', request.toCbor());
    return UpdateTaskResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  CompleteTaskResponse completeTask(CompleteTaskRequest request) {
    final csilResp = transport.call('corndogs', 'CompleteTask', request.toCbor());
    return CompleteTaskResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  CancelTaskResponse cancelTask(CancelTaskRequest request) {
    final csilResp = transport.call('corndogs', 'CancelTask', request.toCbor());
    return CancelTaskResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  CleanUpTimedOutResponse cleanUpTimedOut(CleanUpTimedOutRequest request) {
    final csilResp = transport.call('corndogs', 'CleanUpTimedOut', request.toCbor());
    return CleanUpTimedOutResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  GetQueuesResponse getQueues(GetQueuesRequest request) {
    final csilResp = transport.call('corndogs', 'GetQueues', request.toCbor());
    return GetQueuesResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  GetQueueTaskCountsResponse getQueueTaskCounts(GetQueueTaskCountsRequest request) {
    final csilResp = transport.call('corndogs', 'GetQueueTaskCounts', request.toCbor());
    return GetQueueTaskCountsResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  GetTaskStateCountsResponse getTaskStateCounts(GetTaskStateCountsRequest request) {
    final csilResp = transport.call('corndogs', 'GetTaskStateCounts', request.toCbor());
    return GetTaskStateCountsResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  GetQueueAndStateCountsResponse getQueueAndStateCounts(GetQueueAndStateCountsRequest request) {
    final csilResp = transport.call('corndogs', 'GetQueueAndStateCounts', request.toCbor());
    return GetQueueAndStateCountsResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

