// Generated service handlers and routers.
//
// Code generated by csilgen; DO NOT EDIT.

import 'types.gen.dart';

/// The (de)serialization seam the generated routers use. The host wires this to
/// `csilgen_transport`'s CBOR codec or anything else its protocol expects; the
/// router itself is codec-agnostic.
abstract interface class CsilCodec {
  List<int> encode(Object? value);
  Object? decode(List<int> data);
}

/// The CorndogsService service contract. A host `implements` this; the router
/// dispatches decoded requests/messages to it.
abstract interface class CorndogsServiceHandler {
  SubmitTaskResponse submitTask(SubmitTaskRequest request);
  GetTaskStateByIdResponse getTaskStateById(GetTaskStateByIdRequest request);
  GetNextTaskResponse getNextTask(GetNextTaskRequest request);
  UpdateTaskResponse updateTask(UpdateTaskRequest request);
  CompleteTaskResponse completeTask(CompleteTaskRequest request);
  CancelTaskResponse cancelTask(CancelTaskRequest request);
  CleanUpTimedOutResponse cleanUpTimedOut(CleanUpTimedOutRequest request);
  GetQueuesResponse getQueues(GetQueuesRequest request);
  GetQueueTaskCountsResponse getQueueTaskCounts(GetQueueTaskCountsRequest request);
  GetTaskStateCountsResponse getTaskStateCounts(GetTaskStateCountsRequest request);
  GetQueueAndStateCountsResponse getQueueAndStateCounts(GetQueueAndStateCountsRequest request);
}

