// swift-tools-version:5.9
// corndogs 0.0.0 — generated by csilgen; DO NOT EDIT.
// SwiftPM derives a published version from the package's git tag, so the version
// above is informational only.
import PackageDescription

let package = Package(
name: "corndogs",
products: [
.library(name: "corndogs", targets: ["Corndogs"]),
],
targets: [
.target(name: "Corndogs"),
]
)
