// Generated typed RPC client call-sites.
// Code generated by csilgen; DO NOT EDIT.

const std = @import("std");
const types = @import("types.gen.zig");
const codec = @import("codec.gen.zig");

/// CsilgenTransport is the caller-supplied byte carrier: it performs the call named
/// by (service, op) with the already-encoded req bytes (CBOR over HTTP, say) and
/// returns the response bytes, allocated with `alloc` so the generated client frees
/// them. The generator owns serialization; the carrier only moves bytes.
pub const CsilgenTransport = struct {
    ptr: *anyopaque,
    call: *const fn (ptr: *anyopaque, alloc: std.mem.Allocator, service: []const u8, op: []const u8, req: []const u8) anyerror![]u8,
};

/// CorndogsClient is a typed client for the CorndogsService service over a CsilgenTransport.
pub const CorndogsClient = struct {
    transport: CsilgenTransport,

    pub fn init(transport: CsilgenTransport) CorndogsClient {
        return .{ .transport = transport };
    }

    /// Invoke CorndogsService/SubmitTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn submit_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.SubmitTaskRequest, out: *types.SubmitTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_SubmitTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "SubmitTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_SubmitTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetTaskStateByID with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_task_state_by_id(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetTaskStateByIDRequest, out: *types.GetTaskStateByIDResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetTaskStateByIDRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetTaskStateByID", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetTaskStateByIDResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetNextTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_next_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetNextTaskRequest, out: *types.GetNextTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetNextTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetNextTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetNextTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetNextTaskGroup with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_next_task_group(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetNextTaskGroupRequest, out: *types.GetNextTaskGroupResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetNextTaskGroupRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetNextTaskGroup", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetNextTaskGroupResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/UpdateTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn update_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.UpdateTaskRequest, out: *types.UpdateTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_UpdateTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "UpdateTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_UpdateTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/CompleteTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn complete_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CompleteTaskRequest, out: *types.CompleteTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_CompleteTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "CompleteTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CompleteTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/CancelTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn cancel_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CancelTaskRequest, out: *types.CancelTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_CancelTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "CancelTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CancelTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/CleanUpTimedOut with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn clean_up_timed_out(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CleanUpTimedOutRequest, out: *types.CleanUpTimedOutResponse) anyerror!void {
        const csil_reqb = try codec.encode_CleanUpTimedOutRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "CleanUpTimedOut", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CleanUpTimedOutResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetQueues with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_queues(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetQueuesRequest, out: *types.GetQueuesResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetQueuesRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetQueues", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetQueuesResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetQueueTaskCounts with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_queue_task_counts(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetQueueTaskCountsRequest, out: *types.GetQueueTaskCountsResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetQueueTaskCountsRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetQueueTaskCounts", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetQueueTaskCountsResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetTaskStateCounts with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_task_state_counts(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetTaskStateCountsRequest, out: *types.GetTaskStateCountsResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetTaskStateCountsRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetTaskStateCounts", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetTaskStateCountsResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetQueueAndStateCounts with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_queue_and_state_counts(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetQueueAndStateCountsRequest, out: *types.GetQueueAndStateCountsResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetQueueAndStateCountsRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetQueueAndStateCounts", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetQueueAndStateCountsResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetServerInfo with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_server_info(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetServerInfoRequest, out: *types.GetServerInfoResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetServerInfoRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetServerInfo", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetServerInfoResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/SubmitKeyedTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn submit_keyed_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.SubmitKeyedTaskRequest, out: *types.SubmitKeyedTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_SubmitKeyedTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "SubmitKeyedTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_SubmitKeyedTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/LookupSubmission with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn lookup_submission(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.LookupSubmissionRequest, out: *types.LookupSubmissionResponse) anyerror!void {
        const csil_reqb = try codec.encode_LookupSubmissionRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "LookupSubmission", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_LookupSubmissionResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/ClaimGuardedTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn claim_guarded_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.ClaimGuardedTaskRequest, out: *types.ClaimGuardedTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_ClaimGuardedTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "ClaimGuardedTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_ClaimGuardedTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/ClaimGuardedTaskGroup with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn claim_guarded_task_group(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.ClaimGuardedTaskGroupRequest, out: *types.ClaimGuardedTaskGroupResponse) anyerror!void {
        const csil_reqb = try codec.encode_ClaimGuardedTaskGroupRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "ClaimGuardedTaskGroup", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_ClaimGuardedTaskGroupResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/UpdateGuardedTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn update_guarded_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.UpdateGuardedTaskRequest, out: *types.UpdateGuardedTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_UpdateGuardedTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "UpdateGuardedTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_UpdateGuardedTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/CompleteGuardedTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn complete_guarded_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CompleteGuardedTaskRequest, out: *types.CompleteGuardedTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_CompleteGuardedTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "CompleteGuardedTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CompleteGuardedTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/CancelGuardedTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn cancel_guarded_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CancelGuardedTaskRequest, out: *types.CancelGuardedTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_CancelGuardedTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "CancelGuardedTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CancelGuardedTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/GetGuardedTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_guarded_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetGuardedTaskRequest, out: *types.GetGuardedTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetGuardedTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "GetGuardedTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetGuardedTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke CorndogsService/LookupOperation with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn lookup_operation(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.LookupOperationRequest, out: *types.LookupOperationResponse) anyerror!void {
        const csil_reqb = try codec.encode_LookupOperationRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "CorndogsService", "LookupOperation", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_LookupOperationResponse(alloc, csil_respb, out);
    }
};
