// Generated typed RPC client call-sites.
// Code generated by csilgen; DO NOT EDIT.

const std = @import("std");
const types = @import("types.gen.zig");
const codec = @import("codec.gen.zig");

/// CsilgenTransport is the caller-supplied byte carrier: it performs the call named
/// by (service, op) with the already-encoded req bytes (CBOR over HTTP, say) and
/// returns the response bytes, allocated with `alloc` so the generated client frees
/// them. The generator owns serialization; the carrier only moves bytes.
pub const CsilgenTransport = struct {
    ptr: *anyopaque,
    call: *const fn (ptr: *anyopaque, alloc: std.mem.Allocator, service: []const u8, op: []const u8, req: []const u8) anyerror![]u8,
};

/// CorndogsClient is a typed client for the CorndogsService service over a CsilgenTransport.
pub const CorndogsClient = struct {
    transport: CsilgenTransport,

    pub fn init(transport: CsilgenTransport) CorndogsClient {
        return .{ .transport = transport };
    }

    /// Invoke corndogs/SubmitTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn submit_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.SubmitTaskRequest, out: *types.SubmitTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_SubmitTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "SubmitTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_SubmitTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/GetTaskStateByID with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_task_state_by_id(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetTaskStateByIDRequest, out: *types.GetTaskStateByIDResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetTaskStateByIDRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "GetTaskStateByID", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetTaskStateByIDResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/GetNextTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_next_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetNextTaskRequest, out: *types.GetNextTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetNextTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "GetNextTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetNextTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/UpdateTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn update_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.UpdateTaskRequest, out: *types.UpdateTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_UpdateTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "UpdateTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_UpdateTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/CompleteTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn complete_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CompleteTaskRequest, out: *types.CompleteTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_CompleteTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "CompleteTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CompleteTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/CancelTask with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn cancel_task(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CancelTaskRequest, out: *types.CancelTaskResponse) anyerror!void {
        const csil_reqb = try codec.encode_CancelTaskRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "CancelTask", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CancelTaskResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/CleanUpTimedOut with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn clean_up_timed_out(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.CleanUpTimedOutRequest, out: *types.CleanUpTimedOutResponse) anyerror!void {
        const csil_reqb = try codec.encode_CleanUpTimedOutRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "CleanUpTimedOut", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_CleanUpTimedOutResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/GetQueues with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_queues(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetQueuesRequest, out: *types.GetQueuesResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetQueuesRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "GetQueues", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetQueuesResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/GetQueueTaskCounts with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_queue_task_counts(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetQueueTaskCountsRequest, out: *types.GetQueueTaskCountsResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetQueueTaskCountsRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "GetQueueTaskCounts", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetQueueTaskCountsResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/GetTaskStateCounts with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_task_state_counts(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetTaskStateCountsRequest, out: *types.GetTaskStateCountsResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetTaskStateCountsRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "GetTaskStateCounts", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetTaskStateCountsResponse(alloc, csil_respb, out);
    }

    /// Invoke corndogs/GetQueueAndStateCounts with a typed request, returning the decoded
    /// typed response. Everything in `out` is allocated from `alloc`; pass an arena
    /// and free it once when done.
    pub fn get_queue_and_state_counts(self: CorndogsClient, alloc: std.mem.Allocator, req: *const types.GetQueueAndStateCountsRequest, out: *types.GetQueueAndStateCountsResponse) anyerror!void {
        const csil_reqb = try codec.encode_GetQueueAndStateCountsRequest(alloc, req);
        defer alloc.free(csil_reqb);
        const csil_respb = try self.transport.call(self.transport.ptr, alloc, "corndogs", "GetQueueAndStateCounts", csil_reqb);
        defer alloc.free(csil_respb);
        try codec.decode_GetQueueAndStateCountsResponse(alloc, csil_respb, out);
    }
};
