// Generated service handler structs and routers.
// Code generated by csilgen; DO NOT EDIT.

const std = @import("std");
const types = @import("types.gen.zig");

/// CsilgenCodec is the consumer-supplied (de)serialization layer for channel
/// messages. The generator is codec-agnostic; the implementer wires this to
/// CBOR, JSON, or whatever its protocol expects. decode writes into out.
pub const CsilgenCodec = struct {
    ptr: *anyopaque,
    decode: *const fn (ptr: *anyopaque, data: []const u8, out: *anyopaque) anyerror!void,
    encode: *const fn (ptr: *anyopaque, value: *const anyopaque) anyerror![]u8,
};

/// CorndogsHandlers is the host's implementation of the CorndogsService service.
pub const CorndogsHandlers = struct {
    submit_task: *const fn (ctx: *anyopaque, req: *const types.SubmitTaskRequest, resp: *types.SubmitTaskResponse) anyerror!void,
    get_task_state_by_id: *const fn (ctx: *anyopaque, req: *const types.GetTaskStateByIDRequest, resp: *types.GetTaskStateByIDResponse) anyerror!void,
    get_next_task: *const fn (ctx: *anyopaque, req: *const types.GetNextTaskRequest, resp: *types.GetNextTaskResponse) anyerror!void,
    update_task: *const fn (ctx: *anyopaque, req: *const types.UpdateTaskRequest, resp: *types.UpdateTaskResponse) anyerror!void,
    complete_task: *const fn (ctx: *anyopaque, req: *const types.CompleteTaskRequest, resp: *types.CompleteTaskResponse) anyerror!void,
    cancel_task: *const fn (ctx: *anyopaque, req: *const types.CancelTaskRequest, resp: *types.CancelTaskResponse) anyerror!void,
    clean_up_timed_out: *const fn (ctx: *anyopaque, req: *const types.CleanUpTimedOutRequest, resp: *types.CleanUpTimedOutResponse) anyerror!void,
    get_queues: *const fn (ctx: *anyopaque, req: *const types.GetQueuesRequest, resp: *types.GetQueuesResponse) anyerror!void,
    get_queue_task_counts: *const fn (ctx: *anyopaque, req: *const types.GetQueueTaskCountsRequest, resp: *types.GetQueueTaskCountsResponse) anyerror!void,
    get_task_state_counts: *const fn (ctx: *anyopaque, req: *const types.GetTaskStateCountsRequest, resp: *types.GetTaskStateCountsResponse) anyerror!void,
    get_queue_and_state_counts: *const fn (ctx: *anyopaque, req: *const types.GetQueueAndStateCountsRequest, resp: *types.GetQueueAndStateCountsResponse) anyerror!void,
};
