// Generated CSIL value types.
// Code generated by csilgen; DO NOT EDIT.

const std = @import("std");

/// StringInt64Map is a type alias.
pub const StringInt64Map = std.StringHashMapUnmanaged(i64);

/// QueueAndStateCountsMap is a type alias.
pub const QueueAndStateCountsMap = std.StringHashMapUnmanaged(QueueAndStateCounts);

/// Task is a structured data type.
pub const Task = struct {
    uuid: []const u8,
    queue: []const u8,
    current_state: []const u8,
    auto_target_state: []const u8,
    submit_time: i64,
    update_time: i64,
    timeout: i64,
    payload: []const u8,
    priority: i64,
};

/// SubmitTaskRequest is a structured data type.
pub const SubmitTaskRequest = struct {
    queue: []const u8,
    current_state: []const u8,
    auto_target_state: []const u8,
    timeout: i64,
    payload: []const u8,
    priority: i64,
};

/// SubmitTaskResponse is a structured data type.
pub const SubmitTaskResponse = struct {
    task: ?Task = null,
};

/// GetTaskStateByIDRequest is a structured data type.
pub const GetTaskStateByIDRequest = struct {
    uuid: []const u8,
    queue: []const u8,
};

/// GetTaskStateByIDResponse is a structured data type.
pub const GetTaskStateByIDResponse = struct {
    task: ?Task = null,
};

/// GetNextTaskRequest is a structured data type.
pub const GetNextTaskRequest = struct {
    queue: []const u8,
    current_state: []const u8,
    override_timeout: i64,
    override_current_state: []const u8,
    override_auto_target_state: []const u8,
};

/// GetNextTaskResponse is a structured data type.
pub const GetNextTaskResponse = struct {
    task: ?Task = null,
};

/// CompleteTaskRequest is a structured data type.
pub const CompleteTaskRequest = struct {
    uuid: []const u8,
    queue: []const u8,
    current_state: []const u8,
};

/// CompleteTaskResponse is a structured data type.
pub const CompleteTaskResponse = struct {
    task: ?Task = null,
};

/// UpdateTaskRequest is a structured data type.
pub const UpdateTaskRequest = struct {
    uuid: []const u8,
    queue: []const u8,
    current_state: []const u8,
    auto_target_state: []const u8,
    timeout: i64,
    new_state: []const u8,
    payload: []const u8,
    priority: i64,
};

/// UpdateTaskResponse is a structured data type.
pub const UpdateTaskResponse = struct {
    task: ?Task = null,
};

/// CancelTaskRequest is a structured data type.
pub const CancelTaskRequest = struct {
    uuid: []const u8,
    queue: []const u8,
    current_state: []const u8,
};

/// CancelTaskResponse is a structured data type.
pub const CancelTaskResponse = struct {
    task: ?Task = null,
};

/// CleanUpTimedOutRequest is a structured data type.
pub const CleanUpTimedOutRequest = struct {
    at_time: i64,
    queue: []const u8,
};

/// CleanUpTimedOutResponse is a structured data type.
pub const CleanUpTimedOutResponse = struct {
    timed_out: i64,
};

/// GetQueuesRequest is a structured data type.
pub const GetQueuesRequest = struct {
};

/// GetQueuesResponse is a structured data type.
pub const GetQueuesResponse = struct {
    queues: [][]const u8,
    total_task_count: i64,
};

/// GetQueueTaskCountsRequest is a structured data type.
pub const GetQueueTaskCountsRequest = struct {
};

/// GetTaskStateCountsRequest is a structured data type.
pub const GetTaskStateCountsRequest = struct {
    queue: []const u8,
};

/// GetQueueAndStateCountsRequest is a structured data type.
pub const GetQueueAndStateCountsRequest = struct {
};

/// ServiceError is a structured data type.
pub const ServiceError = struct {
    code: u64,
    message: []const u8,
};

/// GetQueueTaskCountsResponse is a structured data type.
pub const GetQueueTaskCountsResponse = struct {
    queue_counts: StringInt64Map,
    total_task_count: i64,
};

/// GetTaskStateCountsResponse is a structured data type.
pub const GetTaskStateCountsResponse = struct {
    queue: []const u8,
    count: i64,
    state_counts: StringInt64Map,
};

/// QueueAndStateCounts is a structured data type.
pub const QueueAndStateCounts = struct {
    queue: []const u8,
    count: i64,
    state_counts: StringInt64Map,
};

/// GetQueueAndStateCountsResponse is a structured data type.
pub const GetQueueAndStateCountsResponse = struct {
    queue_and_state_counts: QueueAndStateCountsMap,
};
