(* Code generated by csilgen; DO NOT EDIT. *)

[@@@warning "-30"]

type string_int_64_map = (string * int64) list

and task = {
  uuid : string;
  queue : string;
  current_state : string;
  auto_target_state : string;
  submit_time : int64;
  update_time : int64;
  timeout : int64;
  payload : bytes;
  priority : int64;
}

and submit_task_request = {
  queue : string;
  current_state : string;
  auto_target_state : string;
  timeout : int64;
  payload : bytes;
  priority : int64;
}

and submit_task_response = { task : task option }
and get_task_state_by_id_request = { uuid : string; queue : string }
and get_task_state_by_id_response = { task : task option }

and get_next_task_request = {
  queue : string;
  current_state : string;
  override_timeout : int64;
  override_current_state : string;
  override_auto_target_state : string;
}

and get_next_task_response = { task : task option }

and complete_task_request = {
  uuid : string;
  queue : string;
  current_state : string;
}

and complete_task_response = { task : task option }

and update_task_request = {
  uuid : string;
  queue : string;
  current_state : string;
  auto_target_state : string;
  timeout : int64;
  new_state : string;
  payload : bytes;
  priority : int64;
}

and update_task_response = { task : task option }

and cancel_task_request = {
  uuid : string;
  queue : string;
  current_state : string;
}

and cancel_task_response = { task : task option }
and clean_up_timed_out_request = { at_time : int64; queue : string }
and clean_up_timed_out_response = { timed_out : int64 }
and get_queues_request = unit
and get_queues_response = { queues : string list; total_task_count : int64 }
and get_queue_task_counts_request = unit

and get_queue_task_counts_response = {
  queue_counts : string_int_64_map;
  total_task_count : int64;
}

and get_task_state_counts_request = { queue : string }

and get_task_state_counts_response = {
  queue : string;
  count : int64;
  state_counts : string_int_64_map;
}

and queue_and_state_counts = {
  queue : string;
  count : int64;
  state_counts : string_int_64_map;
}

and queue_and_state_counts_map = (string * queue_and_state_counts) list
and get_queue_and_state_counts_request = unit

and get_queue_and_state_counts_response = {
  queue_and_state_counts : queue_and_state_counts_map;
}

and service_error = { code : int64; message : string }
