// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-client

import type { CancelGuardedTaskRequest, CancelGuardedTaskResponse, CancelTaskRequest, CancelTaskResponse, ClaimGuardedTaskGroupRequest, ClaimGuardedTaskGroupResponse, ClaimGuardedTaskRequest, ClaimGuardedTaskResponse, CleanUpTimedOutRequest, CleanUpTimedOutResponse, CompleteGuardedTaskRequest, CompleteGuardedTaskResponse, CompleteTaskRequest, CompleteTaskResponse, GetGuardedTaskRequest, GetGuardedTaskResponse, GetNextTaskGroupRequest, GetNextTaskGroupResponse, GetNextTaskRequest, GetNextTaskResponse, GetQueueAndStateCountsRequest, GetQueueAndStateCountsResponse, GetQueueTaskCountsRequest, GetQueueTaskCountsResponse, GetQueuesRequest, GetQueuesResponse, GetServerInfoRequest, GetServerInfoResponse, GetTaskStateByIDRequest, GetTaskStateByIDResponse, GetTaskStateCountsRequest, GetTaskStateCountsResponse, LookupOperationRequest, LookupOperationResponse, LookupSubmissionRequest, LookupSubmissionResponse, SubmitKeyedTaskRequest, SubmitKeyedTaskResponse, SubmitTaskRequest, SubmitTaskResponse, UpdateGuardedTaskRequest, UpdateGuardedTaskResponse, UpdateTaskRequest, UpdateTaskResponse } from "./types.gen.ts";
import { fromCancelGuardedTaskResponseCbor, fromCancelTaskResponseCbor, fromClaimGuardedTaskGroupResponseCbor, fromClaimGuardedTaskResponseCbor, fromCleanUpTimedOutResponseCbor, fromCompleteGuardedTaskResponseCbor, fromCompleteTaskResponseCbor, fromGetGuardedTaskResponseCbor, fromGetNextTaskGroupResponseCbor, fromGetNextTaskResponseCbor, fromGetQueueAndStateCountsResponseCbor, fromGetQueueTaskCountsResponseCbor, fromGetQueuesResponseCbor, fromGetServerInfoResponseCbor, fromGetTaskStateByIDResponseCbor, fromGetTaskStateCountsResponseCbor, fromLookupOperationResponseCbor, fromLookupSubmissionResponseCbor, fromSubmitKeyedTaskResponseCbor, fromSubmitTaskResponseCbor, fromUpdateGuardedTaskResponseCbor, fromUpdateTaskResponseCbor, toCancelGuardedTaskRequestCbor, toCancelTaskRequestCbor, toClaimGuardedTaskGroupRequestCbor, toClaimGuardedTaskRequestCbor, toCleanUpTimedOutRequestCbor, toCompleteGuardedTaskRequestCbor, toCompleteTaskRequestCbor, toGetGuardedTaskRequestCbor, toGetNextTaskGroupRequestCbor, toGetNextTaskRequestCbor, toGetQueueAndStateCountsRequestCbor, toGetQueueTaskCountsRequestCbor, toGetQueuesRequestCbor, toGetServerInfoRequestCbor, toGetTaskStateByIDRequestCbor, toGetTaskStateCountsRequestCbor, toLookupOperationRequestCbor, toLookupSubmissionRequestCbor, toSubmitKeyedTaskRequestCbor, toSubmitTaskRequestCbor, toUpdateGuardedTaskRequestCbor, toUpdateTaskRequestCbor } from "./codec.gen.ts";

export interface AsyncServiceTransport {
  call(service: string, op: string, req: Uint8Array): Promise<Uint8Array>;
}

export class CorndogsAsyncClient {
  constructor(private readonly t: AsyncServiceTransport) {}

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async submitTask(req: SubmitTaskRequest): Promise<SubmitTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "SubmitTask", toSubmitTaskRequestCbor(req));
    return fromSubmitTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getTaskStateByID(req: GetTaskStateByIDRequest): Promise<GetTaskStateByIDResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetTaskStateByID", toGetTaskStateByIDRequestCbor(req));
    return fromGetTaskStateByIDResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getNextTask(req: GetNextTaskRequest): Promise<GetNextTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetNextTask", toGetNextTaskRequestCbor(req));
    return fromGetNextTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getNextTaskGroup(req: GetNextTaskGroupRequest): Promise<GetNextTaskGroupResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetNextTaskGroup", toGetNextTaskGroupRequestCbor(req));
    return fromGetNextTaskGroupResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async updateTask(req: UpdateTaskRequest): Promise<UpdateTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "UpdateTask", toUpdateTaskRequestCbor(req));
    return fromUpdateTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async completeTask(req: CompleteTaskRequest): Promise<CompleteTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "CompleteTask", toCompleteTaskRequestCbor(req));
    return fromCompleteTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async cancelTask(req: CancelTaskRequest): Promise<CancelTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "CancelTask", toCancelTaskRequestCbor(req));
    return fromCancelTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async cleanUpTimedOut(req: CleanUpTimedOutRequest): Promise<CleanUpTimedOutResponse> {
    const csilResp = await this.t.call("CorndogsService", "CleanUpTimedOut", toCleanUpTimedOutRequestCbor(req));
    return fromCleanUpTimedOutResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getQueues(req: GetQueuesRequest): Promise<GetQueuesResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetQueues", toGetQueuesRequestCbor(req));
    return fromGetQueuesResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getQueueTaskCounts(req: GetQueueTaskCountsRequest): Promise<GetQueueTaskCountsResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetQueueTaskCounts", toGetQueueTaskCountsRequestCbor(req));
    return fromGetQueueTaskCountsResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getTaskStateCounts(req: GetTaskStateCountsRequest): Promise<GetTaskStateCountsResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetTaskStateCounts", toGetTaskStateCountsRequestCbor(req));
    return fromGetTaskStateCountsResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getQueueAndStateCounts(req: GetQueueAndStateCountsRequest): Promise<GetQueueAndStateCountsResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetQueueAndStateCounts", toGetQueueAndStateCountsRequestCbor(req));
    return fromGetQueueAndStateCountsResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getServerInfo(req: GetServerInfoRequest): Promise<GetServerInfoResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetServerInfo", toGetServerInfoRequestCbor(req));
    return fromGetServerInfoResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async submitKeyedTask(req: SubmitKeyedTaskRequest): Promise<SubmitKeyedTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "SubmitKeyedTask", toSubmitKeyedTaskRequestCbor(req));
    return fromSubmitKeyedTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async lookupSubmission(req: LookupSubmissionRequest): Promise<LookupSubmissionResponse> {
    const csilResp = await this.t.call("CorndogsService", "LookupSubmission", toLookupSubmissionRequestCbor(req));
    return fromLookupSubmissionResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async claimGuardedTask(req: ClaimGuardedTaskRequest): Promise<ClaimGuardedTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "ClaimGuardedTask", toClaimGuardedTaskRequestCbor(req));
    return fromClaimGuardedTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async claimGuardedTaskGroup(req: ClaimGuardedTaskGroupRequest): Promise<ClaimGuardedTaskGroupResponse> {
    const csilResp = await this.t.call("CorndogsService", "ClaimGuardedTaskGroup", toClaimGuardedTaskGroupRequestCbor(req));
    return fromClaimGuardedTaskGroupResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async updateGuardedTask(req: UpdateGuardedTaskRequest): Promise<UpdateGuardedTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "UpdateGuardedTask", toUpdateGuardedTaskRequestCbor(req));
    return fromUpdateGuardedTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async completeGuardedTask(req: CompleteGuardedTaskRequest): Promise<CompleteGuardedTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "CompleteGuardedTask", toCompleteGuardedTaskRequestCbor(req));
    return fromCompleteGuardedTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async cancelGuardedTask(req: CancelGuardedTaskRequest): Promise<CancelGuardedTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "CancelGuardedTask", toCancelGuardedTaskRequestCbor(req));
    return fromCancelGuardedTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async getGuardedTask(req: GetGuardedTaskRequest): Promise<GetGuardedTaskResponse> {
    const csilResp = await this.t.call("CorndogsService", "GetGuardedTask", toGetGuardedTaskRequestCbor(req));
    return fromGetGuardedTaskResponseCbor(csilResp);
  }

  /**
   * @throws {ServiceError} when the API returns an error response
   * @throws transport errors (network, timeout) raised by the transport
   */
  async lookupOperation(req: LookupOperationRequest): Promise<LookupOperationResponse> {
    const csilResp = await this.t.call("CorndogsService", "LookupOperation", toLookupOperationRequestCbor(req));
    return fromLookupOperationResponseCbor(csilResp);
  }
}

export class AsyncApiClient {
  readonly corndogs: CorndogsAsyncClient;
  constructor(t: AsyncServiceTransport) {
    this.corndogs = new CorndogsAsyncClient(t);
  }
}
