// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-codec

import type { CancelGuardedTaskRequest, CancelGuardedTaskResponse, CancelTaskRequest, CancelTaskResponse, ClaimGuardedTaskGroupRequest, ClaimGuardedTaskGroupResponse, ClaimGuardedTaskRequest, ClaimGuardedTaskResponse, CleanUpTimedOutRequest, CleanUpTimedOutResponse, CompleteGuardedTaskRequest, CompleteGuardedTaskResponse, CompleteTaskRequest, CompleteTaskResponse, GetGuardedTaskRequest, GetGuardedTaskResponse, GetNextTaskGroupRequest, GetNextTaskGroupResponse, GetNextTaskRequest, GetNextTaskResponse, GetQueueAndStateCountsRequest, GetQueueAndStateCountsResponse, GetQueueTaskCountsRequest, GetQueueTaskCountsResponse, GetQueuesRequest, GetQueuesResponse, GetServerInfoRequest, GetServerInfoResponse, GetTaskStateByIDRequest, GetTaskStateByIDResponse, GetTaskStateCountsRequest, GetTaskStateCountsResponse, GuardedDelivery, GuardedTask, LookupOperationRequest, LookupOperationResponse, LookupSubmissionRequest, LookupSubmissionResponse, OperationReceipt, QueueAndStateCounts, QueueAndStateCountsMap, ServiceError, StringInt64Map, SubmissionReceipt, SubmitKeyedTaskRequest, SubmitKeyedTaskResponse, SubmitTaskRequest, SubmitTaskResponse, Task, TaskDelivery, UpdateGuardedTaskRequest, UpdateGuardedTaskResponse, UpdateTaskRequest, UpdateTaskResponse } from "./types.gen.ts";

/** A CBOR semantic tag wrapping an inner value (e.g. tag 0 timestamp, tag 4 decimal). */
export type CborTag = { readonly tag: number; readonly value: CborValue };

/** A minimal canonical-CBOR value tree: a closed set of node variants. */
export type CborValue =
  | number
  | bigint
  | boolean
  | null
  | string
  | Uint8Array
  | CborValue[]
  | Map<CborValue, CborValue>
  | CborTag;

const csilTextEncoder = new TextEncoder();
const csilTextDecoder = new TextDecoder("utf-8", { fatal: true });

function head(major: number, n: number | bigint, out: number[]): void {
  const mt = major << 5;
  const big = typeof n === "bigint" ? n : BigInt(n);
  if (big < 24n) {
    out.push(mt | Number(big));
  } else if (big < 0x100n) {
    out.push(mt | 24, Number(big) & 0xff);
  } else if (big < 0x10000n) {
    out.push(mt | 25, Number((big >> 8n) & 0xffn), Number(big & 0xffn));
  } else if (big < 0x100000000n) {
    out.push(mt | 26);
    for (let s = 24n; s >= 0n; s -= 8n) out.push(Number((big >> s) & 0xffn));
  } else {
    out.push(mt | 27);
    for (let s = 56n; s >= 0n; s -= 8n) out.push(Number((big >> s) & 0xffn));
  }
}

function encInt(n: bigint, out: number[]): void {
  if (n >= 0n) head(0, n, out);
  else head(1, -1n - n, out);
}

function encFloat(d: number, out: number[]): void {
  out.push(0xfb);
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, d, false);
  for (let i = 0; i < 8; i++) out.push(view.getUint8(i));
}

function encInto(v: CborValue, out: number[]): void {
  if (typeof v === "number") {
    if (Number.isInteger(v)) encInt(BigInt(v), out);
    else encFloat(v, out);
  } else if (typeof v === "bigint") {
    encInt(v, out);
  } else if (typeof v === "boolean") {
    out.push(v ? 0xf5 : 0xf4);
  } else if (v === null) {
    out.push(0xf6);
  } else if (typeof v === "string") {
    const bytes = csilTextEncoder.encode(v);
    head(3, bytes.length, out);
    for (const b of bytes) out.push(b);
  } else if (v instanceof Uint8Array) {
    head(2, v.length, out);
    for (const b of v) out.push(b);
  } else if (Array.isArray(v)) {
    head(4, v.length, out);
    for (const x of v) encInto(x, out);
  } else if (v instanceof Map) {
    head(5, v.size, out);
    for (const [k, val] of v) {
      encInto(k, out);
      encInto(val, out);
    }
  } else {
    head(6, v.tag, out);
    encInto(v.value, out);
  }
}

/** Encode a CBOR value tree to canonical CSIL CBOR bytes. */
export function encodeValue(value: CborValue): Uint8Array {
  const out: number[] = [];
  encInto(value, out);
  return Uint8Array.from(out);
}

type Cursor = { b: Uint8Array; pos: number };

function readArg(st: Cursor, low: number): bigint {
  if (low < 24) {
    st.pos += 1;
    return BigInt(low);
  }
  const width = low === 24 ? 1 : low === 25 ? 2 : low === 26 ? 4 : low === 27 ? 8 : 0;
  if (width === 0 || st.pos >= st.b.length || st.b.length - st.pos - 1 < width) {
    throw new Error("truncated CBOR argument");
  }
  if (low === 24) {
    const v = BigInt(st.b[st.pos + 1]);
    st.pos += 2;
    return v;
  }
  if (low === 25) {
    let v = 0n;
    for (let i = 1; i <= 2; i++) v = (v << 8n) | BigInt(st.b[st.pos + i]);
    st.pos += 3;
    return v;
  }
  if (low === 26) {
    let v = 0n;
    for (let i = 1; i <= 4; i++) v = (v << 8n) | BigInt(st.b[st.pos + i]);
    st.pos += 5;
    return v;
  }
  if (low === 27) {
    let v = 0n;
    for (let i = 1; i <= 8; i++) v = (v << 8n) | BigInt(st.b[st.pos + i]);
    st.pos += 9;
    return v;
  }
  throw new Error("malformed CBOR argument");
}

function smallInt(arg: bigint): number | bigint {
  return arg <= BigInt(Number.MAX_SAFE_INTEGER) ? Number(arg) : arg;
}

function readFloat(st: Cursor, low: number): number {
  const bits = readArg(st, low);
  if (low === 26) {
    const view = new DataView(new ArrayBuffer(4));
    view.setUint32(0, Number(bits), false);
    return view.getFloat32(0, false);
  }
  const view = new DataView(new ArrayBuffer(8));
  view.setBigUint64(0, bits, false);
  return view.getFloat64(0, false);
}

function decInto(st: Cursor, depth: number): CborValue {
  if (depth > 64) throw new Error("CBOR nesting limit exceeded");
  if (st.pos >= st.b.length) throw new Error("unexpected end of CBOR input");
  const ib = st.b[st.pos];
  const major = ib >> 5;
  const low = ib & 0x1f;
  if (major === 7) {
    if (low === 20) {
      st.pos += 1;
      return false;
    }
    if (low === 21) {
      st.pos += 1;
      return true;
    }
    if (low === 22 || low === 23) {
      st.pos += 1;
      return null;
    }
    if (low === 26 || low === 27) return readFloat(st, low);
    throw new Error("malformed CBOR simple value");
  }
  const arg = readArg(st, low);
  switch (major) {
    case 0:
      return smallInt(arg);
    case 1: {
      const n = -1n - arg;
      return n >= BigInt(Number.MIN_SAFE_INTEGER) ? Number(n) : n;
    }
    case 2: {
      if (arg > BigInt(st.b.length - st.pos)) throw new Error("truncated CBOR byte string");
      const n = Number(arg);
      const slice = st.b.slice(st.pos, st.pos + n);
      st.pos += n;
      return slice;
    }
    case 3: {
      if (arg > BigInt(st.b.length - st.pos)) throw new Error("truncated CBOR text string");
      const n = Number(arg);
      const text = csilTextDecoder.decode(st.b.subarray(st.pos, st.pos + n));
      st.pos += n;
      return text;
    }
    case 4: {
      if (arg > BigInt(st.b.length - st.pos)) throw new Error("CBOR array length exceeds remaining input");
      const n = Number(arg);
      const arr: CborValue[] = [];
      for (let i = 0; i < n; i++) arr.push(decInto(st, depth + 1));
      return arr;
    }
    case 5: {
      if (arg > BigInt(st.b.length - st.pos)) throw new Error("CBOR map length exceeds remaining input");
      const n = Number(arg);
      const m = new Map<CborValue, CborValue>();
      for (let i = 0; i < n; i++) {
        const k = decInto(st, depth + 1);
        const val = decInto(st, depth + 1);
        m.set(k, val);
      }
      return m;
    }
    case 6: {
      const inner = decInto(st, depth + 1);
      return { tag: Number(arg), value: inner };
    }
    default:
      throw new Error("malformed CBOR major type");
  }
}

/** Decode a CSIL CBOR byte payload into a CBOR value tree. */
export function decode(bytes: Uint8Array): CborValue {
  const st: Cursor = { b: bytes, pos: 0 };
  const v = decInto(st, 0);
  if (st.pos !== bytes.length) throw new Error("trailing bytes after CBOR value");
  return v;
}

/** The value for `key` in a CBOR map node, or `undefined` when absent. */
export function mapGet(value: CborValue, key: string): CborValue | undefined {
  return value instanceof Map ? value.get(key) : undefined;
}

/** The value for a required `key`; throws when the field is missing. */
export function requireKey(value: CborValue, key: string): CborValue {
  const v = mapGet(value, key);
  if (v === undefined) throw new Error(`missing required field: ${key}`);
  return v;
}

export function asNumber(value: CborValue): number {
  if (typeof value === "number") return value;
  if (typeof value === "bigint") return Number(value);
  throw new Error("expected a number");
}

export function asString(value: CborValue): string {
  if (typeof value === "string") return value;
  throw new Error("expected a text string");
}

export function asBytes(value: CborValue): Uint8Array {
  if (value instanceof Uint8Array) return value;
  throw new Error("expected a byte string");
}

export function asBool(value: CborValue): boolean {
  if (typeof value === "boolean") return value;
  throw new Error("expected a boolean");
}

export function asArray(value: CborValue): CborValue[] {
  if (Array.isArray(value)) return value;
  throw new Error("expected an array");
}

export function asMap(value: CborValue): Map<CborValue, CborValue> {
  if (value instanceof Map) return value;
  throw new Error("expected a map");
}

/** A decoded integer may surface as `bigint` (see `decInto`'s large-value path), so a
 * numeric literal's expected `number` is compared against the `bigint`-normalized form
 * rather than failing on a type mismatch that isn't a value mismatch. */
export function asLiteral<T extends CborValue>(value: CborValue, expected: T): T {
  const norm = typeof value === "bigint" && typeof expected === "number" ? Number(value) : value;
  if (norm !== expected) throw new Error(`literal mismatch: expected ${JSON.stringify(expected)}`);
  return expected;
}

/** Validate a decoded scalar against a literal-enum's declared vocabulary, erroring
 * on an unknown value. The caller reads through `asNumber`/`asString`/`asBool`, which
 * already normalize a decoded `bigint` to `number`, so a plain membership check suffices. */
export function asEnumMember<T extends number | string | boolean | null>(
  value: T,
  members: readonly T[],
): T {
  if (!members.includes(value)) {
    throw new Error(`unknown enum value: ${JSON.stringify(value)}`);
  }
  return value;
}

/** Read a decoded CBOR scalar without narrowing to one JS type, normalizing a
 * decoded integer `bigint` to `number` the same way `asNumber` does. Used for a
 * MIXED-kind literal enum (`"a" / 1`), where no single `asNumber`/`asString`/
 * `asBool` reader fits every member's runtime type — `asEnumMember`'s membership
 * check does the real narrowing instead. */
export function asEnumScalar(value: CborValue): string | number | boolean | null {
  if (typeof value === "bigint") return Number(value);
  if (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean" ||
    value === null
  ) {
    return value;
  }
  throw new Error("expected an enum scalar (string, number, boolean, or null)");
}

function asTagged(value: CborValue, tag: number): CborValue {
  if (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !(value instanceof Uint8Array) &&
    !(value instanceof Map) &&
    value.tag === tag
  ) {
    return value.value;
  }
  throw new Error(`expected tag ${tag}`);
}

/** Decode a tag-0 (RFC 3339, UTC) timestamp into a `Date`. */
export function asTimestamp(value: CborValue): Date {
  return new Date(asString(asTagged(value, 0)));
}

/** Decode a tag-4 decimal fraction into its `[exponent, mantissa]` payload. */
export function asDecimalPayload(value: CborValue): [number | bigint, number | bigint] {
  const arr = asArray(asTagged(value, 4));
  const intOf = (x: CborValue): number | bigint => {
    if (typeof x === "number" || typeof x === "bigint") return x;
    throw new Error("expected an integer in decimal payload");
  };
  return [intOf(arr[0]), intOf(arr[1])];
}

/** A `Date` rendered as the canonical tag-0 text: RFC 3339, UTC, `Z` offset. */
export function csilTsToText(d: Date): string {
  return d.toISOString().replace(/\.000Z$/, "Z");
}

export function toTaskCborValue(v: Task): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  csilMap.set("timeout", v.timeout);
  csilMap.set("priority", v.priority);
  csilMap.set("submit_time", v.submitTime);
  csilMap.set("update_time", v.updateTime);
  csilMap.set("current_state", v.currentState);
  csilMap.set("auto_target_state", v.autoTargetState);
  return csilMap;
}

export function fromTaskCborValue(value: CborValue): Task {
  return {
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
    autoTargetState: asString(requireKey(value, "auto_target_state")),
    submitTime: asNumber(requireKey(value, "submit_time")),
    updateTime: asNumber(requireKey(value, "update_time")),
    timeout: asNumber(requireKey(value, "timeout")),
    priority: asNumber(requireKey(value, "priority")),
  };
}

export function toTaskCbor(v: Task): Uint8Array {
  return encodeValue(toTaskCborValue(v));
}

export function fromTaskCbor(bytes: Uint8Array): Task {
  return fromTaskCborValue(decode(bytes));
}

export function toTaskDeliveryCborValue(v: TaskDelivery): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("task", toTaskCborValue(v.task));
  csilMap.set("payload", v.payload);
  return csilMap;
}

export function fromTaskDeliveryCborValue(value: CborValue): TaskDelivery {
  return {
    task: fromTaskCborValue(requireKey(value, "task")),
    payload: asBytes(requireKey(value, "payload")),
  };
}

export function toTaskDeliveryCbor(v: TaskDelivery): Uint8Array {
  return encodeValue(toTaskDeliveryCborValue(v));
}

export function fromTaskDeliveryCbor(bytes: Uint8Array): TaskDelivery {
  return fromTaskDeliveryCborValue(decode(bytes));
}

export function toSubmitTaskRequestCborValue(v: SubmitTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  csilMap.set("payload", v.payload);
  csilMap.set("timeout", v.timeout);
  csilMap.set("priority", v.priority);
  csilMap.set("current_state", v.currentState);
  csilMap.set("auto_target_state", v.autoTargetState);
  return csilMap;
}

export function fromSubmitTaskRequestCborValue(value: CborValue): SubmitTaskRequest {
  return {
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
    autoTargetState: asString(requireKey(value, "auto_target_state")),
    timeout: asNumber(requireKey(value, "timeout")),
    payload: asBytes(requireKey(value, "payload")),
    priority: asNumber(requireKey(value, "priority")),
  };
}

export function toSubmitTaskRequestCbor(v: SubmitTaskRequest): Uint8Array {
  return encodeValue(toSubmitTaskRequestCborValue(v));
}

export function fromSubmitTaskRequestCbor(bytes: Uint8Array): SubmitTaskRequest {
  return fromSubmitTaskRequestCborValue(decode(bytes));
}

export function toSubmitTaskResponseCborValue(v: SubmitTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toTaskCborValue(v.task));
  return csilMap;
}

export function fromSubmitTaskResponseCborValue(value: CborValue): SubmitTaskResponse {
  return {
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toSubmitTaskResponseCbor(v: SubmitTaskResponse): Uint8Array {
  return encodeValue(toSubmitTaskResponseCborValue(v));
}

export function fromSubmitTaskResponseCbor(bytes: Uint8Array): SubmitTaskResponse {
  return fromSubmitTaskResponseCborValue(decode(bytes));
}

export function toGetTaskStateByIDRequestCborValue(v: GetTaskStateByIDRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  return csilMap;
}

export function fromGetTaskStateByIDRequestCborValue(value: CborValue): GetTaskStateByIDRequest {
  return {
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
  };
}

export function toGetTaskStateByIDRequestCbor(v: GetTaskStateByIDRequest): Uint8Array {
  return encodeValue(toGetTaskStateByIDRequestCborValue(v));
}

export function fromGetTaskStateByIDRequestCbor(bytes: Uint8Array): GetTaskStateByIDRequest {
  return fromGetTaskStateByIDRequestCborValue(decode(bytes));
}

export function toGetTaskStateByIDResponseCborValue(v: GetTaskStateByIDResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toTaskCborValue(v.task));
  return csilMap;
}

export function fromGetTaskStateByIDResponseCborValue(value: CborValue): GetTaskStateByIDResponse {
  return {
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toGetTaskStateByIDResponseCbor(v: GetTaskStateByIDResponse): Uint8Array {
  return encodeValue(toGetTaskStateByIDResponseCborValue(v));
}

export function fromGetTaskStateByIDResponseCbor(bytes: Uint8Array): GetTaskStateByIDResponse {
  return fromGetTaskStateByIDResponseCborValue(decode(bytes));
}

export function toGetNextTaskRequestCborValue(v: GetNextTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  csilMap.set("current_state", v.currentState);
  csilMap.set("override_timeout", v.overrideTimeout);
  csilMap.set("override_current_state", v.overrideCurrentState);
  csilMap.set("override_auto_target_state", v.overrideAutoTargetState);
  return csilMap;
}

export function fromGetNextTaskRequestCborValue(value: CborValue): GetNextTaskRequest {
  return {
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
    overrideTimeout: asNumber(requireKey(value, "override_timeout")),
    overrideCurrentState: asString(requireKey(value, "override_current_state")),
    overrideAutoTargetState: asString(requireKey(value, "override_auto_target_state")),
  };
}

export function toGetNextTaskRequestCbor(v: GetNextTaskRequest): Uint8Array {
  return encodeValue(toGetNextTaskRequestCborValue(v));
}

export function fromGetNextTaskRequestCbor(bytes: Uint8Array): GetNextTaskRequest {
  return fromGetNextTaskRequestCborValue(decode(bytes));
}

export function toGetNextTaskResponseCborValue(v: GetNextTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.delivery !== undefined) csilMap.set("delivery", toTaskDeliveryCborValue(v.delivery));
  return csilMap;
}

export function fromGetNextTaskResponseCborValue(value: CborValue): GetNextTaskResponse {
  return {
    delivery: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromTaskDeliveryCborValue(csilV))(mapGet(value, "delivery")),
  };
}

export function toGetNextTaskResponseCbor(v: GetNextTaskResponse): Uint8Array {
  return encodeValue(toGetNextTaskResponseCborValue(v));
}

export function fromGetNextTaskResponseCbor(bytes: Uint8Array): GetNextTaskResponse {
  return fromGetNextTaskResponseCborValue(decode(bytes));
}

export function toGetNextTaskGroupRequestCborValue(v: GetNextTaskGroupRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queues", v.queues);
  csilMap.set("current_state", v.currentState);
  csilMap.set("override_timeout", v.overrideTimeout);
  csilMap.set("override_current_state", v.overrideCurrentState);
  csilMap.set("override_auto_target_state", v.overrideAutoTargetState);
  return csilMap;
}

export function fromGetNextTaskGroupRequestCborValue(value: CborValue): GetNextTaskGroupRequest {
  return {
    queues: asArray(requireKey(value, "queues")).map((csilE) => asString(csilE)),
    currentState: asString(requireKey(value, "current_state")),
    overrideTimeout: asNumber(requireKey(value, "override_timeout")),
    overrideCurrentState: asString(requireKey(value, "override_current_state")),
    overrideAutoTargetState: asString(requireKey(value, "override_auto_target_state")),
  };
}

export function toGetNextTaskGroupRequestCbor(v: GetNextTaskGroupRequest): Uint8Array {
  return encodeValue(toGetNextTaskGroupRequestCborValue(v));
}

export function fromGetNextTaskGroupRequestCbor(bytes: Uint8Array): GetNextTaskGroupRequest {
  return fromGetNextTaskGroupRequestCborValue(decode(bytes));
}

export function toGetNextTaskGroupResponseCborValue(v: GetNextTaskGroupResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.delivery !== undefined) csilMap.set("delivery", toTaskDeliveryCborValue(v.delivery));
  return csilMap;
}

export function fromGetNextTaskGroupResponseCborValue(value: CborValue): GetNextTaskGroupResponse {
  return {
    delivery: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromTaskDeliveryCborValue(csilV))(mapGet(value, "delivery")),
  };
}

export function toGetNextTaskGroupResponseCbor(v: GetNextTaskGroupResponse): Uint8Array {
  return encodeValue(toGetNextTaskGroupResponseCborValue(v));
}

export function fromGetNextTaskGroupResponseCbor(bytes: Uint8Array): GetNextTaskGroupResponse {
  return fromGetNextTaskGroupResponseCborValue(decode(bytes));
}

export function toCompleteTaskRequestCborValue(v: CompleteTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  csilMap.set("current_state", v.currentState);
  return csilMap;
}

export function fromCompleteTaskRequestCborValue(value: CborValue): CompleteTaskRequest {
  return {
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
  };
}

export function toCompleteTaskRequestCbor(v: CompleteTaskRequest): Uint8Array {
  return encodeValue(toCompleteTaskRequestCborValue(v));
}

export function fromCompleteTaskRequestCbor(bytes: Uint8Array): CompleteTaskRequest {
  return fromCompleteTaskRequestCborValue(decode(bytes));
}

export function toCompleteTaskResponseCborValue(v: CompleteTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toTaskCborValue(v.task));
  return csilMap;
}

export function fromCompleteTaskResponseCborValue(value: CborValue): CompleteTaskResponse {
  return {
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toCompleteTaskResponseCbor(v: CompleteTaskResponse): Uint8Array {
  return encodeValue(toCompleteTaskResponseCborValue(v));
}

export function fromCompleteTaskResponseCbor(bytes: Uint8Array): CompleteTaskResponse {
  return fromCompleteTaskResponseCborValue(decode(bytes));
}

export function toUpdateTaskRequestCborValue(v: UpdateTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  if (v.payload !== undefined) csilMap.set("payload", v.payload);
  csilMap.set("timeout", v.timeout);
  if (v.priority !== undefined) csilMap.set("priority", v.priority);
  csilMap.set("new_state", v.newState);
  csilMap.set("current_state", v.currentState);
  csilMap.set("auto_target_state", v.autoTargetState);
  return csilMap;
}

export function fromUpdateTaskRequestCborValue(value: CborValue): UpdateTaskRequest {
  return {
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
    autoTargetState: asString(requireKey(value, "auto_target_state")),
    timeout: asNumber(requireKey(value, "timeout")),
    newState: asString(requireKey(value, "new_state")),
    payload: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asBytes(csilV))(mapGet(value, "payload")),
    priority: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asNumber(csilV))(mapGet(value, "priority")),
  };
}

export function toUpdateTaskRequestCbor(v: UpdateTaskRequest): Uint8Array {
  return encodeValue(toUpdateTaskRequestCborValue(v));
}

export function fromUpdateTaskRequestCbor(bytes: Uint8Array): UpdateTaskRequest {
  return fromUpdateTaskRequestCborValue(decode(bytes));
}

export function toUpdateTaskResponseCborValue(v: UpdateTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toTaskCborValue(v.task));
  return csilMap;
}

export function fromUpdateTaskResponseCborValue(value: CborValue): UpdateTaskResponse {
  return {
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toUpdateTaskResponseCbor(v: UpdateTaskResponse): Uint8Array {
  return encodeValue(toUpdateTaskResponseCborValue(v));
}

export function fromUpdateTaskResponseCbor(bytes: Uint8Array): UpdateTaskResponse {
  return fromUpdateTaskResponseCborValue(decode(bytes));
}

export function toCancelTaskRequestCborValue(v: CancelTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  csilMap.set("current_state", v.currentState);
  return csilMap;
}

export function fromCancelTaskRequestCborValue(value: CborValue): CancelTaskRequest {
  return {
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
  };
}

export function toCancelTaskRequestCbor(v: CancelTaskRequest): Uint8Array {
  return encodeValue(toCancelTaskRequestCborValue(v));
}

export function fromCancelTaskRequestCbor(bytes: Uint8Array): CancelTaskRequest {
  return fromCancelTaskRequestCborValue(decode(bytes));
}

export function toCancelTaskResponseCborValue(v: CancelTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toTaskCborValue(v.task));
  return csilMap;
}

export function fromCancelTaskResponseCborValue(value: CborValue): CancelTaskResponse {
  return {
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toCancelTaskResponseCbor(v: CancelTaskResponse): Uint8Array {
  return encodeValue(toCancelTaskResponseCborValue(v));
}

export function fromCancelTaskResponseCbor(bytes: Uint8Array): CancelTaskResponse {
  return fromCancelTaskResponseCborValue(decode(bytes));
}

export function toCleanUpTimedOutRequestCborValue(v: CleanUpTimedOutRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  csilMap.set("at_time", v.atTime);
  return csilMap;
}

export function fromCleanUpTimedOutRequestCborValue(value: CborValue): CleanUpTimedOutRequest {
  return {
    atTime: asNumber(requireKey(value, "at_time")),
    queue: asString(requireKey(value, "queue")),
  };
}

export function toCleanUpTimedOutRequestCbor(v: CleanUpTimedOutRequest): Uint8Array {
  return encodeValue(toCleanUpTimedOutRequestCborValue(v));
}

export function fromCleanUpTimedOutRequestCbor(bytes: Uint8Array): CleanUpTimedOutRequest {
  return fromCleanUpTimedOutRequestCborValue(decode(bytes));
}

export function toCleanUpTimedOutResponseCborValue(v: CleanUpTimedOutResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("timed_out", v.timedOut);
  return csilMap;
}

export function fromCleanUpTimedOutResponseCborValue(value: CborValue): CleanUpTimedOutResponse {
  return {
    timedOut: asNumber(requireKey(value, "timed_out")),
  };
}

export function toCleanUpTimedOutResponseCbor(v: CleanUpTimedOutResponse): Uint8Array {
  return encodeValue(toCleanUpTimedOutResponseCborValue(v));
}

export function fromCleanUpTimedOutResponseCbor(bytes: Uint8Array): CleanUpTimedOutResponse {
  return fromCleanUpTimedOutResponseCborValue(decode(bytes));
}

export function toGetQueuesRequestCborValue(v: GetQueuesRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  return csilMap;
}

export function fromGetQueuesRequestCborValue(value: CborValue): GetQueuesRequest {
  void value;
  return {} as GetQueuesRequest;
}

export function toGetQueuesRequestCbor(v: GetQueuesRequest): Uint8Array {
  return encodeValue(toGetQueuesRequestCborValue(v));
}

export function fromGetQueuesRequestCbor(bytes: Uint8Array): GetQueuesRequest {
  return fromGetQueuesRequestCborValue(decode(bytes));
}

export function toGetQueuesResponseCborValue(v: GetQueuesResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queues", v.queues);
  csilMap.set("total_task_count", v.totalTaskCount);
  return csilMap;
}

export function fromGetQueuesResponseCborValue(value: CborValue): GetQueuesResponse {
  return {
    queues: asArray(requireKey(value, "queues")).map((csilE) => asString(csilE)),
    totalTaskCount: asNumber(requireKey(value, "total_task_count")),
  };
}

export function toGetQueuesResponseCbor(v: GetQueuesResponse): Uint8Array {
  return encodeValue(toGetQueuesResponseCborValue(v));
}

export function fromGetQueuesResponseCbor(bytes: Uint8Array): GetQueuesResponse {
  return fromGetQueuesResponseCborValue(decode(bytes));
}

export function toGetQueueTaskCountsRequestCborValue(v: GetQueueTaskCountsRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  return csilMap;
}

export function fromGetQueueTaskCountsRequestCborValue(value: CborValue): GetQueueTaskCountsRequest {
  void value;
  return {} as GetQueueTaskCountsRequest;
}

export function toGetQueueTaskCountsRequestCbor(v: GetQueueTaskCountsRequest): Uint8Array {
  return encodeValue(toGetQueueTaskCountsRequestCborValue(v));
}

export function fromGetQueueTaskCountsRequestCbor(bytes: Uint8Array): GetQueueTaskCountsRequest {
  return fromGetQueueTaskCountsRequestCborValue(decode(bytes));
}

export function toGetQueueTaskCountsResponseCborValue(v: GetQueueTaskCountsResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue_counts", new Map<CborValue, CborValue>(Object.entries(v.queueCounts).map(([csilK, csilV]): [CborValue, CborValue] => [csilK, csilV])));
  csilMap.set("total_task_count", v.totalTaskCount);
  return csilMap;
}

export function fromGetQueueTaskCountsResponseCborValue(value: CborValue): GetQueueTaskCountsResponse {
  return {
    queueCounts: Object.fromEntries(Array.from(asMap(requireKey(value, "queue_counts")), ([csilK, csilV]): [string, number] => [asString(csilK), asNumber(csilV)])),
    totalTaskCount: asNumber(requireKey(value, "total_task_count")),
  };
}

export function toGetQueueTaskCountsResponseCbor(v: GetQueueTaskCountsResponse): Uint8Array {
  return encodeValue(toGetQueueTaskCountsResponseCborValue(v));
}

export function fromGetQueueTaskCountsResponseCbor(bytes: Uint8Array): GetQueueTaskCountsResponse {
  return fromGetQueueTaskCountsResponseCborValue(decode(bytes));
}

export function toGetTaskStateCountsRequestCborValue(v: GetTaskStateCountsRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  return csilMap;
}

export function fromGetTaskStateCountsRequestCborValue(value: CborValue): GetTaskStateCountsRequest {
  return {
    queue: asString(requireKey(value, "queue")),
  };
}

export function toGetTaskStateCountsRequestCbor(v: GetTaskStateCountsRequest): Uint8Array {
  return encodeValue(toGetTaskStateCountsRequestCborValue(v));
}

export function fromGetTaskStateCountsRequestCbor(bytes: Uint8Array): GetTaskStateCountsRequest {
  return fromGetTaskStateCountsRequestCborValue(decode(bytes));
}

export function toGetTaskStateCountsResponseCborValue(v: GetTaskStateCountsResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("count", v.count);
  csilMap.set("queue", v.queue);
  csilMap.set("state_counts", new Map<CborValue, CborValue>(Object.entries(v.stateCounts).map(([csilK, csilV]): [CborValue, CborValue] => [csilK, csilV])));
  return csilMap;
}

export function fromGetTaskStateCountsResponseCborValue(value: CborValue): GetTaskStateCountsResponse {
  return {
    queue: asString(requireKey(value, "queue")),
    count: asNumber(requireKey(value, "count")),
    stateCounts: Object.fromEntries(Array.from(asMap(requireKey(value, "state_counts")), ([csilK, csilV]): [string, number] => [asString(csilK), asNumber(csilV)])),
  };
}

export function toGetTaskStateCountsResponseCbor(v: GetTaskStateCountsResponse): Uint8Array {
  return encodeValue(toGetTaskStateCountsResponseCborValue(v));
}

export function fromGetTaskStateCountsResponseCbor(bytes: Uint8Array): GetTaskStateCountsResponse {
  return fromGetTaskStateCountsResponseCborValue(decode(bytes));
}

export function toQueueAndStateCountsCborValue(v: QueueAndStateCounts): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("count", v.count);
  csilMap.set("queue", v.queue);
  csilMap.set("state_counts", new Map<CborValue, CborValue>(Object.entries(v.stateCounts).map(([csilK, csilV]): [CborValue, CborValue] => [csilK, csilV])));
  return csilMap;
}

export function fromQueueAndStateCountsCborValue(value: CborValue): QueueAndStateCounts {
  return {
    queue: asString(requireKey(value, "queue")),
    count: asNumber(requireKey(value, "count")),
    stateCounts: Object.fromEntries(Array.from(asMap(requireKey(value, "state_counts")), ([csilK, csilV]): [string, number] => [asString(csilK), asNumber(csilV)])),
  };
}

export function toQueueAndStateCountsCbor(v: QueueAndStateCounts): Uint8Array {
  return encodeValue(toQueueAndStateCountsCborValue(v));
}

export function fromQueueAndStateCountsCbor(bytes: Uint8Array): QueueAndStateCounts {
  return fromQueueAndStateCountsCborValue(decode(bytes));
}

export function toGetQueueAndStateCountsRequestCborValue(v: GetQueueAndStateCountsRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  return csilMap;
}

export function fromGetQueueAndStateCountsRequestCborValue(value: CborValue): GetQueueAndStateCountsRequest {
  void value;
  return {} as GetQueueAndStateCountsRequest;
}

export function toGetQueueAndStateCountsRequestCbor(v: GetQueueAndStateCountsRequest): Uint8Array {
  return encodeValue(toGetQueueAndStateCountsRequestCborValue(v));
}

export function fromGetQueueAndStateCountsRequestCbor(bytes: Uint8Array): GetQueueAndStateCountsRequest {
  return fromGetQueueAndStateCountsRequestCborValue(decode(bytes));
}

export function toGetQueueAndStateCountsResponseCborValue(v: GetQueueAndStateCountsResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue_and_state_counts", new Map<CborValue, CborValue>(Object.entries(v.queueAndStateCounts).map(([csilK, csilV]): [CborValue, CborValue] => [csilK, toQueueAndStateCountsCborValue(csilV)])));
  return csilMap;
}

export function fromGetQueueAndStateCountsResponseCborValue(value: CborValue): GetQueueAndStateCountsResponse {
  return {
    queueAndStateCounts: Object.fromEntries(Array.from(asMap(requireKey(value, "queue_and_state_counts")), ([csilK, csilV]): [string, QueueAndStateCounts] => [asString(csilK), fromQueueAndStateCountsCborValue(csilV)])),
  };
}

export function toGetQueueAndStateCountsResponseCbor(v: GetQueueAndStateCountsResponse): Uint8Array {
  return encodeValue(toGetQueueAndStateCountsResponseCborValue(v));
}

export function fromGetQueueAndStateCountsResponseCbor(bytes: Uint8Array): GetQueueAndStateCountsResponse {
  return fromGetQueueAndStateCountsResponseCborValue(decode(bytes));
}

export function toGetServerInfoRequestCborValue(v: GetServerInfoRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  return csilMap;
}

export function fromGetServerInfoRequestCborValue(value: CborValue): GetServerInfoRequest {
  void value;
  return {} as GetServerInfoRequest;
}

export function toGetServerInfoRequestCbor(v: GetServerInfoRequest): Uint8Array {
  return encodeValue(toGetServerInfoRequestCborValue(v));
}

export function fromGetServerInfoRequestCbor(bytes: Uint8Array): GetServerInfoRequest {
  return fromGetServerInfoRequestCborValue(decode(bytes));
}

export function toGetServerInfoResponseCborValue(v: GetServerInfoResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("features", v.features);
  csilMap.set("server_version", v.serverVersion);
  csilMap.set("task_guard_policy", v.taskGuardPolicy);
  csilMap.set("submission_key_policy", v.submissionKeyPolicy);
  csilMap.set("receipt_retention_seconds", v.receiptRetentionSeconds);
  return csilMap;
}

export function fromGetServerInfoResponseCborValue(value: CborValue): GetServerInfoResponse {
  return {
    serverVersion: asString(requireKey(value, "server_version")),
    features: asArray(requireKey(value, "features")).map((csilE) => asString(csilE)),
    submissionKeyPolicy: asString(requireKey(value, "submission_key_policy")),
    taskGuardPolicy: asString(requireKey(value, "task_guard_policy")),
    receiptRetentionSeconds: asNumber(requireKey(value, "receipt_retention_seconds")),
  };
}

export function toGetServerInfoResponseCbor(v: GetServerInfoResponse): Uint8Array {
  return encodeValue(toGetServerInfoResponseCborValue(v));
}

export function fromGetServerInfoResponseCbor(bytes: Uint8Array): GetServerInfoResponse {
  return fromGetServerInfoResponseCborValue(decode(bytes));
}

export function toGuardedTaskCborValue(v: GuardedTask): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("task", toTaskCborValue(v.task));
  csilMap.set("guarded", v.guarded);
  csilMap.set("revision", v.revision);
  csilMap.set("terminal", v.terminal);
  return csilMap;
}

export function fromGuardedTaskCborValue(value: CborValue): GuardedTask {
  return {
    task: fromTaskCborValue(requireKey(value, "task")),
    guarded: asBool(requireKey(value, "guarded")),
    revision: asNumber(requireKey(value, "revision")),
    terminal: asBool(requireKey(value, "terminal")),
  };
}

export function toGuardedTaskCbor(v: GuardedTask): Uint8Array {
  return encodeValue(toGuardedTaskCborValue(v));
}

export function fromGuardedTaskCbor(bytes: Uint8Array): GuardedTask {
  return fromGuardedTaskCborValue(decode(bytes));
}

export function toSubmissionReceiptCborValue(v: SubmissionReceipt): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  csilMap.set("guarded", v.guarded);
  csilMap.set("task_uuid", v.taskUuid);
  csilMap.set("expires_at", v.expiresAt);
  csilMap.set("accepted_at", v.acceptedAt);
  csilMap.set("submission_key", v.submissionKey);
  return csilMap;
}

export function fromSubmissionReceiptCborValue(value: CborValue): SubmissionReceipt {
  return {
    queue: asString(requireKey(value, "queue")),
    submissionKey: asString(requireKey(value, "submission_key")),
    taskUuid: asString(requireKey(value, "task_uuid")),
    acceptedAt: asNumber(requireKey(value, "accepted_at")),
    expiresAt: asNumber(requireKey(value, "expires_at")),
    guarded: asBool(requireKey(value, "guarded")),
  };
}

export function toSubmissionReceiptCbor(v: SubmissionReceipt): Uint8Array {
  return encodeValue(toSubmissionReceiptCborValue(v));
}

export function fromSubmissionReceiptCbor(bytes: Uint8Array): SubmissionReceipt {
  return fromSubmissionReceiptCborValue(decode(bytes));
}

export function toSubmitKeyedTaskRequestCborValue(v: SubmitKeyedTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  csilMap.set("guarded", v.guarded);
  csilMap.set("payload", v.payload);
  csilMap.set("timeout", v.timeout);
  csilMap.set("priority", v.priority);
  csilMap.set("current_state", v.currentState);
  csilMap.set("submission_key", v.submissionKey);
  csilMap.set("auto_target_state", v.autoTargetState);
  return csilMap;
}

export function fromSubmitKeyedTaskRequestCborValue(value: CborValue): SubmitKeyedTaskRequest {
  return {
    submissionKey: asString(requireKey(value, "submission_key")),
    guarded: asBool(requireKey(value, "guarded")),
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
    autoTargetState: asString(requireKey(value, "auto_target_state")),
    timeout: asNumber(requireKey(value, "timeout")),
    payload: asBytes(requireKey(value, "payload")),
    priority: asNumber(requireKey(value, "priority")),
  };
}

export function toSubmitKeyedTaskRequestCbor(v: SubmitKeyedTaskRequest): Uint8Array {
  return encodeValue(toSubmitKeyedTaskRequestCborValue(v));
}

export function fromSubmitKeyedTaskRequestCbor(bytes: Uint8Array): SubmitKeyedTaskRequest {
  return fromSubmitKeyedTaskRequestCborValue(decode(bytes));
}

export function toSubmitKeyedTaskResponseCborValue(v: SubmitKeyedTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toGuardedTaskCborValue(v.task));
  csilMap.set("receipt", toSubmissionReceiptCborValue(v.receipt));
  csilMap.set("replayed", v.replayed);
  return csilMap;
}

export function fromSubmitKeyedTaskResponseCborValue(value: CborValue): SubmitKeyedTaskResponse {
  return {
    receipt: fromSubmissionReceiptCborValue(requireKey(value, "receipt")),
    replayed: asBool(requireKey(value, "replayed")),
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromGuardedTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toSubmitKeyedTaskResponseCbor(v: SubmitKeyedTaskResponse): Uint8Array {
  return encodeValue(toSubmitKeyedTaskResponseCborValue(v));
}

export function fromSubmitKeyedTaskResponseCbor(bytes: Uint8Array): SubmitKeyedTaskResponse {
  return fromSubmitKeyedTaskResponseCborValue(decode(bytes));
}

export function toLookupSubmissionRequestCborValue(v: LookupSubmissionRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  csilMap.set("submission_key", v.submissionKey);
  return csilMap;
}

export function fromLookupSubmissionRequestCborValue(value: CborValue): LookupSubmissionRequest {
  return {
    queue: asString(requireKey(value, "queue")),
    submissionKey: asString(requireKey(value, "submission_key")),
  };
}

export function toLookupSubmissionRequestCbor(v: LookupSubmissionRequest): Uint8Array {
  return encodeValue(toLookupSubmissionRequestCborValue(v));
}

export function fromLookupSubmissionRequestCbor(bytes: Uint8Array): LookupSubmissionRequest {
  return fromLookupSubmissionRequestCborValue(decode(bytes));
}

export function toLookupSubmissionResponseCborValue(v: LookupSubmissionResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toGuardedTaskCborValue(v.task));
  if (v.receipt !== undefined) csilMap.set("receipt", toSubmissionReceiptCborValue(v.receipt));
  return csilMap;
}

export function fromLookupSubmissionResponseCborValue(value: CborValue): LookupSubmissionResponse {
  return {
    receipt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromSubmissionReceiptCborValue(csilV))(mapGet(value, "receipt")),
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromGuardedTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toLookupSubmissionResponseCbor(v: LookupSubmissionResponse): Uint8Array {
  return encodeValue(toLookupSubmissionResponseCborValue(v));
}

export function fromLookupSubmissionResponseCbor(bytes: Uint8Array): LookupSubmissionResponse {
  return fromLookupSubmissionResponseCborValue(decode(bytes));
}

export function toClaimGuardedTaskRequestCborValue(v: ClaimGuardedTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queue", v.queue);
  csilMap.set("operation_id", v.operationId);
  csilMap.set("current_state", v.currentState);
  csilMap.set("override_timeout", v.overrideTimeout);
  csilMap.set("override_current_state", v.overrideCurrentState);
  csilMap.set("override_auto_target_state", v.overrideAutoTargetState);
  return csilMap;
}

export function fromClaimGuardedTaskRequestCborValue(value: CborValue): ClaimGuardedTaskRequest {
  return {
    operationId: asString(requireKey(value, "operation_id")),
    queue: asString(requireKey(value, "queue")),
    currentState: asString(requireKey(value, "current_state")),
    overrideTimeout: asNumber(requireKey(value, "override_timeout")),
    overrideCurrentState: asString(requireKey(value, "override_current_state")),
    overrideAutoTargetState: asString(requireKey(value, "override_auto_target_state")),
  };
}

export function toClaimGuardedTaskRequestCbor(v: ClaimGuardedTaskRequest): Uint8Array {
  return encodeValue(toClaimGuardedTaskRequestCborValue(v));
}

export function fromClaimGuardedTaskRequestCbor(bytes: Uint8Array): ClaimGuardedTaskRequest {
  return fromClaimGuardedTaskRequestCborValue(decode(bytes));
}

export function toGuardedDeliveryCborValue(v: GuardedDelivery): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("task", toGuardedTaskCborValue(v.task));
  csilMap.set("payload", v.payload);
  return csilMap;
}

export function fromGuardedDeliveryCborValue(value: CborValue): GuardedDelivery {
  return {
    task: fromGuardedTaskCborValue(requireKey(value, "task")),
    payload: asBytes(requireKey(value, "payload")),
  };
}

export function toGuardedDeliveryCbor(v: GuardedDelivery): Uint8Array {
  return encodeValue(toGuardedDeliveryCborValue(v));
}

export function fromGuardedDeliveryCbor(bytes: Uint8Array): GuardedDelivery {
  return fromGuardedDeliveryCborValue(decode(bytes));
}

export function toClaimGuardedTaskResponseCborValue(v: ClaimGuardedTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.delivery !== undefined) csilMap.set("delivery", toGuardedDeliveryCborValue(v.delivery));
  csilMap.set("replayed", v.replayed);
  return csilMap;
}

export function fromClaimGuardedTaskResponseCborValue(value: CborValue): ClaimGuardedTaskResponse {
  return {
    delivery: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromGuardedDeliveryCborValue(csilV))(mapGet(value, "delivery")),
    replayed: asBool(requireKey(value, "replayed")),
  };
}

export function toClaimGuardedTaskResponseCbor(v: ClaimGuardedTaskResponse): Uint8Array {
  return encodeValue(toClaimGuardedTaskResponseCborValue(v));
}

export function fromClaimGuardedTaskResponseCbor(bytes: Uint8Array): ClaimGuardedTaskResponse {
  return fromClaimGuardedTaskResponseCborValue(decode(bytes));
}

export function toClaimGuardedTaskGroupRequestCborValue(v: ClaimGuardedTaskGroupRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("queues", v.queues);
  csilMap.set("operation_id", v.operationId);
  csilMap.set("current_state", v.currentState);
  csilMap.set("override_timeout", v.overrideTimeout);
  csilMap.set("override_current_state", v.overrideCurrentState);
  csilMap.set("override_auto_target_state", v.overrideAutoTargetState);
  return csilMap;
}

export function fromClaimGuardedTaskGroupRequestCborValue(value: CborValue): ClaimGuardedTaskGroupRequest {
  return {
    operationId: asString(requireKey(value, "operation_id")),
    queues: asArray(requireKey(value, "queues")).map((csilE) => asString(csilE)),
    currentState: asString(requireKey(value, "current_state")),
    overrideTimeout: asNumber(requireKey(value, "override_timeout")),
    overrideCurrentState: asString(requireKey(value, "override_current_state")),
    overrideAutoTargetState: asString(requireKey(value, "override_auto_target_state")),
  };
}

export function toClaimGuardedTaskGroupRequestCbor(v: ClaimGuardedTaskGroupRequest): Uint8Array {
  return encodeValue(toClaimGuardedTaskGroupRequestCborValue(v));
}

export function fromClaimGuardedTaskGroupRequestCbor(bytes: Uint8Array): ClaimGuardedTaskGroupRequest {
  return fromClaimGuardedTaskGroupRequestCborValue(decode(bytes));
}

export function toClaimGuardedTaskGroupResponseCborValue(v: ClaimGuardedTaskGroupResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.delivery !== undefined) csilMap.set("delivery", toGuardedDeliveryCborValue(v.delivery));
  csilMap.set("replayed", v.replayed);
  return csilMap;
}

export function fromClaimGuardedTaskGroupResponseCborValue(value: CborValue): ClaimGuardedTaskGroupResponse {
  return {
    delivery: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromGuardedDeliveryCborValue(csilV))(mapGet(value, "delivery")),
    replayed: asBool(requireKey(value, "replayed")),
  };
}

export function toClaimGuardedTaskGroupResponseCbor(v: ClaimGuardedTaskGroupResponse): Uint8Array {
  return encodeValue(toClaimGuardedTaskGroupResponseCborValue(v));
}

export function fromClaimGuardedTaskGroupResponseCbor(bytes: Uint8Array): ClaimGuardedTaskGroupResponse {
  return fromClaimGuardedTaskGroupResponseCborValue(decode(bytes));
}

export function toUpdateGuardedTaskRequestCborValue(v: UpdateGuardedTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  if (v.payload !== undefined) csilMap.set("payload", v.payload);
  csilMap.set("timeout", v.timeout);
  if (v.priority !== undefined) csilMap.set("priority", v.priority);
  csilMap.set("new_state", v.newState);
  csilMap.set("operation_id", v.operationId);
  if (v.expectedState !== undefined) csilMap.set("expected_state", v.expectedState);
  csilMap.set("auto_target_state", v.autoTargetState);
  csilMap.set("expected_revision", v.expectedRevision);
  return csilMap;
}

export function fromUpdateGuardedTaskRequestCborValue(value: CborValue): UpdateGuardedTaskRequest {
  return {
    operationId: asString(requireKey(value, "operation_id")),
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
    expectedRevision: asNumber(requireKey(value, "expected_revision")),
    expectedState: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "expected_state")),
    newState: asString(requireKey(value, "new_state")),
    autoTargetState: asString(requireKey(value, "auto_target_state")),
    timeout: asNumber(requireKey(value, "timeout")),
    payload: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asBytes(csilV))(mapGet(value, "payload")),
    priority: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asNumber(csilV))(mapGet(value, "priority")),
  };
}

export function toUpdateGuardedTaskRequestCbor(v: UpdateGuardedTaskRequest): Uint8Array {
  return encodeValue(toUpdateGuardedTaskRequestCborValue(v));
}

export function fromUpdateGuardedTaskRequestCbor(bytes: Uint8Array): UpdateGuardedTaskRequest {
  return fromUpdateGuardedTaskRequestCborValue(decode(bytes));
}

export function toUpdateGuardedTaskResponseCborValue(v: UpdateGuardedTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("task", toGuardedTaskCborValue(v.task));
  csilMap.set("replayed", v.replayed);
  return csilMap;
}

export function fromUpdateGuardedTaskResponseCborValue(value: CborValue): UpdateGuardedTaskResponse {
  return {
    task: fromGuardedTaskCborValue(requireKey(value, "task")),
    replayed: asBool(requireKey(value, "replayed")),
  };
}

export function toUpdateGuardedTaskResponseCbor(v: UpdateGuardedTaskResponse): Uint8Array {
  return encodeValue(toUpdateGuardedTaskResponseCborValue(v));
}

export function fromUpdateGuardedTaskResponseCbor(bytes: Uint8Array): UpdateGuardedTaskResponse {
  return fromUpdateGuardedTaskResponseCborValue(decode(bytes));
}

export function toCompleteGuardedTaskRequestCborValue(v: CompleteGuardedTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  csilMap.set("operation_id", v.operationId);
  if (v.expectedState !== undefined) csilMap.set("expected_state", v.expectedState);
  csilMap.set("expected_revision", v.expectedRevision);
  return csilMap;
}

export function fromCompleteGuardedTaskRequestCborValue(value: CborValue): CompleteGuardedTaskRequest {
  return {
    operationId: asString(requireKey(value, "operation_id")),
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
    expectedRevision: asNumber(requireKey(value, "expected_revision")),
    expectedState: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "expected_state")),
  };
}

export function toCompleteGuardedTaskRequestCbor(v: CompleteGuardedTaskRequest): Uint8Array {
  return encodeValue(toCompleteGuardedTaskRequestCborValue(v));
}

export function fromCompleteGuardedTaskRequestCbor(bytes: Uint8Array): CompleteGuardedTaskRequest {
  return fromCompleteGuardedTaskRequestCborValue(decode(bytes));
}

export function toCompleteGuardedTaskResponseCborValue(v: CompleteGuardedTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("task", toGuardedTaskCborValue(v.task));
  csilMap.set("replayed", v.replayed);
  return csilMap;
}

export function fromCompleteGuardedTaskResponseCborValue(value: CborValue): CompleteGuardedTaskResponse {
  return {
    task: fromGuardedTaskCborValue(requireKey(value, "task")),
    replayed: asBool(requireKey(value, "replayed")),
  };
}

export function toCompleteGuardedTaskResponseCbor(v: CompleteGuardedTaskResponse): Uint8Array {
  return encodeValue(toCompleteGuardedTaskResponseCborValue(v));
}

export function fromCompleteGuardedTaskResponseCbor(bytes: Uint8Array): CompleteGuardedTaskResponse {
  return fromCompleteGuardedTaskResponseCborValue(decode(bytes));
}

export function toCancelGuardedTaskRequestCborValue(v: CancelGuardedTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  csilMap.set("operation_id", v.operationId);
  if (v.expectedState !== undefined) csilMap.set("expected_state", v.expectedState);
  csilMap.set("expected_revision", v.expectedRevision);
  return csilMap;
}

export function fromCancelGuardedTaskRequestCborValue(value: CborValue): CancelGuardedTaskRequest {
  return {
    operationId: asString(requireKey(value, "operation_id")),
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
    expectedRevision: asNumber(requireKey(value, "expected_revision")),
    expectedState: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : asString(csilV))(mapGet(value, "expected_state")),
  };
}

export function toCancelGuardedTaskRequestCbor(v: CancelGuardedTaskRequest): Uint8Array {
  return encodeValue(toCancelGuardedTaskRequestCborValue(v));
}

export function fromCancelGuardedTaskRequestCbor(bytes: Uint8Array): CancelGuardedTaskRequest {
  return fromCancelGuardedTaskRequestCborValue(decode(bytes));
}

export function toCancelGuardedTaskResponseCborValue(v: CancelGuardedTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("task", toGuardedTaskCborValue(v.task));
  csilMap.set("replayed", v.replayed);
  return csilMap;
}

export function fromCancelGuardedTaskResponseCborValue(value: CborValue): CancelGuardedTaskResponse {
  return {
    task: fromGuardedTaskCborValue(requireKey(value, "task")),
    replayed: asBool(requireKey(value, "replayed")),
  };
}

export function toCancelGuardedTaskResponseCbor(v: CancelGuardedTaskResponse): Uint8Array {
  return encodeValue(toCancelGuardedTaskResponseCborValue(v));
}

export function fromCancelGuardedTaskResponseCbor(bytes: Uint8Array): CancelGuardedTaskResponse {
  return fromCancelGuardedTaskResponseCborValue(decode(bytes));
}

export function toGetGuardedTaskRequestCborValue(v: GetGuardedTaskRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("uuid", v.uuid);
  csilMap.set("queue", v.queue);
  return csilMap;
}

export function fromGetGuardedTaskRequestCborValue(value: CborValue): GetGuardedTaskRequest {
  return {
    uuid: asString(requireKey(value, "uuid")),
    queue: asString(requireKey(value, "queue")),
  };
}

export function toGetGuardedTaskRequestCbor(v: GetGuardedTaskRequest): Uint8Array {
  return encodeValue(toGetGuardedTaskRequestCborValue(v));
}

export function fromGetGuardedTaskRequestCbor(bytes: Uint8Array): GetGuardedTaskRequest {
  return fromGetGuardedTaskRequestCborValue(decode(bytes));
}

export function toGetGuardedTaskResponseCborValue(v: GetGuardedTaskResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.task !== undefined) csilMap.set("task", toGuardedTaskCborValue(v.task));
  return csilMap;
}

export function fromGetGuardedTaskResponseCborValue(value: CborValue): GetGuardedTaskResponse {
  return {
    task: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromGuardedTaskCborValue(csilV))(mapGet(value, "task")),
  };
}

export function toGetGuardedTaskResponseCbor(v: GetGuardedTaskResponse): Uint8Array {
  return encodeValue(toGetGuardedTaskResponseCborValue(v));
}

export function fromGetGuardedTaskResponseCbor(bytes: Uint8Array): GetGuardedTaskResponse {
  return fromGetGuardedTaskResponseCborValue(decode(bytes));
}

export function toOperationReceiptCborValue(v: OperationReceipt): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("at", v.at);
  csilMap.set("op", v.op);
  csilMap.set("queue", v.queue);
  csilMap.set("task_uuid", v.taskUuid);
  csilMap.set("expires_at", v.expiresAt);
  csilMap.set("operation_id", v.operationId);
  csilMap.set("result_state", v.resultState);
  csilMap.set("result_revision", v.resultRevision);
  return csilMap;
}

export function fromOperationReceiptCborValue(value: CborValue): OperationReceipt {
  return {
    operationId: asString(requireKey(value, "operation_id")),
    op: asString(requireKey(value, "op")),
    taskUuid: asString(requireKey(value, "task_uuid")),
    queue: asString(requireKey(value, "queue")),
    resultRevision: asNumber(requireKey(value, "result_revision")),
    resultState: asString(requireKey(value, "result_state")),
    at: asNumber(requireKey(value, "at")),
    expiresAt: asNumber(requireKey(value, "expires_at")),
  };
}

export function toOperationReceiptCbor(v: OperationReceipt): Uint8Array {
  return encodeValue(toOperationReceiptCborValue(v));
}

export function fromOperationReceiptCbor(bytes: Uint8Array): OperationReceipt {
  return fromOperationReceiptCborValue(decode(bytes));
}

export function toLookupOperationRequestCborValue(v: LookupOperationRequest): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("operation_id", v.operationId);
  return csilMap;
}

export function fromLookupOperationRequestCborValue(value: CborValue): LookupOperationRequest {
  return {
    operationId: asString(requireKey(value, "operation_id")),
  };
}

export function toLookupOperationRequestCbor(v: LookupOperationRequest): Uint8Array {
  return encodeValue(toLookupOperationRequestCborValue(v));
}

export function fromLookupOperationRequestCbor(bytes: Uint8Array): LookupOperationRequest {
  return fromLookupOperationRequestCborValue(decode(bytes));
}

export function toLookupOperationResponseCborValue(v: LookupOperationResponse): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  if (v.receipt !== undefined) csilMap.set("receipt", toOperationReceiptCborValue(v.receipt));
  return csilMap;
}

export function fromLookupOperationResponseCborValue(value: CborValue): LookupOperationResponse {
  return {
    receipt: ((csilV: CborValue | undefined) => csilV === undefined ? undefined : fromOperationReceiptCborValue(csilV))(mapGet(value, "receipt")),
  };
}

export function toLookupOperationResponseCbor(v: LookupOperationResponse): Uint8Array {
  return encodeValue(toLookupOperationResponseCborValue(v));
}

export function fromLookupOperationResponseCbor(bytes: Uint8Array): LookupOperationResponse {
  return fromLookupOperationResponseCborValue(decode(bytes));
}

export function toServiceErrorCborValue(v: ServiceError): CborValue {
  const csilMap = new Map<CborValue, CborValue>();
  csilMap.set("code", v.code);
  csilMap.set("message", v.message);
  return csilMap;
}

export function fromServiceErrorCborValue(value: CborValue): ServiceError {
  return {
    code: asNumber(requireKey(value, "code")),
    message: asString(requireKey(value, "message")),
  };
}

export function toServiceErrorCbor(v: ServiceError): Uint8Array {
  return encodeValue(toServiceErrorCborValue(v));
}

export function fromServiceErrorCbor(bytes: Uint8Array): ServiceError {
  return fromServiceErrorCborValue(decode(bytes));
}

