# Code generated by csilgen; DO NOT EDIT.

defmodule Csilgen.Generated.Transport do
  @moduledoc """
  Caller-supplied byte carrier. The host implements this behaviour for its
  carrier (CBOR over HTTP/WebSocket/etc.): `call/4` takes the already-encoded
  request bytes and returns the response bytes. The generated client owns
  (de)serialization via the codec; the carrier only moves bytes.
  """

  @type t :: struct()

  @callback call(t(), service :: String.t(), method :: String.t(), req :: binary()) ::
              binary()

  @doc "Dispatches to the transport struct's implementing module."
  @spec call(t(), String.t(), String.t(), binary()) :: binary()
  def call(%mod{} = transport, service, method, req) do
    mod.call(transport, service, method, req)
  end
end

defmodule Csilgen.Generated.CorndogsClient do
  @moduledoc "Typed client for the CorndogsService service. The client owns (de)serialization via the codec; the transport only moves bytes."

  @enforce_keys [:transport]
  defstruct [:transport]
  @type t :: %__MODULE__{transport: Csilgen.Generated.Transport.t()}

  @spec new(Csilgen.Generated.Transport.t()) :: t()
  def new(transport), do: %__MODULE__{transport: transport}

  @spec submit_task(t(), Csilgen.Generated.SubmitTaskRequest.t()) ::
          Csilgen.Generated.SubmitTaskResponse.t()
  def submit_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "SubmitTask",
        Csilgen.Generated.SubmitTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.SubmitTaskResponse.from_cbor(resp)
  end

  @spec get_task_state_by_id(t(), Csilgen.Generated.GetTaskStateByIDRequest.t()) ::
          Csilgen.Generated.GetTaskStateByIDResponse.t()
  def get_task_state_by_id(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetTaskStateByID",
        Csilgen.Generated.GetTaskStateByIDRequest.to_cbor(req)
      )

    Csilgen.Generated.GetTaskStateByIDResponse.from_cbor(resp)
  end

  @spec get_next_task(t(), Csilgen.Generated.GetNextTaskRequest.t()) ::
          Csilgen.Generated.GetNextTaskResponse.t()
  def get_next_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetNextTask",
        Csilgen.Generated.GetNextTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.GetNextTaskResponse.from_cbor(resp)
  end

  @spec get_next_task_group(t(), Csilgen.Generated.GetNextTaskGroupRequest.t()) ::
          Csilgen.Generated.GetNextTaskGroupResponse.t()
  def get_next_task_group(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetNextTaskGroup",
        Csilgen.Generated.GetNextTaskGroupRequest.to_cbor(req)
      )

    Csilgen.Generated.GetNextTaskGroupResponse.from_cbor(resp)
  end

  @spec update_task(t(), Csilgen.Generated.UpdateTaskRequest.t()) ::
          Csilgen.Generated.UpdateTaskResponse.t()
  def update_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "UpdateTask",
        Csilgen.Generated.UpdateTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.UpdateTaskResponse.from_cbor(resp)
  end

  @spec complete_task(t(), Csilgen.Generated.CompleteTaskRequest.t()) ::
          Csilgen.Generated.CompleteTaskResponse.t()
  def complete_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "CompleteTask",
        Csilgen.Generated.CompleteTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.CompleteTaskResponse.from_cbor(resp)
  end

  @spec cancel_task(t(), Csilgen.Generated.CancelTaskRequest.t()) ::
          Csilgen.Generated.CancelTaskResponse.t()
  def cancel_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "CancelTask",
        Csilgen.Generated.CancelTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.CancelTaskResponse.from_cbor(resp)
  end

  @spec clean_up_timed_out(t(), Csilgen.Generated.CleanUpTimedOutRequest.t()) ::
          Csilgen.Generated.CleanUpTimedOutResponse.t()
  def clean_up_timed_out(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "CleanUpTimedOut",
        Csilgen.Generated.CleanUpTimedOutRequest.to_cbor(req)
      )

    Csilgen.Generated.CleanUpTimedOutResponse.from_cbor(resp)
  end

  @spec get_queues(t(), Csilgen.Generated.GetQueuesRequest.t()) ::
          Csilgen.Generated.GetQueuesResponse.t()
  def get_queues(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetQueues",
        Csilgen.Generated.GetQueuesRequest.to_cbor(req)
      )

    Csilgen.Generated.GetQueuesResponse.from_cbor(resp)
  end

  @spec get_queue_task_counts(t(), Csilgen.Generated.GetQueueTaskCountsRequest.t()) ::
          Csilgen.Generated.GetQueueTaskCountsResponse.t()
  def get_queue_task_counts(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetQueueTaskCounts",
        Csilgen.Generated.GetQueueTaskCountsRequest.to_cbor(req)
      )

    Csilgen.Generated.GetQueueTaskCountsResponse.from_cbor(resp)
  end

  @spec get_task_state_counts(t(), Csilgen.Generated.GetTaskStateCountsRequest.t()) ::
          Csilgen.Generated.GetTaskStateCountsResponse.t()
  def get_task_state_counts(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetTaskStateCounts",
        Csilgen.Generated.GetTaskStateCountsRequest.to_cbor(req)
      )

    Csilgen.Generated.GetTaskStateCountsResponse.from_cbor(resp)
  end

  @spec get_queue_and_state_counts(t(), Csilgen.Generated.GetQueueAndStateCountsRequest.t()) ::
          Csilgen.Generated.GetQueueAndStateCountsResponse.t()
  def get_queue_and_state_counts(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetQueueAndStateCounts",
        Csilgen.Generated.GetQueueAndStateCountsRequest.to_cbor(req)
      )

    Csilgen.Generated.GetQueueAndStateCountsResponse.from_cbor(resp)
  end

  @spec get_server_info(t(), Csilgen.Generated.GetServerInfoRequest.t()) ::
          Csilgen.Generated.GetServerInfoResponse.t()
  def get_server_info(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetServerInfo",
        Csilgen.Generated.GetServerInfoRequest.to_cbor(req)
      )

    Csilgen.Generated.GetServerInfoResponse.from_cbor(resp)
  end

  @spec submit_keyed_task(t(), Csilgen.Generated.SubmitKeyedTaskRequest.t()) ::
          Csilgen.Generated.SubmitKeyedTaskResponse.t()
  def submit_keyed_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "SubmitKeyedTask",
        Csilgen.Generated.SubmitKeyedTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.SubmitKeyedTaskResponse.from_cbor(resp)
  end

  @spec lookup_submission(t(), Csilgen.Generated.LookupSubmissionRequest.t()) ::
          Csilgen.Generated.LookupSubmissionResponse.t()
  def lookup_submission(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "LookupSubmission",
        Csilgen.Generated.LookupSubmissionRequest.to_cbor(req)
      )

    Csilgen.Generated.LookupSubmissionResponse.from_cbor(resp)
  end

  @spec claim_guarded_task(t(), Csilgen.Generated.ClaimGuardedTaskRequest.t()) ::
          Csilgen.Generated.ClaimGuardedTaskResponse.t()
  def claim_guarded_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "ClaimGuardedTask",
        Csilgen.Generated.ClaimGuardedTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.ClaimGuardedTaskResponse.from_cbor(resp)
  end

  @spec claim_guarded_task_group(t(), Csilgen.Generated.ClaimGuardedTaskGroupRequest.t()) ::
          Csilgen.Generated.ClaimGuardedTaskGroupResponse.t()
  def claim_guarded_task_group(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "ClaimGuardedTaskGroup",
        Csilgen.Generated.ClaimGuardedTaskGroupRequest.to_cbor(req)
      )

    Csilgen.Generated.ClaimGuardedTaskGroupResponse.from_cbor(resp)
  end

  @spec update_guarded_task(t(), Csilgen.Generated.UpdateGuardedTaskRequest.t()) ::
          Csilgen.Generated.UpdateGuardedTaskResponse.t()
  def update_guarded_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "UpdateGuardedTask",
        Csilgen.Generated.UpdateGuardedTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.UpdateGuardedTaskResponse.from_cbor(resp)
  end

  @spec complete_guarded_task(t(), Csilgen.Generated.CompleteGuardedTaskRequest.t()) ::
          Csilgen.Generated.CompleteGuardedTaskResponse.t()
  def complete_guarded_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "CompleteGuardedTask",
        Csilgen.Generated.CompleteGuardedTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.CompleteGuardedTaskResponse.from_cbor(resp)
  end

  @spec cancel_guarded_task(t(), Csilgen.Generated.CancelGuardedTaskRequest.t()) ::
          Csilgen.Generated.CancelGuardedTaskResponse.t()
  def cancel_guarded_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "CancelGuardedTask",
        Csilgen.Generated.CancelGuardedTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.CancelGuardedTaskResponse.from_cbor(resp)
  end

  @spec get_guarded_task(t(), Csilgen.Generated.GetGuardedTaskRequest.t()) ::
          Csilgen.Generated.GetGuardedTaskResponse.t()
  def get_guarded_task(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "GetGuardedTask",
        Csilgen.Generated.GetGuardedTaskRequest.to_cbor(req)
      )

    Csilgen.Generated.GetGuardedTaskResponse.from_cbor(resp)
  end

  @spec lookup_operation(t(), Csilgen.Generated.LookupOperationRequest.t()) ::
          Csilgen.Generated.LookupOperationResponse.t()
  def lookup_operation(%__MODULE__{transport: transport}, req) do
    resp =
      Csilgen.Generated.Transport.call(
        transport,
        "CorndogsService",
        "LookupOperation",
        Csilgen.Generated.LookupOperationRequest.to_cbor(req)
      )

    Csilgen.Generated.LookupOperationResponse.from_cbor(resp)
  end
end
