# Code generated by csilgen; DO NOT EDIT.

defmodule Csilgen.Generated.CorndogsServer do
  @moduledoc "Server handler behaviour + routers for the CorndogsService service."

  @callback submit_task(req :: Csilgen.Generated.SubmitTaskRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.SubmitTaskResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_task_state_by_id(req :: Csilgen.Generated.GetTaskStateByIDRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.GetTaskStateByIDResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_next_task(req :: Csilgen.Generated.GetNextTaskRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.GetNextTaskResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_task(req :: Csilgen.Generated.UpdateTaskRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.UpdateTaskResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback complete_task(req :: Csilgen.Generated.CompleteTaskRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.CompleteTaskResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback cancel_task(req :: Csilgen.Generated.CancelTaskRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.CancelTaskResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback clean_up_timed_out(req :: Csilgen.Generated.CleanUpTimedOutRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.CleanUpTimedOutResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_queues(req :: Csilgen.Generated.GetQueuesRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.GetQueuesResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_queue_task_counts(req :: Csilgen.Generated.GetQueueTaskCountsRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.GetQueueTaskCountsResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_task_state_counts(req :: Csilgen.Generated.GetTaskStateCountsRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.GetTaskStateCountsResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_queue_and_state_counts(req :: Csilgen.Generated.GetQueueAndStateCountsRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.GetQueueAndStateCountsResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

