name: Do releases
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  do-releases:
    name: Do releases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
      - if: ${{ steps.check-protos.outputs.protos-changed == 'true' }}
  release-protos:
    name: Release protos
    uses: ./.github/workflows/protos_release.yaml
    with:
      base-sha: ${{ github.event.pull_request.base.sha }}
    secrets:
      AUTOMATION_PAT: ${{ secrets.AUTOMATION_PAT }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
  release-corndogs:
    name: Release corndogs
    needs: release-protos
    if: ${{ always() }} # gaurantees this will run, but only after requirements
    uses: ./.github/workflows/corndogs_release.yaml
    with:
      base-sha: ${{ github.event.pull_request.base.sha }}
    secrets:
      AUTOMATION_PAT: ${{ secrets.AUTOMATION_PAT }}
      QUAY_DOCKER_REGISTRY_USER: ${{ secrets.QUAY_DOCKER_REGISTRY_USER }}
      QUAY_DOCKER_REGISTRY_PASSWORD: ${{ secrets.QUAY_DOCKER_REGISTRY_PASSWORD }}
  release-helm:
    name: Release helm chart
    needs: release-corndogs
    if: ${{ always() }} # gaurantees this will run, but only after requirements
    uses: ./.github/workflows/helm_release.yaml
    with:
      base-sha: ${{ github.event.pull_request.base.sha }}
    secrets:
      AUTOMATION_PAT: ${{ secrets.AUTOMATION_PAT }}
