name: Do releases
on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main
    # paths:
    #   - protos/**
    #   - corndogs/**
    #   - helm_chart/chart/**
jobs:
  do-releases:
    name: Do releases
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
      - name: Get changed paths
        id: changed-paths
        run: |
          workflow_changed=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^\.github')
          if [[ $workflow_changed ]]; then
            echo "workflow_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "workflow_changed=false" >> "$GITHUB_OUTPUT"
          fi
          protos_changed=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^\protos/')
          if [[ $protos_changed ]]; then
            echo "protos_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "protos_changed=false" >> "$GITHUB_OUTPUT"
          fi
          echo "corndogs=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^corndogs/')"
          echo "helm_chart=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^helm_chart/chart/')"
      - run: |
          echo ${{ steps.changed-paths.outputs.workflow_changed }}
          echo ${{ steps.changed-paths.outputs.protos_changed }}