name: Do releases
on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main
    # paths:
    #   - protos/**
    #   - corndogs/**
    #   - helm_chart/chart/**
jobs:
  do-releases:
    name: Do releases
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
      - name: Get changed paths
        id: changed-paths
        run: |
          echo "test=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^\.github')" >> "$GITHUB_OUTPUT"
          echo "protos=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^\protos/')" >> "$GITHUB_OUTPUT"
          echo "corndogs=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^corndogs/')" >> "$GITHUB_OUTPUT"
          echo "helm_chart=$(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^helm_chart/chart/')" >> "$GITHUB_OUTPUT"
      - if:  ${{ startsWith(steps.changed-paths.outputs.test, '.github') }}
        run: |
          echo Got github