name: Do releases
on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main
    # paths:
    #   - protos/**
    #   - corndogs/**
    #   - helm_chart/chart/**
jobs:
  do-releases:
    name: Do releases
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
      - name: Get changed paths
        id: changed-paths
        shell: bash
        run: |
          diff=$(git diff --name-only HEAD ${{ github.event.pull_request.base.sha }}) 

          set +e
          workflow_changed=$(echo $diff | grep -q -m 1 -E '^.github/' ; echo $?)
          set -e
          echo "GOT WORKFLOW $workflow_changed"
          if [[ $workflow_changed = 0 ]]; then
              echo "workflow_changed=true" >> $GITHUB_OUTPUT
          else
              echo "workflow_changed=false" >> $GITHUB_OUTPUT
          fi

          set +e
          protos_changed=$(echo $diff | grep -q -m 1 -E '^protos/' ; echo $?)
          set -e
          echo "GOT PROTOS $protos_changed"
          if [[ $protos_changed = 0 ]]; then
              echo "protos_changed=true" >> $GITHUB_OUTPUT
          else
              echo "protos_changed=false" >> $GITHUB_OUTPUT
          fi
      - run: |
          echo ${{ steps.changed-paths.outputs.workflow_changed }}
          echo ${{ steps.changed-paths.outputs.protos_changed }}