name: Do releases
on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main
    # paths:
    #   - protos/**
    #   - corndogs/**
    #   - helm_chart/chart/**
jobs:
  do-releases:
    name: Do releases
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
      - name: Get changed paths
        id: changed-paths
        run: |
          git diff --name-only HEAD ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^protos\/'
          echo "Ran once"
          protos_changed=$(git diff --name-only HEAD ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^protos\/')
          echo "GOT PROTOS $protos_changed"
          if [[ -z $protos_changed ]]; then
            echo "protos_changed=false" >> $GITHUB_OUTPUT
          else
            echo "protos_changed=true" >> $GITHUB_OUTPUT
          fi
          echo "Moving on"
          workflow_changed=$(git diff --name-only HEAD ${{ github.event.pull_request.base.sha }} | grep -m 1 -E '^\.github')
          echo "GOT WORKFLOW $workflow_changed"
          if [[ -z $workflow_changed ]]; then
            echo "workflow_changed=false" >> $GITHUB_OUTPUT
          else
            echo "workflow_changed=true" >> $GITHUB_OUTPUT
          fi
      - run: |
          echo ${{ steps.changed-paths.outputs.workflow_changed }}
          echo ${{ steps.changed-paths.outputs.protos_changed }}