name: Upload chart  
on:
  release:
    types:
      - released
jobs:
  upload-chart:
    if: ${{ startsWith(github.event.release.name, 'helm_chart') }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Upload chart
        uses: catalystcommunity/action-upload-chart-git@v1
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          tag: ${{ steps.semver-tags.outputs.new_release_git_tag }}
          release-asset-label-contains: "Helm_chart"